### ISSUE TITLE
Tiles should get synth patch numbers

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#106]
From the Quatschmacher post:

> Numbers on the tiles would help (corresponding to the Prophet’s own numbering of 5x8 would be good). This is especially the case of one has imported a bank and all patches are labelled “basic program” - it’s hard to use the compare tool in those instances.

**Comment by Florent-H** [comment]
Any luck on implementing patch numbers by the patch names?

**Comment by christofmuc** [comment]
@Florent-H Oh, right, I need to investigate this! The problem is not so much displaying the numbers (more the question where to put the UI button that toggles the display without making an even more quirky user experience), but if the data is properly stored during import. I need to sit down and test it again, but the plan was always that the numbers should be there unless it is an edit buffer import, which has no program place embedded. Will go looking into this for the next release!

**Comment by christofmuc** [comment]
@Florent-H I added a little subtitle to the buttons - this is not a perfect solution as it clutters the display, but is good to get started in debugging. Once I know the numbers make sense for the synths, I can add a UI mode switch that switches between the name and the number on the tile.

**Comment by Florent-H** [comment]
@christofmuc Great! Will take a look when I'm back in my studio in a couple of days.
