### ISSUE TITLE
New feature: Send patches to somebody else

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#11]
This came from a YouTube comment:

"Is it possible to store selfmade presets from the Prophet on Mac with this software, so i can send it to a friend?"

Very good question! As of now, the only way would be to share your database of all patches with him, but I can easily add a function to store the patches as a sysex file to either import into his Orm, or to send directly to the prophet. I'll add an enhancement idea to my list. I think the easiest way would be to just export all current patches into individual files (one .syx file per patch) - those would be edit buffer files that you can send to the synth without having to worry about overwriting any content or any bank. Thank you!

**Comment by christofmuc** [comment]
Implemented this the quickest way possible which is to export the patches as edit buffer sysex files, individually zipped into  one big zip file. More complex would be the implementation of back management, but that is another issue.

**Comment by Andy2No** [comment]
FWIW,  I've been using the Edit buffer Dump Request method, manually.  It has the advantage that the patch doesn't have a location associated with it - you send the dumped file back to the synth and it's loaded into the edit buffer, so you can play it and then save it manually, to wherever you want.

I use Bome's Send SX, in Windows.  but most sysex utilities should work.

The sysex to send to the synth to get the current edit buffer is:

F0 01 2A 06 F7

I've attached a zip file containing the sysex file with just that command in it - github doesn't allow me to attach the .syx file directly.

[Edit Buffer Dump Request.zip](https://github.com/christofmuc/KnobKraft-orm/files/5209998/Edit.Buffer.Dump.Request.zip)

**Comment by christofmuc** [comment]
This was implemented in version 1.7, there is a new function called "Export into sysex files" that will simply write all patches currently visible (i.e. filtered by the search functions) into a single ZIP file containings one sysex file of an edit buffer dump per patch. This can be either sent directly into the synth or just imported by the KnobKraft Orm on the other computer via the import sysex files from computer mechanism.

![grafik](https://user-images.githubusercontent.com/5006524/95652425-263f2280-0af1-11eb-8ca2-d54a8cc84855.png)
