### ISSUE TITLE
Ensoniq ESQ-1 adaptation

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#120]
I have started a discussion #119 and a [Wiki page](https://github.com/christofmuc/KnobKraft-orm/wiki/Ensoniq-ESQ-1) for the Ensoniq ESQ-1, and attached a working adaptation for it.
[ensoniqesq1.88.zip](https://github.com/christofmuc/KnobKraft-orm/files/7619353/ensoniqesq1.88.zip)

NB: remove the version number characters (.88) from the file name before use.

**Comment by Andy2No** [comment]
The way to attach most things, on Github is to put it in a .zip file, because that's one of the allowed file types.

Under the box you type in, you should see a message that says "Attach files by dragging & dropping, selecting or pasting them.".  If you click that, you should see a File Open dialog box - or you can try dragging the zip file into the box you type in.

**Comment by Mostelin** [comment]
Thanks for the tip. I've amended the original post and added the zipped file.

**Comment by christofmuc** [comment]
@Mostelin Awesome, Marc! You have done a great job wading through the documentation to get this working! I'll include it as a standard module with the next official KnobKraft release, if that is ok with you! Let me know if there is any more you need, but I understand you figured out the fingerprinting etc. by now :-)?

**Comment by Mostelin** [comment]
Yes, please feel free to include this in the next release, and thanks for kicking off such a useful project.

It turns out fingerprinting on the ESQ family is very easy; as soon as I realised what you were trying to do in that function, it was solved.

At some stage I may implement the renaming function. It will require compiling some kind of lookup table, I think, as the encoding is not just ASCII.

**Comment by christofmuc** [comment]
@Mostelin Good idea on the lookup table. For the simple case, you could to something like I did in the not yet finished Roland D50 adaptation, there you'll find code on how to do this in Python. In your case, it will be a bit (but only a bit) more involved with some "characters" needing a string as representation as with the "1." case, but it shouldn't be too hard.

**Comment by Mostelin** [comment]
Thanks for the suggestion. I can't find the Roland D50 adaptation you mention, though.

However, I think I have a form of 'lookup' working now, using a short Python dictionary. There's just one hiccough: the code for "8." is ASCII hex 5C (backslash \) and is causing odd behaviour. I don't understand why. It works OK when translating from decimal 92 in the adaptation, but not when translating from the text "C5" (reverse-order hex) in my JSON file generator, where programs are processed as text. I may get some time for debugging today. Stay tuned.

**Comment by Mostelin** [comment]
Here's the latest revision, 0.9, which now includes better name translation from synth to ORM.
[ensoniqesq1.90.zip](https://github.com/christofmuc/KnobKraft-orm/files/7653057/ensoniqesq1.90.zip)

**Comment by christofmuc** [comment]
Released with version 1.13.5
