### ISSUE TITLE
Null character causing log message truncation?

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#125]
Some patches have been created with null character (represented as 00) in place of space character (represented as 02) in their names. Even when names are composed so that null is replaced by space, or nothing at all, the presence of null is still felt when sending the patch to the synth. The log message reads, for example,

`Sending patch BOSTR `

instead of 

`Sending patch BOSTR to Ensoniq ESQ-1`

In this case, the sixth character in the name part of the program data is still 00, but the sixth character in the name field has been replaced by space (which does actually appear in the log message).

**Comment by christofmuc** [comment]
@Mostelin Let me see - the text output by the log is derived from calling nameFromDump() in Python - this should return a clean string and no 0 characters. I would be surprised if the C++ code inserted 0 characters ;-) 
Can you export the patch to syx and attach it here? The Orm will export a single syx if you e.g. search for the exact name and have only the desired patch visible in the grid, and then press export to syx.

**Comment by Mostelin** [comment]
@christofmuc 
Christof
As you requested, here is a single-program sysex file that has NULL in its name. It is valid, in that I checked that the syunth accepted it and played it properly. This program is also one of the five I am sending you in the short PIF, regarding the other problem.
[BOSTR.zip](https://github.com/christofmuc/KnobKraft-orm/files/7660676/BOSTR.zip)

**Comment by christofmuc** [comment]
@Mostelin No problem! Just upload the new version to the (closed) ticket, I'll pick it up from there. You can override the built-in adaptation with a newer script when you put it into the adaptations directory and a log message on startup will tell you that you are not using the built-in adaptation. The user directory is chooseable from the Setup task.

**Comment by Mostelin** [comment]
OK. Here's version 0.91 of the Ensoniq ESQ-1 adaptation. Fingers crossed.
[ensoniqesq1.91.zip](https://github.com/christofmuc/KnobKraft-orm/files/7664204/ensoniqesq1.91.zip)
