### ISSUE TITLE
Request: Add AND logic to tag selection

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#126]
At present (ver 1.13.5), tags appear to combine using OR. Hence, if you select both Pad and Organ, the results will include all Pad programs plus all Organ programs. There seems to be no simple way to find only programs which are tagged as both Pad AND Organ.

Use case : I might like to select, say, ESQ-1 AND Pad, deliberately excluding SQ-80 Pads. Naturally, on another occasion, I may wish to see all Pads.

Perhaps this feature could be made available under Advanced filters, where it appears that the synth itself can already be used as a filter. Yet it is not clear how the user could use this to pre-filter results as, if I recall correctly, only the programs for the currently selected adaptation will be available.

**Comment by christofmuc** [comment]
@Mostelin Very good point. I believe the AND search is a special case, OR is default. For your usecase, of course AND makes sense. One idea - the text search is AND based, I could add the text searched to include the tag names (probably exact), so you could use the text search box to insert ESQ-1, and then continue to use the tag buttons as now? 

That's a rather spontanous idea, and it doesn't document itself very well, but then again, also the UI for the search is difficult to master.

**Comment by Mostelin** [comment]
> One idea - the text search is AND based, I could add the text searched to include the tag names (probably exact), so you could use the text search box to insert ESQ-1, and then continue to use the tag buttons as now?

Yes, that would be worth a try.

**Comment by christofmuc** [comment]
@Mostelin Ha! The new release 1.14.0 is out today, and I added a checkbox "All must match" that turns the OR search into an AND search. Let me know if it works for you!

**Comment by Mostelin** [comment]
Thank you very much! I've started playing with this feature and it looks good so far - definitely meets my personal use case. I have fallen behind a bit with my work on categorisation, but I will pick up the thread and report back to you anything of interest.

Meanwhile, your other changes look interesting too...
