### ISSUE TITLE
Patch numbers displayed overlay other text depending on zoom view

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#127]
This came up in #77, but I think needs its own issue because it is kind of a bug.

In this:

  - I want a configurable display on the button. Either "patch number only", "short name", or "full name" (including layer names). Where to put that selector?
  - Then the button is too small for the selected display, what should happen? Automatically switch to a lower detailed plot, or rather accept overlap? You can always increase the button size now, to make it fit again.

**Comment by christofmuc** [comment]
@Andy2No We could also somehow make the display configurable per synth -
like "line 1", "line 2", subscriipt ->
assign "Patch name", "layer 1 name" (when synth has layers), or "Program Number". Then we could match the display more closely to what the synth displays, and if you don't have enough space, you can reconfigure.

Just switching wouldn't be so fast then.

**Comment by Andy2No** [comment]
@christofmuc Maybe each adaptation could have a function to return the patch name, plus another to return the bank/patch number, as a string, to make it flexible... I'm not clear if that's what happens already.

There could also be functions to control the layout, e.g. one to return position within the button, just which line to put it on.  There could also be things like basic style controls, e.g. embedded in the returned strings for the patch name or number, etc... but it all seems like adding complication for not much reason.

I think what you have now would be fine for any case, but the layout needs adjusting to use the space better.  I see empty space above the patch name, which it could be moved up into, allowing more space for the patch number so it doesn't overwrite it so easily.

Here are a couple more screenshots.  I've been trying different system font/dpi scalings on my 1360x768 monitor, and I'm currently on 150% - I'm still not sure how much that affects Orm, but I thought I should mention it.  The first is with Vew Scale set to 150%; the second has it set to 175%.  In both cases, it looks like there is room for both lines to be shown and not overlap, if they were placed differently.

Maybe the patch number line should be centred horizontally too?

150% view scaling:

![1_14_0 fonts 150, view scale 150](https://user-images.githubusercontent.com/8021302/147884614-271fccac-5beb-4df7-8c21-946715822323.gif)

175% view scaling:

![1_14_0 fonts 150, view scale 175](https://user-images.githubusercontent.com/8021302/147884636-f3862781-caea-4f49-a43a-feec582ac0d3.gif)

**Comment by Andy2No** [comment]
I also meant to say, if there were/are functions to return the patch name, and the patch number (possibly also containing the bank number), and those were allowed to return an empty string, that could help to make it configurable per synth - provided the layout adjusts accordingly.

So, if a synth doesn't use patch names, it would just return an empty string for that.  Orm would then adjust the layout of the display to show just the non-empty patch/bank number string.

**Comment by christofmuc** [comment]
@Andy2No This is done now by providing 4 different modes for the display on the buttons themselves, using the new combo box, It persits the setting per synth, so one could choose e.g. numbers only for a synth that never had patch names, and layers for something like the Rev2 where 2 layers have 2 different names...

**Comment by Andy2No** [comment]
@christofmuc Cool.  I can see how that could be useful, for the Prophet 12 desktop... on a large enough monitor.  I guess that functionality would have to be added to the adaptation, to make it work.

Would it be possible to move the patch names up a little?  I'm still getting the number running into the name, but there's some empty space above the patch names, when I choose Name and # or Layers and # 

The patch names are centred in their buttons vertically, which means the patch numbers are squashed into the same height as the blank space above the names, in each button.  If the names could be moved up by about half the height of the empty space above them, there would be enough room to show both tidily, without them touching or overlapping.

See attached screenshot:

![1_15_0 patch numbers running into names](https://user-images.githubusercontent.com/8021302/164995683-b6e5b151-1e7c-4b78-8402-fd30ed267ff0.gif)

**Comment by christofmuc** [comment]
@Andy2No Sure, I could use the space better. I think the main reason was the favorite Icon, but as this is in the corner, it still might work. Why do you say this needs support by the adaptation? Does it have layer names? Or do you mean the program numbers?

**Comment by Andy2No** [comment]
The Prophet 12 has two layers to each patch, each with its own name, but the Library only shows one of them (Layer A, I think), if I choose Layers and # - it looks the same as if I choose Name and # 

I assumed that meant the adaptation would need another function or two adding, to let it return both names.

I wouldn't really have the space to show them both, personally, so I probably wouldn't use it much.  Someone with a monitor with more lines might want to though.

**Comment by christofmuc** [comment]
@Andy2No Ah, I get you! Yes, it could be that the layer name capability is missing for the generic adaptation is only available in C++. I use it with the Rev2, and that is C++ code where a lot of more thing were possible. I'll create a new ticket for that. Might also make sense for the Pro2 and Pro3, I think those are layered as well.
