### ISSUE TITLE
Category assignment buttons too small for touchscreen use

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#128]
This came up in #77:

"Can you make the category assignment buttons bigger or resizable? I mainly use the touchscreen of the laptop which works great for selecting patches but is rather fiddly when assigning categories and/or favoriting/hiding patches."

**Comment by christofmuc** [comment]
@Andy2No We could also somehow make the display configurable per synth - 
like "line 1", "line 2", subscriipt ->
assign "Patch name", "layer 1 name" (when synth has layers), or "Program Number". Then we could match the display more closely to what the synth displays, and if you don't have enough space, you can reconfigure.

Just switching wouldn't be so fast then.

**Comment by christofmuc** [comment]
@markusschloesser Just for you, this is done ;-)

**Comment by markusschloesser** [comment]
@christofmuc love it, thank you! 😊
