### ISSUE TITLE
Building in Windows - where to get CMake 3.18, or how critical is the version number?

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#137]
In the readme, on the Code page, it says "We use CMake 3.18.", but unless I'm misunderstanding their site, the oldest version available now is 3.21.

Is there a way to still get 3.18?  Is 3.21 likely to be close enough, or is it better to get the latest stable release and try to hack it until it works?

I was thinking of trying to see what's needed to add a timeout option, for the patch dump function #136 , but if I need to change things just to get it to compile, I'm not sure how useful a contribution that would be, especially if it then didn't compile in CMake 3.18.

Also, I know nothing at all about using git properly, or pull requests :)

**Comment by christofmuc** [comment]
@Andy2No CMake 3.18 is the minimum version, and as CMake is generally nicely backwards compatible you can use any version that is at least 3.18!

Don't worry about PRs or anything, if the changes are small I can just integrate them into the release for you.
