### ISSUE TITLE
1.14.1 "Import sysex files from computer" button is not working

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#142]
Clicking the "Import sysex files from computer" button is having no effect, in 1.14.1.  I'm not sure if that was already the case in 1.14.0.

I don't currently have a synth connected, so maybe the problem relates to that.  I'm fairly sure it worked to import patches into the database, without one actually connected, in earlier versions.

I'll try later with one connected, but it seems like it shouldn't matter, since the target of that operation is the database, not a synth.

Nothing appears in the log window, when I press it.

This is on Win 7 SP1 x64.

See also #143

**Comment by christofmuc** [comment]
@Andy2No No, I agree, the import sysex file button should work no matter if the synth is connected (green bar) or not.

**Comment by christofmuc** [comment]
@Andy2No So this is back? This is really weird, I would have expected a log error somewhere. I'll close it anyway ;-)
