### ISSUE TITLE
After update with WinSparkle, the KnobKraft Orm is not relaunched

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#146]
Seems this is a feature and not a bug: https://github.com/vslavik/winsparkle/issues/132

**Comment by christofmuc** [comment]
https://stackoverflow.com/questions/3767227/run-application-after-successful-install

**Comment by christofmuc** [comment]
Hm, disabling the FinishedPage in the Innosetup installer will re-launch. But it will also auto-launch on first install, which may not be a bad thing. 

Have to test this with the 1.15.0.

**Comment by christofmuc** [comment]
That change did not work!? Maybe I need to look again at the InnoSetup docs.

**Comment by christofmuc** [comment]
Tested, this started working again with 2.0.5

**Comment by markusschloesser** [comment]
confirmed, working fine here. Neat improvement!
