### ISSUE TITLE
Scrollbars for scalable stuff

### ISSUE THREAD

**Issue by BenMcLean** [christofmuc/KnobKraft-orm#151]
I love that the UI is scalable. Makes it easy to read stuff in the app for low vision people like myself. However, the panel on the far right makes some buttons inaccessible when scaled higher. They go off screen and there's no way to scroll down to them.

**Comment by christofmuc** [comment]
@BenMcLean Thank you, yes, the scalability is not done properly everywhere. I remember somebody also saying that the buttons are too small for touch screen mode anyway. 

What are your screen settings, like resolution and font scaling? Are you on Windows? I could give it a try on my machine and find a way to make it work.

**Comment by markusschloesser** [comment]
> I remember somebody also saying that the buttons are too small for touch screen mode anyway.

That was me! 😉

**Comment by BenMcLean** [comment]
> @BenMcLean Thank you, yes, the scalability is not done properly everywhere. I remember somebody also saying that the buttons are too small for touch screen mode anyway.
> 
> What are your screen settings, like resolution and font scaling? Are you on Windows? I could give it a try on my machine and find a way to make it work.

I have to change it a lot because there are **_so many apps_** which won't work right with high DPI. I'm at 175% "make everything bigger" (DPI) in Windows 10 right now and text at 150%, not because that's what I actually need to be able to read anything, but because any bigger and the descenders on the letters start getting cut off on a lot of apps.

**Comment by Andy2No** [comment]
> I have to change it a lot because there are **_so many apps_** which won't work right with high DPI. I'm at 175% "make everything bigger" (DPI) in Windows 10 right now and text at 150%, ...

FWIW, my workaround for the scaling problem is to switch screen resolutions.  I use 1360x768 (the actual native resolution of my TV/monitor) with 150% font scaling, most of the time, but some dialog boxes don't fit on the screen, mostly for height, so I switch to 1080p when I need to - and then squint or use the magnifier.

I'm using Win7.  To change the font scaling, I need to log out, closing everything in the process, but I can switch display resolutions without doing that.  I use the AMD Catalyst Control Centre, as a more convenient way of doing it, but it can also be done through the Control Panel.

**Comment by markusschloesser** [comment]
Fyi, you can have individual scaling PER app.

**Comment by christofmuc** [comment]
@BenMcLean I added scrollbars for the right hand side, so at least the software should be usable now. I didn't test with all possible resolutions/DPI/font sizes, but I beliebe this could work now. Thanks again for pointing it out!
