### ISSUE TITLE
Tetra adaptation can only import first two banks

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#160]
I'm trying the DSI Tetra adaptation, after updating mine to the final beta firmware.  When trying to "Import patches from synth", I'm only given boxes to tick for banks 1 and 2.  Those work, but the Tetra has 4 banks.

Having imported those, Import All goes through the motions, but doesn't import any more patches, so that also appears to only be looking at the first two banks.

**Comment by christofmuc** [comment]
@Andy2No That should be an easy fix, our code says the Tetra has 2 banks: https://github.com/christofmuc/KnobKraft-orm/blob/master/adaptions/DSI_Tetra.py.

Were there ever any other versions/compatible synths that only had 2? I might have taken that from the Manual, but then, those are often wrong as they are just created from the Manual of the previously released synth.

**Comment by Andy2No** [comment]
I don't think there were.  The Mopho is the monophonic version, but that has three banks, or at least the Mopho Desktop does.  I've never owned the keyboard version but I think it's the same.

The Tetra really has 5 banks, but the fifth is a special one for Combi mode... which may need an entirely different adaptations to support it, but personally, I'd be happy with just the 4 Program mode banks, of 128 patches.

**Comment by christofmuc** [comment]
@Andy2No Fixed with today's release.
