### ISSUE TITLE
Device Request - DSI Tempest

### ISSUE THREAD

**Issue by jmfreeland** [christofmuc/KnobKraft-orm#164]
I'm not even sure how feasible this is, but a Tempest librarian would be excellent given how hard it can be to create good sounds from scratch.

**Comment by christofmuc** [comment]
@jmfreeland Indeed! There is the hope that the Tempest is based on the same firmware as all other DSI products, they seem to have used a very stable common software base for all of their synths, and AFAIK the Tempest is more of a synth than a classic drum computer.

The official manual at http://www.davesmithinstruments.com/wp-content/uploads/2015/02/Tempest-Operation-Manual-v.1.4.pdf?765cbf sadly has no information on the sysex code, only that is has sysex. Which is good for a start.

This seems to suggest the packing of the data is not the same as the other DSI synths: https://forum.sequential.com/index.php/topic,5075.msg50397.html#msg50397. That might be bad.

The device ID though is documented here as 0x28: https://forum.sequential.com/index.php/topic,174.msg12220.html#msg12220 So with this, we might give the Generic Sequential module a try!

I opened a ticket with DSI support to see if they have any additional docs to provide us. User "van" on the forum has done a patch randomizer which would have all the information we need, but sadly its not open sourced.

**Comment by christofmuc** [comment]
I did the patch name extraction. That should already bring us a bit forward, even if there are many more unknowns for the Tempest. I posted this in the forums: https://forum.sequential.com/index.php/topic,5075.msg59905.html#msg59905

It seems the Tempest does have a different of RAM (aka edit buffer) and stored programs. The only file I have is type 0x63, and if it is a stored program I don't know where the storage location is in the file. I am looking at the factory presets, which I would assume are storage programs. Needs more data.

**Comment by christofmuc** [comment]
@jmfreeland Hi Josh, I started doing a Tempest adaptation, but I need more data. Could you record two different sounds into sysex, once from a flash memory position and once from the RAM?

**Comment by markusschloesser** [comment]
I have a Tempest, so happy to test and also can provide other sounds.
BUT: The sound hierarchy thing becomes more important with the Tempest (especially mine), because of the 3-tiered hierarchy (Project - Beats - Sounds).
Also would love to have a Tempest adaptation as my SOUNDS storage is full currently.

**Comment by christofmuc** [comment]
@markusschloesser Oh, that would be awesome if you could help. I have already found out how to extract the name (currently I am looking at sounds only), so next step would be to find out the difference between a RAM and a flash sound sysex file, and where in the sysex the position in the flash is.

**Comment by markusschloesser** [comment]
happy to help! :-) How would I do this? What else would you need?

**Comment by christofmuc** [comment]
@markusschloesser Initiate sound save operations from the device, and record them into Midi Ox/Sysex Librarian. The Tempest manual has the instructions on how to save sounds to sysex.

**Comment by markusschloesser** [comment]
And you need that for an edit buffer sound?

**Comment by christofmuc** [comment]
@markusschloesser Yes, for a "RAM sound" and for a "Flash sound", as the manual describes it. Potentially two flash sounds, or even better, the same sound stored in two different positions in the synth, to see where it stores the storage location.

**Comment by markusschloesser** [comment]
[kktests.zip](https://github.com/christofmuc/KnobKraft-orm/files/9277040/kktests.zip)finally had some time.
first test:
3 files
1. Sound "basic beat A1" after power on
2. basic beats with one param changed (OSC 1 Waveform).
3. same as 2 but OSC PWM changed again

2. has 2 bits different to 1 (fifth ( original is 0x03 changed is 0x01) and eighth
3. has 1 bit different to 2 (the eighth)


second test:
same as above but with Basic Beat A2 and pitch change instead of waveform change
[kktests.zip](https://github.com/christofmuc/KnobKraft-orm/files/9277063/kktests.zip)
strangely all 3 have only one bit changed (fifth)
[kktests.zip](https://github.com/christofmuc/KnobKraft-orm/files/9277077/kktests.zip)

third test
Sound "ananlogue drummer)
sound 1
completely confusing results

will try to do more testing later tonight, but right now it looks 🤪

**Comment by markusschloesser** [comment]
[kktests.zip](https://github.com/christofmuc/KnobKraft-orm/files/9277618/kktests.zip)
Basic A12 BD/Kick saved once from RAM and once from FLASH.
Ram is 154 bytes
FLASH is 174 bytes (I assume cos it includes the storage space infO9

**Comment by markusschloesser** [comment]
[analog 808 kick.zip](https://github.com/christofmuc/KnobKraft-orm/files/9277627/analog.808.kick.zip)
[909 AS1.zip](https://github.com/christofmuc/KnobKraft-orm/files/9277638/909.AS1.zip)
and 2 more, each as RAM and FLASH.

tbh I still don't understand the memory structure of the tempest. I though all SOUNDS were in the machine and also part of BEATS and PROJECTS. But I couldn't find a lot of SOUNDS when trying to export from FLASH, even though they are part of the current PROJECT.

**Comment by christofmuc** [comment]
My first attempt:

[DSI_Tempest.zip](https://github.com/christofmuc/KnobKraft-orm/files/9397911/DSI_Tempest.zip)

Thanks for the files! Looking at those now, it appears the RAM (edit buffer) dump simply has no name encoded in it, while the flash program has.

In this thread on sequential https://forum.sequential.com/index.php?topic=1297.0, Razmo commented 

"The only way to control all the data are by SysEx, and here it gets even worse. Only the currently selected sound can be dumped to Tempest, but not requested. Same goes for the current beat, but beats are packed data even beyond the usual SysEx packing scheme, so you would need special software to unpack these and obtain the algorithm from Sequential... Projects are the same, and the sheer size of such a dump is huge."

So it seems the Tempest has no request functionality, you aways have to send it from the device itself into the manual dump window. 

The only person ever getting anything from the Tempest format has been KoSv on the Sequential forum, or Konstantin, and he made the patch randomizer. But he withdrew the OpenSource, it is no longer to be found :-/

Maybe if we contact him nicely?

Sadly, the last post in the Sequential forum on the Tempest is exactly my request... https://forum.sequential.com/index.php/topic,5075.msg59906.html#new

**Comment by markusschloesser** [comment]
https://algorithmic-instruments.com/js/randomizer.wasm  don't know if you can anything with this?
Will take a look at the adaptation asap! :-)

**Comment by christofmuc** [comment]
@markusschloesser I am aware or that site!

**Comment by markusschloesser** [comment]
> @markusschloesser I am aware or that site!

No, I meant the code (you were looking for), seems to be in the wasm file (but I of course, I could be completely wrong about that 😂)

**Comment by christofmuc** [comment]
The DSI Tempest adaptation was released with 1.17 in Oct 2022. I guess I'll close this until there is more interest again.

**Comment by markusschloesser** [comment]
I am still very much interested, but haven't gotten around to dive deeper into my Tempest (too many other newer, less hassle synths 😇😁
I will come around at some point :-)

**Comment by christofmuc** [comment]
no worries, I am just cleaning up a bit :-)
I got myself a 3rd Wave, really love it and I think it will keep me busy for a while, so I know what you mean!

**Comment by markusschloesser** [comment]
https://www.modwiggler.com/forum/viewtopic.php?t=299526

Someone is working on things, also pym commented. I'll leave this here for documentation purposes

**Comment by christofmuc** [comment]
This sounds promising!
