### ISSUE TITLE
Name search box seems to be missing, in 1.16.0

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#171]
I've used the patch name search box before, though I can't be sure which version I last used it in.  In 1.16.0, I can't find it.

Possibly it's just a user interface change that I've missed reading about, or maybe it's caused by my system font size setting?  It doesn't matter what zoom level I set in the Orm; I still don't see a search box.  I seem to remember it was next to the category filter tick boxes, before. 

See attached.  Off topic, I found the factory sounds set for the Tetra, and the bank and patch numbers are showing correctly when I import it.  That's what's showing here - but if there's a search box, I can't see it.

![1_16_0 can't find the search box](https://user-images.githubusercontent.com/8021302/181876002-5a5bf00c-a4c5-4cea-a3cb-d3dd1fb507f9.gif)

**Comment by Andy2No** [comment]
For comparison, here's a screenshot I've shown before, of 1.15.0, which shows the search box to the left of the top row of tick boxes:


![1_15_0 patch numbers running into names](https://user-images.githubusercontent.com/8021302/181876216-c70b4180-5019-45dc-854a-849b6b05c6a9.gif)

**Comment by Mostelin** [comment]
I was just about to report the same issue.

**Comment by christofmuc** [comment]
@Mostelin @Andy2No Oh dear, a wrong commit that was meant for a prototypical touchscreen-only version went into the master branch. Will release a 1.16.1 with a fix!

**Comment by christofmuc** [comment]
Hotfix 1.16.1 released.

**Comment by Andy2No** [comment]
@christofmuc It works fine in 1.16.1.  Thanks :+1:
