### ISSUE TITLE
FR: Change the Program number on the Synth when i am selecting the related program in KnobKraftOrm

### ISSUE THREAD

**Issue by planist79** [christofmuc/KnobKraft-orm#176]
KnobKraftOrm is a great tool! Thank you. 
I use it for my [Korg DW-8000. One or two requests i have, maybe you can comment?

1. Would it be possible to change the Program number on the [DW-8000] when i am selecting the related program in KnobKraftOrm?
So, instead of sending the sysex patch parameters to the edit buffer, better send the sysex patch parameters directly to the corresponding program on the [DW-8000](https://gearspace.com/gear/korg/dw-8000).

The Sysex for choosing the program number and sending the sysex patch parameters to program 1 and 2 and so on would look like this:
C0 00
F0 42 30 03 40 00 0F 1F 00 00 00 00 00 00 1A 00 00 00 00 14 0D 00 00 00 0D 02 17 07 1F 0B 09 00 00 10 04 1F 00 07 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 F7
C0 01
F0 42 30 03 40 00 0F 1F 00 00 00 00 00 00 1A 00 00 00 00 14 0D 00 00 00 0D 02 17 07 1F 0B 09 00 00 10 04 1F 00 07 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 F7
and so on...

Thank you, Peter

**Comment by christofmuc** [comment]
@planist79 Hi Peter! Thank you for the suggestion! I hadn't though of that before - basically when I understand you correctly the idea would be that if the position of the patch is known, *additionally* to sending the patch to the edit buffer is to send a program change? That would make sense, and I would think it is especially great when you then want to change the patch and then immediately write it to that program place.

I think we could make this an option - some synths might be slow when getting program changes, and it is not a good idea to immediately send an edit buffer. The DW8000 is quite fast I think.

Also note, this willl not work for all programs - not for all of them the original program place is known, e.g. if you read a single patch sysex file without program change in it, the DW8000 wouldn't know where this program is coming from.

I'll take this on the enhancement list, shouldn't be hard!

**Comment by christofmuc** [comment]
@planist79 Oh, and to persist the changed program, the DW8000 offers another command - it is called the WRITE_REQUEST in the manual. 

Basically it looks like this:

    f0 42 30 03 11 <program> f7

That is the command that needs to follow the send to edit buffer for the synth to store it. Else the next program change will lose  the program just sent.

We could make that another option - the reason I didn't do it was that this is a potentially destructive operation. If you have a patch in that place which is not backuped, you'll lose it. If KnobKraft only writes to the Edit Buffer, you cannot lose patches accidentally.

Also, I am working on a bigger feature for complete bank management: #9

**Comment by christofmuc** [comment]
@planist79 The KnobKraft Orm 2.0.0, released today, has the feature to manage the banks, and also send program changes when it knows the patch is in the synth already. It does this transparently - if the patch is marked as stored in the synth's bank, it will program change, else it will send it via sysex into the edit buffer. Give it a try, it is a beta release and I am looking for feedback!
