### ISSUE TITLE
Build Fails on Fedora 37 with Python 3.11

### ISSUE THREAD

**Issue by ryanpg123** [christofmuc/KnobKraft-orm#191]
[ 72%] Building CXX object adaptions/CMakeFiles/knobkraft-generic-adaptation.dir/CreateNewAdaptationDialog.cpp.o
In file included from /home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/attr.h:13,
                 from /home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h:45,
                 from /home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/embed.h:12,
                 from /home/ryanpg/src/KnobKraft-orm/adaptions/GenericAdaptation.h:18,
                 from /home/ryanpg/src/KnobKraft-orm/adaptions/CreateNewAdaptationDialog.cpp:9:
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h: In function ‘std::string pybind11::detail::error_string()’:
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:446:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  446 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
      |                                    ^~
In file included from /usr/include/python3.11/Python.h:42,
                 from /home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/detail/common.h:124,
                 from /home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pytypes.h:12,
                 from /home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:13:
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:446:75: error: expected primary-expression before ‘>’ token
  446 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
      |                                                                           ^
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:446:77: error: expected primary-expression before ‘)’ token
  446 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +
      |                                                                             ^
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:448:29: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  448 |                 handle(frame->f_code->co_name).cast<std::string>() + "\n";
      |                             ^~
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:448:64: error: expected primary-expression before ‘>’ token
  448 |                 handle(frame->f_code->co_name).cast<std::string>() + "\n";
      |                                                                ^
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:448:66: error: expected primary-expression before ‘)’ token
  448 |                 handle(frame->f_code->co_name).cast<std::string>() + "\n";
      |                                                                  ^
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/cast.h:449:26: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  449 |             frame = frame->f_back;
      |                          ^~
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h: In function ‘pybind11::function pybind11::detail::get_type_override(const void*, const type_info*, const char*)’:
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h:2291:49: error: ‘PyThreadState’ {aka ‘struct _ts’} has no member named ‘frame’; did you mean ‘cframe’?
 2291 |     PyFrameObject *frame = PyThreadState_Get()->frame;
      |                                                 ^~~~~
      |                                                 cframe
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h:2292:41: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 2292 |     if (frame && (std::string) str(frame->f_code->co_name) == name &&
      |                                         ^~
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h:2293:14: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 2293 |         frame->f_code->co_argcount > 0) {
      |              ^~
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h:2296:18: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 2296 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
      |                  ^~
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
In file included from /usr/include/python3.11/Python.h:38:
/home/ryanpg/src/KnobKraft-orm/third_party/pybind11/include/pybind11/pybind11.h:2296:30: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
 2296 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
      |                              ^~~~~~~~~~~~~~~~
/usr/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
   22 | typedef struct _frame PyFrameObject;
      |                ^~~~~~
/home/ryanpg/src/KnobKraft-orm/adaptions/GenericAdaptation.h: At global scope:
/home/ryanpg/src/KnobKraft-orm/adaptions/GenericAdaptation.h:46:15: warning: ‘knobkraft::GenericAdaptation’ declared with greater visibility than the type of its field ‘knobkraft::GenericAdaptation::adaptation_module’ [-Wattributes]
   46 |         class GenericAdaptation : public midikraft::Synth, public midikraft::SimpleDiscoverableDevice,
      |               ^~~~~~~~~~~~~~~~~
gmake[2]: *** [adaptions/CMakeFiles/knobkraft-generic-adaptation.dir/build.make:76: adaptions/CMakeFiles/knobkraft-generic-adaptation.dir/CreateNewAdaptationDialog.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1233: adaptions/CMakeFiles/knobkraft-generic-adaptation.dir/all] Error 2
gmake: *** [Makefile:156: all] Error 2

**Comment by ryanpg123** [comment]
Wondering if there's something I can do to assist. Seems to me to be related to Python 11, but I'm not a programmer. Please let me know, I'm excited to get back to using this awesome patch manager!

**Comment by christofmuc** [comment]
@ryanpg123 Hi Ryan, it seems the problem is indeed the very new Python 3.11. I am using pybind11 to help with the use of Python from C++, and that would require the latest version (2.10.1) of pybind11 to function. You can either:

- update pybind11 yourself (it is a submodule in third_party), or
- use a different version of Python (3.10 should work out of the box) by specifying the PYTHON_EXECUTABLE variable to be the full path to the python version you want to use and the PYTHON_VERSION_TO_EMBED to 3.10.
- or pull the latest master and try again, as I updated the pybind11 version myself. You'll end up with an untested 1.17.2, but we just want to know if your Fedora compile problem is gone.

**Comment by ryanpg123** [comment]
Thanks, Christof. I'm probably missing something basic here, but I'd
already tried building Master which fails with:

***@***.*** KnobKraft-orm]$ cmake -D
CMAKE_INTERPROCEDURAL_OPTIMIZATION=off -S . -B builds
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0")
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Checking for module 'gtk+-3.0'
--   Found gtk+-3.0, version 3.24.35
-- Checking for module 'glew'
--   Found glew, version 2.2.0
-- Checking for module 'webkit2gtk-4.0'
--   Found webkit2gtk-4.0, version 2.38.2
-- Found the following ICU libraries:
--   data (required): /usr/lib64/libicudata.so
--   uc (required): /usr/lib64/libicuuc.so
-- Found ICU: /usr/include (found version "71.1")
CMake Error at CMakeLists.txt:126 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/third_party/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:148 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/third_party/SQLiteCpp

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:151 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/third_party/JUCE

  does not contain a CMakeLists.txt file.


CMake Error at third_party/CMakeLists.txt:15 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/third_party/fmt

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:203 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/third_party/json

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:204 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/third_party/json-schema-validator

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:207 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/juce-utils

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:208 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/juce-widgets

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:209 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/MidiKraft-base

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:210 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/MidiKraft-librarian

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:211 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/MidiKraft-database

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:214 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-access-virus

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:215 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-BCR2000

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:216 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-kawai-k3

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:217 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-korg-dw8000

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:218 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-oberheim-matrix1000

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:219 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-roland-mks50

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:220 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-roland-mks80

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:221 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-sequential-rev2

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:222 (add_subdirectory):
  The source directory

    /home/ryanpg/src/KnobKraft-orm/synths/MidiKraft-sequential-ob6


"Reality is that which, when you stop believing in it, doesn’t go away."
-Philip K. Dick

**Comment by ryanpg123** [comment]
LOL, for future readers, the PKD quote is not part of the build error.

**Comment by ryanpg123** [comment]
Once I properly did git clone --recurse-submodules https://github.com/christofmuc/KnobKraft-orm, it builds and runs. Thanks!

**Comment by christofmuc** [comment]
@ryanpg123 Awesome! Happy to help!
