### ISSUE TITLE
1.10 does not recognize Matrix 6, 1.20 does not start at all

### ISSUE THREAD

**Issue by tsantilis** [christofmuc/KnobKraft-orm#2]
Hi, 

is the matrix 6 keyboard supported? My matrix 6 is not recognized at all - or I do domething wrong. 
Version 1.20 does not start. 

Running on Windows 10.
Regards,
Stratos

**Comment by christofmuc** [comment]
I only have a Matrix 1000 to test, but I think the differences to the Matrix 6 are really small, I will look into it if you can give feedback!

What does 1.2.0 say when starting, is there an error message? I could think that you need a working Python 3.6 installation, but would need to verify. Python can be installed from https://www.python.org/downloads/release/python-368/. 

If installing Python 3.6 fixes 1.2.0, I will update the docs!

**Comment by tsantilis** [comment]
Hi, Matrix 1000 seems a bit different than Matrix 6, e.g. there is the "edit" mode, which is required to be enabled if I use the Peavey PC1600 controller to edit the parameters.
What do I have to do to detect the Matrix 6 at all? Currently the Rev 2 is displayed (allthough I don't have a rev 2 unfortunately). Auto-Detect says no results.
Installation of Python didn't help unfortunately for 1.20, still nothing happens if I click on the 1.20 exe.

**Comment by christofmuc** [comment]
Normally it should show up in the top row? The "Setup" Tab should contain a list of synths, which you can switch "active", then they appear in the top row. Running "auto detect" would give a green light if the synth was detected. You're running 1.10? Should be in the Window Title, else it is the 1.0.0 which has only the Rev2.

I will look into the sysex documentation of the Matrix 6, should be easy to support.

**Comment by tsantilis** [comment]
Yes you are right it's 1.0, I was irritated by the URL that I found: 
https://github.com/christofmuc/KnobKraft-orm/releases/download/1.1.0/knobkraft_orm_setup.exe

This URL obviously contains 1.0 still. Where can I get 1.1 from?

**Comment by christofmuc** [comment]
I'm just testing the install problem, it seems 1.1.0 suffers from the same problem as 1.2.0 with a wrong DLL, which is why you still get 1.0.0 even after installing 1.1.0. Let me try to fix this, I'll let you know!

**Comment by christofmuc** [comment]
Phew, I uploaded release 1.3.0, which will hopefully fix the installer issues, can you give it a try? I also added a blind implementation of the Matrix 6, which we would have to test together.

**Comment by tsantilis** [comment]
OK it starts now and M6 is now visible, but nevertheless I can not say it is working. How can I "ping" the M6 ? 
I have received a lot or error messages in the log area.
[20200513 log.txt](https://github.com/christofmuc/KnobKraft-orm/files/4623502/20200513.log.txt)

**Comment by christofmuc** [comment]
Very good, one problem solved!

Can you check the content of the directory USER\Documents\KnobKraft-orm-adaptions? The faulty 
installer placed a file called test.py there which needs to be deleted. To ping the M6, turn off all synths except the M6 on the Setup page, and then switch to the MIDI log, clear it, and then run the MIDI... Auto-detect synths function again.

Paste the MIDI log here, so we can see what is going on with the M6.

**Comment by christofmuc** [comment]
One more bugfix - you can repace the file "Matrix 6.py" in the directory User\Documents\Knobkraft-Orm-adaptions with the attached file. (Remove the additional .txt extension so it is called .py)
[Matrix 6.py.txt](https://github.com/christofmuc/KnobKraft-orm/files/4623628/Matrix.6.py.txt)

**Comment by tsantilis** [comment]
Ok replaced the file content and deleted the test file.
Matrix 6 is green underlined now, but still error messages in the log. What is autoconfigure ? The same as auto detect?
19:36:53: Lost communication with Oberheim Matrix 1000 on channel 1 of device Scarlett 6i6 USB - please rerun autoconfigure!
19:36:54: Lost communication with Matrix 6/6R on channel 1 of device Scarlett 6i6 USB - please rerun autoconfigure!
19:37:03: No Matrix 6/6R could be detected - is it turned on?
19:37:19: No Matrix 6/6R could be detected - is it turned on?

**Comment by christofmuc** [comment]
yes, same thing.  Can you post the MIDI log from the MIDI log window?

**Comment by christofmuc** [comment]
Oh, and turn off the Matrix 1000 integration, just keep the M6.

**Comment by tsantilis** [comment]
Only M6 is active, nevertheless M1000 entries appear in the log (lost communication ...).
Here is the midi log:
00:00:00.000: Out Scarlett 6i6 USB Sysex [f0 7e 00 06 01 f7]
00:00:00.000: Out Scarlett 6i6 USB Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out Microsoft GS Wavetable Synth Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out QUARTET Midi Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out Scarlett 6i6 USB Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out Microsoft GS Wavetable Synth Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out QUARTET Midi Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out Scarlett 6i6 USB Sysex [f0 10 06 04 03 00 f7]

**Comment by christofmuc** [comment]
Ok, that looks not too bad - the M1000 is still referenced because it was activated once, don't worry.

This looks like the system is sending the proper Sysex information, but the M6 is not responding. Now I guess you need to configure it properly so it will reply - from the documentation, the package [f0 10 06 03 03 00 f7] should trigger it to reply with the master data dump package, but nothing seems to be sent. You could test with Midi OX, if you know how to handle that, or check the manual how to setup the M6 for MIDI sysex.

**Comment by tsantilis** [comment]
Hi, it was (partly) my fault yesterday I had only one midi patch cable (Matrix in) plugged, now I have in and out and the following result:
00:00:00.000: Out Microsoft GS Wavetable Synth Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out QUARTET Midi Sysex [f0 10 06 04 03 00 f7]
00:00:00.000: Out Scarlett 6i6 USB Sysex [f0 10 06 04 03 00 f7]
00:14:21.723: In  Scarlett 6i6 USB Sysex [f0 10 06 03 02 00 00 08 02 00 00 00 00 00 00 00 00 00 00 0f 03 0e 0f 00 00 0f 03 00 00 01 00 01 00 01 00 01 00 01 00 04 00 00 04 01 00 02 00 00 00 00 00 0b 01 00 00 00 00 00 00 01 00 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 00 02 00 03 00 04 00 05 00 06 00 07 00 08 00 09 00 0a 00 0b 00 0c 00 0d 00 0e 00 0f 00 00 01 01 01 02 01 03 01 04 01 05 01 06 01 07 01 08 01 09 01 0a 01 0b 01 0c 01 0d 01 0e 01 0f 01 00 02 01 02 02 02 03 02 04 02 05 02 06 02 07 02 08 02 09 02 0a 02 0b 02 0c 02 0d 02 0e 02 0f 02 00 03 01 03 02 03 03 03 04 03 05 03 06 03 07 03 08 03 09 03 0a 03 0b 03 0c 03 0d 03 0e 03 0f 03 00 04 01 04 02 04 03 04 04 04 05 04 06 04 07 04 08 04 09 04 0a 04 0b 04 0c 04 0d 04 0e 04 0f 04 00 05 01 05 02 05 03 05 04 05 05 05 06 05 07 05 08 05 09 05 0a 05 0b 05 0c 05 0d 05 0e 05 0f 05 00 06 01 06 02 06 03 06 00 00 01 00 02 00 03 00 04 00 05 00 06 00 07 00 08 00 09 00 0a 00 0b 00 0c 00 0d 00 0e 00 0f 00 00 01 01 01 02 01 03 01 04 01 05 01 06 01 07 01 08 01 09 01 0a 01 0b 01 0c 01 0d 01 0e 01 0f 01 00 02 01 02 02 02 03 02 04 02 05 02 06 02 07 02 08 02 09 02 0a 02 0b 02 0c 02 0d 02 0e 02 0f 02 00 03 01 03 02 03 03 03 04 03 05 03 06 03 07 03 08 03 09 03 0a 03 0b 03 0c 03 0d 03 0e 03 0f 03 00 04 01 04 02 04 03 04 04 04 05 04 06 04 07 04 08 04 09 04 0a 04 0b 04 0c 04 0d 04 0e 04 0f 04 00 05 01 05 02 05 03 05 04 05 05 05 06 05 07 05 08 05 09 05 0a 05 0b 05 0c 05 0d 05 0e 05 0f 05 00 06 01 06 02 06 03 06 3d f7]
This means that the Matrix 6 responds to the ping. Still an error message occurs "No Matrix 6 could be detected".  
From google I found out that there is an important difference between m1000 and m6. 
The m6 required an additional sysex command to react properly:

"A 5 bytes long string was send before the 7 bytes string was react to the M6.
F0 10 06 05 F7 and then:
F0 10 06 06 00 00 F7" 

Is this already done in your implementation?

**Comment by christofmuc** [comment]
Ah, great, we're getting there! No, this is the first time I hear about that opcode - I will also check why the detection is not happy, give me a sec!

**Comment by christofmuc** [comment]
Ah, sloppiness on my part. You need to change line 27 of the Matrix 6.py file from
   if (len(message) == 15
to 
   if (len(message) > 3

That was still a left over from the Matrix 1000.

I will make a new version today with the two fixes we found, and also add in the 5 byte string the Matrix 6 needs!

**Comment by tsantilis** [comment]
Ok, we are getting closer. Communication now happens! 
I could load all patches from the m6. I tried also to send patch info:

09:51:53: Found Matrix 6/6R on channel 4 replying on device Scarlett 6i6 USB when sending to Scarlett 6i6 USB
09:51:53: Adaption: Error, expected 236 bytes of master data 
09:51:39: Sending patch BED TRAK to Matrix 6/6R 

BUT the sent patch info does not have any effect on the M6 yet, I guess this is because of the missing opcode. 
I have previously switched to "patch edit" mode, this is required for the m6 to receive patch data, this is what I know also from the use of the Peavey 1600x controller.

**Comment by christofmuc** [comment]
The patch should be send into program slot 100 - can you change to that slot and see if patch 100 changes? The Matrix 6 has no "edit buffer" which would make it possible to send a patch to the synth without using a memory slot. In the Kawai K3, which is the same, I always send a program change to 100 after sending the patch, so automatically the program 100 is selected and I can hear the patch.

**Comment by tsantilis** [comment]
YES now it works, the patch is on position 99! 
It is even possible to play the notes over midi with another program (e.g. midiox or my DAW) and to switch patches in your tool! Great!
Is it also possible to provide a control panel for the patch parameters? That would be so great! 
Also to include this thing into a daw would be great ...

**Comment by christofmuc** [comment]
Ha ha, great! I will add the discussed changes, and also the switch to position 99.

The patch parameter panel is a different beast, I have a version that integrates with a BCR2000 controller bidirectionally, so you can switch the patch on the Matrix 1000 and all the BCR2000 led rings indicate the new patch. But with time, I am sure I'll add some capabilities to make a panel. 

The DAW integration is possible as well, but as I don't use DAWs right now, that might a bit more out. Be sure to follow and subscribe to the YouTube channel, I am trying to make more content available there soon.

**Comment by christofmuc** [comment]
Ok, I released version 1.4.0 with the fixes discussed. Before you install it, please save your working version of the Matrix 6.py file somewhere else, the installer will replace it and in case something goes wrong, we can look at the difference! I am closing this ticket now, but feel free to reopen!
