### ISSUE TITLE
2.0.0 Patch name missing from log when sending to synth

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#210]
I've just started playing with version 2.0.0 and noted that sent patch names are not being displayed as of old. See attached log.

[missing patch name.log](https://github.com/christofmuc/KnobKraft-orm/files/10425059/missing.patch.name.log)

**Comment by christofmuc** [comment]
Confirmed - I now only used the name or number, but should have used the database name for the log output. Will fix!

**Comment by christofmuc** [comment]
Fixed, up for release.

**Comment by christofmuc** [comment]
This was fixed with release 2.0.1
