### ISSUE TITLE
2.0.0 Slowish response when selecting 'By import' in the Library tab

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#211]

**Comment by Mostelin** [comment]
IIRC the list of import sources (files) was available immediately on start-up in version 1. This is not so in version 2 - at first I thought this was not working at all, but I see that it now takes about 4 seconds for the list of files to appear, and once it is open, switching between each file is accomplished quite easily and quickly. That delay is a bit annoying, though.

**Comment by christofmuc** [comment]
Indeed, there seems to be a missing index. I was trying to avoid touching this as my plan was to migrate the imports into proper lists (the banks, user banks, and user lists internally are the same thing, and imports should be those as well), but didn't do it yet to get the other stuff finished.

I could accelerate this on my database from 620 ms to 125 ms by creating an index, I'll give that a try for the next release!

This is what did it for me, could be applied by a SQL command line or wait until the new version is done:
CREATE INDEX i1 ON patches(sourceID);

**Comment by christofmuc** [comment]
This was fixed with release 2.0.1
