### ISSUE TITLE
2.0.0 Duplicate Names filter no longer sorts patches (and search is slow)

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#212]
Again, IIRC, in version 1 the selection of 'Duplicate Names' also sorted the resultant display of patches so that, for example, it was possible to see all examples of patches called DIGPNO displayed contiguously. This made it easy to deal with such cases when they occurred, but is no longer the case.

In an attempt to circumvent this problem I tried entering DIGPNO in the search box, but the program enforced a long 'Not Responding' wait for each character entered. This is now rather cumbersome, and it would simply be better to sort the result of a 'Duplicate Names' filter.

Incidentally, attempting to clear the search box by clicking the red X also results in a very long wait before results are redisplayed.

These search problems seem related to the specific 'Duplicate Names' filter, because seach works fine on unfiltered results.

**Comment by christofmuc** [comment]
Yes, I think something slowed down the search tremendously. Plus, the sorting is somehow broken as well, so it's really two bugs here. 

Notes to myself.
The current query is this:
SELECT * FROM (select md5, name as dup_name, synth, count(*) as name_count from patches where hidden = 0 and synth = "Yamaha Reface DX" group by dup_name, synth having name_count >1) as ordinal_table JOIN patches on patches.name = ordinal_table.dup_name and patches.synth = ordinal_table.synth 
WHERE 1 == 1  AND ( patches.synth = "Yamaha Reface DX" )  AND (hidden is null or hidden != 1) AND (name_count > 1) ORDER BY name, sourceID, midiBankNo, midiProgramNo 
Takes 507 ms to return 1020 lines in my database.

Faster version:
select * from patches where synth = "Yamaha Reface DX" and name in (
select name as dup_name from patches where synth = "Yamaha Reface DX" group by dup_name having count(name)> 1) order by name;
takes 337ms. Better but not fast. It needs an index CREATE INDEX i3 ON patches(name, synth);

It seems though the query is run more than once by the UI, that is something I need to look at next.

**Comment by christofmuc** [comment]
Ha! ChatGPT had the answer in seconds on how structure the query to produce the duplicates only and which index to create. It is faster than ever now, will be part of the next release. Sort order also fixed, that was a regression.

**Comment by christofmuc** [comment]
This runs in 274ms, with name,synth index:

WITH patches_count AS (
   SELECT synth, name, COUNT(*) as count
   FROM patches   
   GROUP BY synth, name
)
SELECT patches.*
FROM patches
JOIN patches_count
ON patches.synth = patches_count.synth
AND patches.name = patches_count.name
WHERE patches_count.count > 1  AND ( patches.synth = "Yamaha Reface DX" ) AND (hidden is null or hidden != 1)

**Comment by christofmuc** [comment]
Also fixed with release 2.0.1
