### ISSUE TITLE
2.0.0 bug: User banks will only send to bank #1 on the Prophet 5 rev4

### ISSUE THREAD

**Issue by Keinstrom** [christofmuc/KnobKraft-orm#216]
Steps to reproduce 
- use the Prophet 5 rev 4 adaptation 
- create a couple of new user banks
- make sure each bank is assigned a different bank number using the ˋnew bank´ dialog
- send each bank to the Prophet 5 rev4

Result
No matter which bank you send it is replacing bank #1 on the P5 rev4.

Note
Double clicking on the bank names in the user bank tree on the left hand side displays ‚bank #1‘ for all user banks although they were set to different bank numbers when they were created. Reassigning them again doesn’t work. The assignment doesn’t stick. Closing and opening the bank dialog will show them reverted to bank #1 again.

Interestingly the info text in the bank panel on the right hand side shows the correct bank number „… send to bank 1, 2, 3, etc.“. Out of curiosity I exported the database as a sysex file and sent it to the P5. Same result, all presets are send but overwrite bank#1 on the Prophet 5 rev4 in consecutive cycles. (Looks like the bank number is not set correctly in the sysex file.)

As I write this I didn‘t have another synth at hand to check if this issue is specific to the Prophet 5 rev4 adaptation or a more general bug of the new bank management feature.

thanks
-keinstrom-

**Comment by christofmuc** [comment]
Confirmed. Tested with the Prophet 5 adaptation, and what I see is that patches snap back to display their orignal location vs their assigned place in the user bank. Also, when the user bank is filled with the default patch, all items show the same patch position (which is wrong). This needs a deep copy object somewhere. I'll look into it!

**Comment by christofmuc** [comment]
Changing the bank was actually never implemented. The UI wasn't supposed to be shown, but I can see that this would be a useful feature, to retarget an existing bank. I think the main reason I did not allow it was that in some synths not all banks are the same, i.e. you might have a bank of tones and another bank of programs, and you shouldn't be able to switch the type of the bank. The banks could even have a different size. 

Workaround if you want to switch a bank would be to create a new bank, and then just drag the old bank one the new one, which would place all patches from the one bank in the other.

**Comment by christofmuc** [comment]
@Keinstrom The new 2.0.2 release (building right now) will address these issues. Sending to banks other than 0 should work as expected, and instead of being able to change the target bank of a user bank (which could cause the problems mentioned above), you can now drag a user bank in the tree onto the "add new user bank" text in the tree and drop it there - the dialog will open to have you create a new bank with the patches of the bank copied.

**Comment by Keinstrom** [comment]
Unfortunately this fix didn't work for me. User banks still send only to bank #1 on the P5/10.

**Comment by christofmuc** [comment]
Can you get me the MIDI log of an upload and a screenshot? I tested it in dry run mode and it worked with the Prophet 5 adaptation, but of course, without having the real device I might have missed something testing it :-/

**Comment by Keinstrom** [comment]
Moin Christof,
After deleting all previous generated databases, caches, preferences and installing version 2.0.2 - basically starting all over from a clean slate - I got it to work as described. So you may close this ticket. I realize this is still beta and I'm sure bugs and issues will shake out over time. I really enjoy the software. Thanks for your great work. -ts-

**Comment by christofmuc** [comment]
Moinsen, happy to hear this works, and glad you enjoy it! Spread the word!

**Comment by Keinstrom** [comment]
Jau… I'm spreading…
