### ISSUE TITLE
2.0.0 Pioneer Toraiz AS-1 adaptation does not detect device

### ISSUE THREAD

**Issue by bboc** [christofmuc/KnobKraft-orm#219]
When I connect the AS-1 via USB, KnobCraft can't detect it. The log says "error No Pioneer Toraiz AS-1 could be detected - is it turned on?"

When I set it up manually to the correct USB port and MIDI channel, it still doesn't work. 

However, when I use Soundtower on the same USB port and MIDI channel, it just works, so it's not the connection, not the device setup, and not the device itself.

**Comment by christofmuc** [comment]
@bboc Can you paste the MIDI log here after an unsuccessful detection attempt?

It should read something like

23:27:13.394: Out OB-6 Sysex [f0 7e 7f 06 01 f7]
23:27:13.395: In  OB-6 Sysex [f0 7e 02 06 02 01 2e 01 00 00 01 06 06 f7]

and many more messages.

**Comment by christofmuc** [comment]
It seems in our Toraiz adaptation the device ID is hardcoded as 0b00010000 or 16 decimal, 0x10 hex. I can remove that, not sure why this is done.

**Comment by bboc** [comment]
Did you test this with an AS-1? The AS-1 has no way to set the Device ID, so I would assume that is not the problem. Even after removing the Device ID check from the two other places where it occurs in that file, and the AS-1 set to Omni, 1 or 16,  I had no success?

**Comment by christofmuc** [comment]
@bboc No, I have no AS-1. Can you post the MIDI log of a failed detection here?

**Comment by bboc** [comment]
As you can see, no response from the AS-1 (even though the message is exactly like the AS-1 handbook says)

```
01:50:45.475: Out Toraiz AS-1 Sysex [f0 7e 7f 06 01 f7]
01:50:47.349: Out Blofeld Sysex [f0 7e 7f 06 01 f7]
01:50:47.350: In  Blofeld Sysex [f0 7e 0b 06 02 3e 13 00 00 00 31 2e 32 34 f7]
01:50:47.559: Out QuNexus Control Surface Sysex [f0 7e 7f 06 01 f7]
01:50:47.580: In  QuNexus Control Surface Sysex [f0 7e 00 06 02 00 01 5f 19 00 00 00 01 00 00 02 01 00 f7]
```

So I guess this is a bug in the AS-1, because I listened to what Soundtower sends to the AS-1 when polling it, and they send a request for a dump of the global parameters.

When I do the same, I get a response from which I can learn the MIDI channel.

```
02:20:45.399: Out Toraiz AS-1 Sysex [f0 00 40 05 00 00 01 08 10 0e f7]
02:20:45.400: In  Toraiz AS-1 Sysex [f0 00 40 05 00 00 01 08 10 0f 0c 32 00 04 00 02 02 01 01 02 01 01 00 00 00 01 04 03 00 00 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 f7]
```

Another thing I can look at once I have my adaptation for the Modor NF-1m up and running. 

Can you tell me what's the best way to fix/extend existing adaptations? I don't like editing the copy inside the program, because tracking changes is a hassle there. If I put it into the user adaptation dir, I have to change the device name to see what is the one I want to edit, but then my Library will break, because the device name is wrong. So I think it's best if I  delete the adaptation from the Contents/MACOS/adaptations directory  and symlink my local copy there, right?

BTW, have you considered putting the adaptations into a separate repo?

**Comment by christofmuc** [comment]
Indeed, it seems the documentation maybe wrong. Getting the global data dump is better anyway because you get the MIDI channel, I actually do the same for the OB-6. 

Good question about working on the shipped adaptations. The idea was that you set the user adaptation directory to the directory where your copy of the adaptation is. On launching KnobKraft, you see a warning message that your version of the adaptation overrides the one which is shipped, at least this is what was planned. Let me check, I might have broken it. 

Originally, the adaptations were compiled into the executable so they would not be on the file system. For some reason I abandoned that approach, not sure if that was smart. In the very beginning, they had their own repo, but then I reduced the number of repos because it became very unwieldy. Not sure about this. We might want a simple adaptation update mechanism that does not require a full installer rebuild though.

**Comment by christofmuc** [comment]
No, it still seems to work. Use the Options menu Set User Adaptation Dir and the system will prefer to load your adaptation for the synth instead of the one that was shipped with it, no need to change the Synth name.

**Comment by bboc** [comment]
Ok, will try that tomorrow. For now I just deleted all adaptations from the program and put everything I need into the user folder, because that gives me a small and manageable list. 

As I was stuck with my previous adaptation I started working on the AS-1 adaptation, device detection is now working fine, and I fixed a couple of small things. For testing this further, I need to understand what would trigger sending a program dump  and an edit buffer dump to the device, so that I can test the 7bit decode and encode functions. I probably need to rename a sound for that, right?

**Comment by christofmuc** [comment]
Edit buffer dumps are always created when clicking on a patch in the grid - it might need to patch the device ID or MIDI channel, so that function is always called when sending.

Program Dumps are currently only called when modifying a synth bank and sending the updated bank to the synth.

**Comment by bboc** [comment]
Toraiz adaptation is working now, I'll test some more with 2.0.1 tomorrow just to be sure.

About shipping adaptations: you could pack one or several adaptations into a zip-file, and change the extension to `.knobkraft`. The app can register that extension and import the contents when the user double-clicks the file.

**Comment by christofmuc** [comment]
@bboc That's a neat idea! We need to make sure it is cross platform though. This indicates it might work for windows and macOS, but Linux works differently: https://forum.juce.com/t/associating-file-formats-extensions-with-my-application/8649

I mean, ideally we would have an Internet repository of adaptations, but that is a whole new project. Maybe if we add Internet download capabilities into the Orm, it could download adaptations via the adaptation tab. Or we could add an "import adaptations" button there to browse to that zip file of adaptations.

The main question is how to publish adaptations. I had originally created a github repo for user-made adaptations, but not everybody was comfortable enough to work with git, so I kind of took this over and integrate fixes here in the main repo. Some come via email, some via pull request, some via issue thread.

**Comment by bboc** [comment]
For linux, an import dialog would work, or dragging an adaptation onto the program window. 

If you have a separate repo, as a first iteration KnobKraft could look at the the releases there (curl or github API), and download new releases. It's probably too much hassle tracking versions for all adaptations separately, and you want to have them in a repo anyway so that you can track changes.

**Comment by christofmuc** [comment]
I put some thoughts on adaptation distribution into #233, this needs a bit more thought as we also have to solve the versioning #123 . 

Let me know when you have the Toraiz adaptation ready, I'll include it here following the old process :-)

**Comment by christofmuc** [comment]
Closing as stale - let me know if you have a newer version of the Toraiz adaptation!
