### ISSUE TITLE
2.0.0 Bank panel still points to device that was removed

### ISSUE THREAD

**Issue by bboc** [christofmuc/KnobKraft-orm#222]
Given:
-  I have activated an adaptation in setup
-  and requested a bank from that device
When:
- I deactivate that adaptation
- and activate another adaptation
Then: 
- in the library I still see the Synth Bank window
- which points to the other device (with the adaptation deactivated)
- and I can click on "import again" and it imports that bank from the synth (even though device is present neither in the left sidebar, nor in the setup screen)

<img width="696" alt="image" src="https://user-images.githubusercontent.com/520442/219141108-3b862e5c-e3e2-4b36-b40c-736b3cf109a1.png">

**Comment by christofmuc** [comment]
Oh yes, that's a clear bug. It should clear the bank display.

**Comment by christofmuc** [comment]
This was fixed in the 2.0.2 release, just building.
