### ISSUE TITLE
2.0.1 Duplicate Names filter not behaving as expected.

### ISSUE THREAD

**Issue by Mostelin** [christofmuc/KnobKraft-orm#224]
The Duplicate Names filter now:
1. groups like-named patches together, but 'incompletely'.
2. displays patches in curious non-alphabetical order.

NB: Solving 2 might largely solve 1.

Example:
When I filter by Duplicate Names, HARP first occurs 3 times, then other patches (JUMP, OBOE...) are listed.
![image](https://user-images.githubusercontent.com/95011279/219240763-48fd80b1-97f7-4027-b8f6-11d5fb757307.png)

When I further filter by text matching, the display shows there are in fact 7 'duplicate name' patches called HARP:
![image](https://user-images.githubusercontent.com/95011279/219248200-9a6428ea-5329-4253-a28d-b7c3cc1d0806.png)

NB: The log suggests there are no hidden characters in the names of these 7:
12:39:01: info Sending patch HARP to Ensoniq ESQ-1
12:39:05: info Sending patch HARP to Ensoniq ESQ-1
12:39:08: info Sending patch HARP to Ensoniq ESQ-1
12:39:12: info Sending patch HARP to Ensoniq ESQ-1
12:39:13: info Sending patch HARP to Ensoniq ESQ-1
12:39:18: info Sending patch HARP to Ensoniq ESQ-1
12:39:20: info Sending patch HARP to Ensoniq ESQ-1
However, I have found that there **are** hidden characters. The group of three shown in the first image above are "HARP " (1 trailing space), and there are four "HARP  " (2 trailing spaces).

To complicate things further, I know that musicians sometimes added **leading** spaces to centre short patch names in the synth display.

I realise that 'duplicate names' should mean exactly that, so I don't think it would be wise to trim names (even if offered as an option, since that would further clutter the UI). I think an alphabetical sort would be the best approach. It would have the added benefit of putting all patch names with leading spaces at the top of the list, thereby alerting the user that there could be some less strict form of duplication. The only catch I see here is a case where there are just two patches in the form " XXXX" and "XXXX". Since neither on its own would make the list, sorting the list would be ineffective.

**Comment by christofmuc** [comment]
That sounds we just should never trim and display Patch Names where possible within single quotes, so you can see what is going on with whitespace?

**Comment by christofmuc** [comment]
Can you test this again with the 2.0.2? I believe that the duplicate filter and sorting works, as the database cannot trim. I removed trimming whitespace from the display, though. Problem is the property editor will still not allow you to enter leading whitespac,e but I believe we have no consistency problem in the duplicate name function.

**Comment by Mostelin** [comment]
Cannot install 2.0.2. See details in issue #229.

**Comment by Mostelin** [comment]
I think this is indeed working correctly. Now that I can see in the log exactly how patch names are padded, I can see that they are correctly ordered in the main display, with leading-space names listed first. In my setup, there are only 10 such cases:
3 x ' HARP '
2 x ' JUMP '
2 x ' OBOE '
3 x ' SAX  '

The listing is consistently alphanumeric, which I should have spotted. Sorry about that.

**Comment by christofmuc** [comment]
@Mostelin No problem, happy it works! Closing this now. Performance should be good again as well!
