### ISSUE TITLE
2.0.1 current focus is not highlighted in bank

### ISSUE THREAD

**Issue by bboc** [christofmuc/KnobKraft-orm#228]
![image](https://user-images.githubusercontent.com/520442/219504103-d8144680-1614-466b-8a8d-07e12e8d8521.png)

I mean, it is, but ever so slightly. In the grid, the highlight is much more obvious. Should be the same color in the bank panel.

**Comment by christofmuc** [comment]
Hm, I am unsure about this one, because the patch could be in the bank multiple times (e.g. if you make yourself an init patch and then drag that into a new bank, the whole bank is filled). Should all light up then? Maybe.

**Comment by christofmuc** [comment]
So that being said, this actually wasn't even meant to be the case, so I'll flag this an enhancement rather than a bug,

**Comment by bboc** [comment]
You can see U1 P13 is slightly highlighted in the bank, and that is just as I expect it, because I clicked on a patch in a bank panel. But it should be clearly visible. That's all there is 

The case you are referring to is probably about something different: what should happen when the user clicks on a patch in the library, and the same patch is used multiple times in the bank. I'd handle this the same as the favorites, all occurrences should be highlighted, but that should look different than the highlight when somebody directly selects a patch.

Thinking about this I may have found a way to handle program changes and edit buffer dumps consistently without a switch. Add two clickable areas, one for the program number, which sends a program change, and one for the patch name, which sends the edit buffer. Now the user can choose what they want in each case. That would work both in the bank panel and in the library, but in the bank panel I guess it's better to split the button horizontally between patch number and patch name.

**Comment by christofmuc** [comment]
Ah, right, the focus colour is off and hardly visible. That's indeed a bug!

**Comment by christofmuc** [comment]
So I made a fix that all patch buttons highlight when they have the same patch (md5 sum) as the current patch, which is the one loaded into the currentpatch panel. This seems to work nicely for the bank as well as for the second window.

**Comment by christofmuc** [comment]
Fixed in 2.1.0
