### ISSUE TITLE
Bank numbers shown even if not selected because of synchronization with Bank List

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#229]
**New problem**: the first 13 patches are sometimes shown with numbers repeated bottom left, even when 'Name' selected in display combo box (see attached screen grab).

To recreate, select the bank entry under 'By Import', then reselect the bank entry under 'In Synth'.
To reset, select another option in display combo box, then reselect 'Name'.

[Main log 2.txt](https://github.com/christofmuc/KnobKraft-orm/files/10750690/Main.log.2.txt)
[MIDI log 2.txt](https://github.com/christofmuc/KnobKraft-orm/files/10750691/MIDI.log.2.txt)
![Patch number display bug](https://user-images.githubusercontent.com/95011279/219225562-fb6d35c1-b0a8-4b7d-bfc0-ffdaab6ecbc8.PNG)

_Originally posted by @Mostelin in https://github.com/christofmuc/KnobKraft-orm/issues/217#issuecomment-1432277940_

**Comment by christofmuc** [comment]
@Mostelin Can you check if this is gone with the 2.0.2? I had a problem with the subtitle of the button, maybe this is now fixed as well?

**Comment by Mostelin** [comment]
I tried to download and install 2.0.2. After download, I got the error message 'The update is improperly signed' and could not install. The log reported as follows (I tried twice): 
```
10:29:29: error Error encountered in WinSparkle
10:31:38: error Error encountered in WinSparkle
```

**Comment by Andy2No** [comment]
> I tried to download and install 2.0.2. After download, I got the error message 'The update is improperly signed' and could not install. 

It seems like this should be a separate issue, on its own.  FWIW, It installs okay in Win 7.  I downloaded the .exe and installed it on top of V1.17, rather than asking Orm to update itself.

**Comment by Mostelin** [comment]
@Andy2No - you're right, of course: this is a separate issue. I'll leave it to Christof to clean up. Thanks for the tip about downloading.

And so, meanwhile, back to business - both problems appear to be fixed. I cannot recreate the odd display of 13 indices, and the in-synth patch names are all correct.

**Comment by christofmuc** [comment]
@Mostelin @Andy2No Thank you, yes, I somehow got distracted yesterday and forgot to include the code signature for the 2.0.2 in the appcast. Fixed this now, and make a ticket to finally automate this process fully (it is already much better than it was...)

Closing this as the bug is fixed (phew).
