### ISSUE TITLE
2.0.2 New Database shows favorites defined with previous database

### ISSUE THREAD

**Issue by bboc** [christofmuc/KnobKraft-orm#237]
When I create a new database (e.g. for testing an adaptation), and then Import a bank, the favorites I have defined with the previous database are marked with a heart icon. Is this intentional?

**Comment by christofmuc** [comment]
Lol, no, that's yet another bug of duplicate data. The problems started when the synth bank's button should synchronize with the grid button for favorite and tags. and it went downhill from there. I need to think about that fix so I don't make things worse...

This can be fixed quite easily, but the code is really not good in that corner of the system. 

Thanks for reporting btw, keep it coming ;-9

**Comment by christofmuc** [comment]
This should be fixed with today's 2.0.3 release.
