### ISSUE TITLE
Testing adaptations

### ISSUE THREAD

**Issue by bboc** [christofmuc/KnobKraft-orm#238]
Testing an adaptation requires some insight how KnobKraft works. Some of that might be learned from the Programing Guide, but it's much more straightforward to have a simple list of test steps you can work through from top to bottom to verify that everything is working as intended.

I have started writing a [collection of simple test cases](https://github.com/christofmuc/KnobKraft-orm/wiki/How-to-test-an-adaptation) to test the adaptations I'm working on in the wiki. However I soon found that I don't understand enough about how KnobCraft designed, so I can't write tests for some parts of the API.

I listed all functions I can't test at the bottom. Specifically I can't write test for renaming a patch, and for all the Edit Buffer functions.

**Comment by christofmuc** [comment]
Very true, it is on the list. 

Let me summarize quickly what I do to test:

I can run all my test for all adaptations by running

python -m pytest adaptions

The tests have basically two different mechanism that I use. The simpler one is to put a test_synthname.py file into the directory to implement synth specific tests. Look at test_AndromedaA6.py for an example on how this works. I think this is straightforward, and putting the tests into a file starting with test_ will make sure they are run in the CI.

The more advanced version is the general tests implemented in test_adaptation.py. This is a dynamic loader that will actually load in turn all modules, check if they have implemented a function called test_data(), and if it finds that will try to run as many tests as possible from the test_adaptation.py file.

The test_data() method is currently not documented, you can find an example usage in Roland_JV80.py, or Matrix1000.py, and by revisiting the code in the test_adaptations.py.

This is in the making, which is why I haven't documented it yet. The idea is that there is a set of generic tests that each adaptation needs to pass, given it can provide data to test against, and parameters to understand which tests make sense and which not.

**Comment by bboc** [comment]
Even better, I'll check that out and write some tests then. For keeping test data in strings, you might want to take a loot a triple-quoted strings and the function textwrap.dedent(). This saves you the backslashes, and still llows for nice indentation

**Comment by bboc** [comment]
For the upcoming documentation: you need to create a venv and install pytest and mdutil (dependency of test_implementation_status.py)

Running all tests:

`$ python -m pytest . --all`

Run one "new style" test

`$ python -m pytest test_adaptations.py  --adaptation Matrix1000.py`

Run all "new style" tests:

`python -m pytest test_adaptations.py  --all`

This shows  a couple of warnings that should be addressed, these may be related to the fact that the function that returns the test data is called `test_data()`, because [pytest would identify those functions as tests](https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#test-discovery). 

Maybe there's a simple way to invoke these tests from the module itself, so that pytest can pick up those tests along with any additional tests that might be defined in an adaptatation? Currently you can't do that with one command.

I'm currently figuring out how to prepare the test data, what's the difference between  `detection_reply` and `device_detect_call` / `device_detect_reply`?

**Comment by bboc** [comment]
Just an observation: it's weird that the API works on sysex messages as lists of integers (bytes), but the test data is expected as strings.

**Comment by bboc** [comment]
in test_rename() (line 97/98) there's a bug assertion:


```
 new_name = adaptation.nameFromDump(with_new_name)
assert new_name.strip() == new_name.strip()
```

needs to be replaced with 
```
assert new_name.strip() == adaptation.nameFromDump(with_new_name)
```

**Comment by bboc** [comment]
Ok, now I have a couple of tests passing, but two are still failing (fingerprinting and convertToEditBuffer). Need to figure out what's the problem here, because the adaptation appears to be working with the synth, and it did detect duplicates. 

the problem with fingerprinting here is that test code assumes that the Modor NF-1m would send a program dump with program number and bank number to the Orm, but in fact the response for single program dump and edit buffer dump is exactly the same sysex message (an edit buffer dump without bank or patch number), only the device itself can read the program dump. So that test code throws an error, because the fingerprinting code does not expect that kind of message. 

Have to check what's the other problem, probably tomorrow or the day after.

**Comment by bboc** [comment]
I dug around a bit more in the test_adaptations.py to figure out what is wrong, and since you said this is a work in progress I'll offer some suggestions. I think the code would benefit from a more declarative style, where you declare what functions and test data you expect to be present for a test, like so:


```
@skip_targets_without_test_data()
@skip_targets_without("nameFromDump")
@skip_targets_without("renamePatch")
def test_rename(adaptation, test_data: AdaptationTestData):
    ...
```

I implemented this with decorators, and it works fine for the "normal" adaptations, however I'm still having some trouble getting this to work with the generic adaptations, because these are implemented as objects that are "installed" into the module at runtime. will play around with that some more tonight. I actually like the idea of adaptations as objects, that would make it much easier to share code between them, e.g. for providing default implementations. 

Since the scenarios are somewhat complex (some functions being optional), I also think the tests might benefit from some more documentation, especially `test_convert_to_edit_buffer()`. 

What's also slighlty inconvenient is that the verbose output of pytest is ordered by test function, and not by module, which makes it hard to see what is actually tested for one module.

**Comment by bboc** [comment]
@christofmuc So, I finally found some time today and got this declarative thing to work, fixed a little bug in the test code, then added tests to the updated Toraiz AS-1 adaptation.

I found two things that I think need some more work:

1. some test may test nothing at all, but still pass. That affects 
    - test_fingerprinting() 
    - test_convert_to_program_dump()
    - test_is_program_dump() (I already fixed that and added a separate tests for test_is_edit_buffer_dump()
2. test_convert_to_program_dump() is simply too complex, the code in this test has too many conditionals, and I found at least one but that is a result of that, a code path that obviously has not been used, or at least not in an implementation where that would make a difference. This test currently fails for both of my adaptations, although they appear to work fine in the Orm. 

Currently, you get the same result (test is passing) when you implement one conversion function (and nothing else) and one message, or if you implement two different test messages, and both conversion functions, both testing functions and nameFromDump and numberFromDump. So that doesn't help much in finding out what's working and what isn't. 

I can see a few ways around this: 

 - separating the test into two tests (one for each conversion), which each relies on both test functions. The reverse conversion could still be used if present, but that would simplify the code quite a bit
 - providing the actual expected result of the conversion with the test data - that would simplifiy the test code even more
 - skipping the test if no appropriate test data is found, e.g. convert to program dump requires an edit buffer dump as input.


I'm curious what you think about that, especially how that would affect the tests for the other adaptations.

**Comment by bboc** [comment]
@christofmuc ok, now I tested splitting test_convert_to_edit_buffer() into two separate tests, and in the process I found a couple of things that I think were not working properly and documented them in the test code. 

You can take a look here:

https://github.com/bboc/KnobKraft-orm/blob/bboc_adaptions/adaptions/test_adaptations.py

There are still some problems I have to work out, the main thing is that in the case of the Modor NF-1m the synth returns the same message when the Orm requests an edit buffer dump or a program dump. So I thought isEditBufferDump() and isSingleProgramDump() should both return True for that message, because otherwise when requesting a program from a memory location, the Orm would not recognize the dump as a valid answer. The programming guide explains that, the example here is the DW8000.

Implementing it that way leads to the Orm storing edit buffer dumps in the database. So far, so good.

Now I thought that convertToProgramDump() should take that edit buffer dump and convert it to a message that contains a memory location. Which is working fine, as far as I could test that manually.

Now the test code in test_adaptation.py appears to contradict that logic, because it looks to me it expects that after converting an edit buffer to a dump that contains a memory location, the result should return True when passed through isSingleProgamDump(). And so the test inevitably fails.

Can you help me out, what is it I'm missing here? 

Also I don't seem to understand exactly what  `number` and `target_no` is for in the test data, and why they are two different parameters, you'd have to set them to the same value always, right?

**Comment by christofmuc** [comment]
@bboc Wow, you got some great progress there! Sorry I didn't jump in, but I am pretty busy right now preparing for a longer absence, so I did not have time to deep dive with you right now here. I do read and understand, and agree with all you wrote, so I think you have a pretty good grip here. 

The adaptations as objects was already done by me with the generic sequential and roland modules, but they have a weird method to hook up functions in the module namespace calling into the object... all a bit of an emergent mess admittedly. I shy away from larger breaking changes so far, but maybe it is time.

And yes, the tests that are currently there are more of a stitch together of all individual tests that had been written for one module or the other, and obviously the configuration of the test is near as complex as the whole capability model again. I like your idea of using the decorators!

Not sure if I find time in the next days, else I'll be off for a month before I can start coming back to the project :-/

**Comment by bboc** [comment]
@christofmuc I won't be available in the next couple of days, so let's just re-visit that topic in a month. 

Maybe then we can find a design for the adaptations that allows for reuse of as much code as possible, while eliminating the need for boilerplate code. Maybe it's not even necessary to hook up the functions in the module namespace if the C++ app can interact with the objects directly. No idea how that would work, though. 

I also think we'd need to re-visit the capabilities model to address the topic of the third type of kind of dump, it might be similar to the problem with the bank dump capability and importing sysex files containing bank dumps. Overall, this might result in a simpler and cleaner API. 

For the test data, we might be able to define more specific test data sets, so that there is a clear expectation which test case uses which kind of test data, and the user can still provide several sets of test data for some / all test cases if they choose. Maybe looking at  the use cases (device detection, requesting/storing edit buffers or program data, converting database dumps, reading files with bank dumps or file dumps) can help with defining test data?

Anyways we'll talk more when you get back.

**Comment by christofmuc** [comment]
@bboc I'm back now and slowly starting to work on this again. Thinking about this there might be an opportunity to create a "version 2" Adaptation interface in Python that can work with objects/classes rather than modules. The original modules are good but run into problems as soon as you want to use inheritace like I do with the generic Sequential and Roland modules - jumping through hoops there. 

Generally, the C++ capabilities are maybe better designed with the Python code a simplified layer on top of them to make it easier (but less powerful) to write adaptations. In the beginning I thought we might want to implement complex synths in C++, but by now I think all synths should be in Python, it is so much easier than C++.

**Comment by bboc** [comment]
@christofmuc Hi, I agree that Python is much easier. Can you keep the python object alive between operations, that might make things more responsive? Maybe there could be a factory from which the ORM can obtain a list of adaptations, and request an instance of a specific adaptation, and also obtain a list of available capabilities? And we should keep in mind that maybe in the future the ORM wants to keep multiple instances of the same adaptation, so users can connect several identical devices.

**Comment by christofmuc** [comment]
@bboc Actually, the Python modules are kept alive, so you could store globals in that module. The reason I don't have objects was... I can't remember. I think because it felt more Pythonique to just have a few free functions of which you implement a subset and then the driver does all the rest. 

True though that currently you can have only one of each synth types. Main reason is that they are autodetected mostly, and autodetection with multiple devices is messy/won't work in most cases.

The main performance bottleneck right now is not that the Python object is not kept alive, but that fingerprints/md5s and names are not cached on the C++ side, leading to way too many roundtrips into the Python code.

I haven't profiled yet, but as you had noticed before the functions are called way more often than they need to be called.

**Comment by christofmuc** [comment]
With 2.0.4, the whole generic test suite has been retargeted and I have written the Adaptation Testing Guide. Thanks again for your contribution!
