### ISSUE TITLE
MS2000/Microkorg fix 

### ISSUE THREAD

**Issue by BM-01** [christofmuc/KnobKraft-orm#239]
Hey thanks for making such a cool app! 

I'm new to this so apologies if this isn't the correct approach, but the MS2000 adaptation didn't work with my microkorg. The issue appears to be that the hardware ID for the microkorg was incorrect. I fixed it by adding 0x11 to line 72 in the MS200 adaptation file. Maybe it's worth having a separate adaptation for the microkorg?

Thanks again!

**Comment by christofmuc** [comment]
Thanks, that's cool! If the models are completely compatible and the only problem was the detection, your fix is probably all it needs. Sometimes we need to store the ID detected and use it later when composing the edit buffers for the specific synth, then we'd add a global variable to the module. But it seems the microkorg accepts original dumps from the MS2000? 

I'll take your fix into the next release!

**Comment by BM-01** [comment]
Hey Christof thanks for the reply!

Yep microkorg can read ms2000 patches and vice-versa.

Can't wait for the ability to send banks to the synth! ;)

Thanks for creating this!

Brad

**Comment by christofmuc** [comment]
Released with 2.0.3 today.
