### ISSUE TITLE
How to deal with synths which have ROM patches in the same bank as RAM patches?

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#246]
The Waldorf Pulse (Plus) has 1 bank with a total of 99 patches. In that one bank the first 40 patches are RAM, the rest is ROM patches.
The adaptation guideline mentions "isROM" [bool], but only for whole banks.
How do I deal with this in an adaptation?

**Comment by christofmuc** [comment]
Sigh, they always come up with surprises... On the other hand, why would you need to download the ROM patches at all? Could you not just setup on bank of 40?
