### ISSUE TITLE
2.0.2 is labeled as latest but marked as "beta"

### ISSUE THREAD

**Issue by suschizu** [christofmuc/KnobKraft-orm#247]
hello - is version 2.0.2 still a beta release? because it's marked as latest (stable) release
1.6.1 was the one that was marked as "latest" before  - thanks!

**Comment by christofmuc** [comment]
@suschizu Yes, it is a bit less stable than the 1.6.1, but has quite a lot of new features. If you just want to give it a spin and try with your synth, start with the 1.6.1. The upgrade is painless, downgrade currently harder (but possible with a bit of help). Unless you absolutely want to have bank management, which is the main feature of 2.x, and still somewhat in testing right now!

**Comment by suschizu** [comment]
hey @christofmuc - thanks for the fast reply!
