### ISSUE TITLE
Prophet-5 Rev4 not working without id_list

### ISSUE THREAD

**Issue by jpursey** [christofmuc/KnobKraft-orm#248]
I needed to add:
            id_list=[0b00110010, 0b00110011]
to the adaptation, or it would actually work as the returned device inquiry returns 0b00110011 as the ID, but all subsequent sysex uses 0b00110010.

**Comment by christofmuc** [comment]
@jpursey Thank you! That's probably a Prophet-5 Desktop module, or is it a Prophet 10? I'll add it to the implementation for the next release!

**Comment by jpursey** [comment]
Yes, I have a Prophet-10 desktop, although the MIDI specification is the same for all 4 variants (5/10 or desktop/keyboard): https://davesmith.wpenginepowered.com/wp-content/uploads/2021/03/Prophet-5-MIDI-Implementation-1.4.pdf

It always returns 0b00110011 for the device ID with an inquiry, but will not respond to that in anything else. That seems like a bug, on Sequential's side... but that is how it works.

**Comment by christofmuc** [comment]
Yeah, they do the same for Prophet 12 SE and other devices. They like to be able to detect which submodel of a family of devices it is, but it doesn't make any difference for the patches. They should rather use family/model like other vendors do, but ok, this is why I added the id_list feature in the first place :-)

**Comment by christofmuc** [comment]
Fix released with 2.0.3 today
