### ISSUE TITLE
keep manual port and channel assignments, even when synths off

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#256]
when I have synths switched off while loading KK, those obviously don't get detected. But the (manual) assignments that I did for them, also get lost. 
Is there a way to keep them?

**Comment by christofmuc** [comment]
True, this is a nasty regression that happened when I tried to support USB devices better, which can appear and disappear during the runtime of the program. I should actually fix this bug as it gets on my nerves as well ;-)

**Comment by christofmuc** [comment]
@markusschloesser I tried to fix this problem with release 2.0.6. At least in my tests with my USB synths this worked nicely. I can even hot unplug and plug them back again. They are not always picked up (The OB-6 is slow), but that might be ticket #80. Please give it a try!

**Comment by markusschloesser** [comment]
confirmed working!
