### ISSUE TITLE
Renaming a patch creates and inserts a new patch instead, and produces an indexing error

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#260]
Working on my partial Behringer Pro 800 adaptation, I defined the renamePatch() function, and apparently got it working, AFAIK, but instead of renaming the chosen patch, the Orm generates a new patch with the new name, adding that to the database, leaving the older one intact.

It also generates this error, the first time I do a rename after importing the patches from a dump (of all non-blank patches):

**warning Found 6 patches with inconsistent MD5 - please run the Edit... Reindex Patches command for this synth**

After doing the re-index, I can try the rename again, which produces another new patch but without that error.

Is this a known problem?  Have people been implementing renamePatch() successfully?  I'm on the current release, which is v2.0.5.

Here's my rename function, which just tries to replace values in the dump message, then return it:

```
def renamePatch(message, new_name):
    if isSingleProgramDump(message) or isEditBufferDump(message):
        # I'm assuming the bytes containing the top bits, won't need changing
        # - they start as 0 in blank patch and they'll stay as 0 for 7 bit ascii characters
        
        pos= nameBaseIndex
        for c in range(0, 4):   # doesn't include the last value in range, in the loop
            if c < len(new_name):
                message[nameBaseIndex + c] = ord(new_name[c])
                pos+= 1
        if(pos == nameBaseIndex + 4):
            pos+= 1  # skip a byte after first 4 bytes of name in dump (top bits of next 7 bytes)
        for c in range(4, 11):
            if c < len(new_name):
                message[nameBaseIndex + c + 1] = ord(new_name[c])
                pos+= 1
        if(pos == nameBaseIndex + 12):
            pos+= 1  # skip another byte after 7 more bytes in dump
        for c in range(11, 16):
            if c < len(new_name):
                message[nameBaseIndex + c + 2] = ord(new_name[c])
                pos+= 1
        if(pos < len(message) - 2):
            message[pos] = 0  # terminate - there is always at least one zero byte before the end f7
                              # only the first 16 characters seem to count
        return message  # no checksum to recalculate
    raise Exception("Neither edit buffer nor program dump can't be converted")
    return 'invalid'
```

**Comment by Andy2No** [comment]
FWIW, I've now verified that the same thing happens with V1.17.1 - after a fresh import of patches from sysex files, renaming a patch inserts a new patch with the new name, leaving the old one intact, and causing the indexing error.

**Comment by christofmuc** [comment]
Hm, this would most likely be an inconsistency between the implementation of the calculateFingerprint() and the renamePatch() method. Did you hook up the tests to check if renaming does not change fingerprint?

**Comment by Andy2No** [comment]
I wasn't aware of the tests, and having read the Adaptation Guide a couple of times, I wasn't aware of a need to implement calculateFingerprint() to get renaming to work, so I hadn't.

Having done that, it's doing what I initially expected, renaming a patch instead of creating a new one with the new name... I still haven't looked for the tests, yet.

FWIW, I based calculateFingerprint on the example code given in the Adpatation Guide, but that gave an error until I added:

```
import hashlib
```
at the top.  I have some other notes on small changes to the Adaptation Guide to clarify things, but maybe this issue thread isn't the best place.  I think it does need advice that calculateFingerprint() will have to be implemented to get renaming to work.  I'd suggest putting that under the section for renamePatch().

**Comment by christofmuc** [comment]
Thank you for the feedback. I improved the Adaptation Programming Guide and added the import hashlib, and the hint to look at calculateFingerprint when implementing renamePatch.
