### ISSUE TITLE
current update, updates to 2.0.5-dev, then wants to update again - PC/Win10

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#261]
I currently always get a prompt to update to a newer version (2.0.5). When I click update, 2.0.5-dev gets installed, hence the next time I launch, I get the update prompt again. Probably a "build" thing?

**Comment by christofmuc** [comment]
Uh, yes, must be this -dev suffix that shouldn't be there. I'll make sure to get rid of it for next release. What happens when you click skip version?

**Comment by christofmuc** [comment]
Hm, this still happens with 2.0.6, because it is also called -dev. I need to do more debugging which submodule causes the -dev mark.

**Comment by christofmuc** [comment]
This worked now for me with 2.0.7, which also no longer has the wrong -dev suffix.
