### ISSUE TITLE
Broken link on the Wiki page - 404 - The master branch of KnobKraft-orm  does not contain the path   adaptions/Adaptation Programming Guide.md.

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#262]
Following the usual link from the Wiki tab ("The most important information on how to create your own synthesizer adaptation or how to enhance existing ones can be found in the [Adaptation programming guide](https://github.com/christofmuc/KnobKraft-orm/blob/master/adaptions/Adaptation%20Programming%20Guide.md)."), I now get this error:

404 - page not found
The master branch of KnobKraft-orm does not contain the path 

adaptions/Adaptation Programming Guide.md.

**Comment by Andy2No** [comment]
The link on the Wiki page should point to:

```
https://github.com/christofmuc/KnobKraft-orm/blob/master/adaptations/Adaptation%20Programming%20Guide.md
```

not to 

```
https://github.com/christofmuc/KnobKraft-orm/blob/master/adaptions/Adaptation%20Programming%20Guide.md
```

The mistake is that the link still uses adaptions, on the Wiki page, but it should say adaptations.

**Comment by christofmuc** [comment]
@Andy2No Thank you! Fixed the link on the wiki page. I finally wanted to get rid of that old spelling error!
