### ISSUE TITLE
Suggestion for Adaptations documentation

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#27]
I made a start on making a new adaptation, reading through the new adaptations manual.  I got to the part where it said to change the name function, but it didn't say whether it was okay to change the file name, and if Orm would recognize it if I did.

I tried renaming the python file, and that worked, but it seems like that should have been in the documentation.

Personally, I find it harder to follow a manual if it's raising questions for me that it doesn't answer, because I end up thinking about that instead of paying attention.

FWIW, Korg have quietly dropped all support for Windows 7, even though support for Windows 10 isn't working properly, for some of their synths.  So, there may be a greater need for Orm, and other non-official sysex librarians.

**Comment by christofmuc** [comment]
Thank you, very good point. I'll add to the documentation the Orm will load and try to create adaptations for all files with the extension .py in the specified adaptation directory.

Korg - that's a shame. Which models would be affected? I mostly deal with Vintage synths earlier than 2000, so I don't have a good overview over the Korg models probably right now supported by the Korg software, or their relative importance/commonness in the market.

**Comment by Andy2No** [comment]
You're welcome.

Korg dropping support for Win7 affects all of their synths that are currently in production, and any no longer in production that had a USB driver or a software librarian to manage patches and other features.

For example, I bought my Minilogue XD earlier this year, in May.  At the time, the downloads page for it identified versions of the USB driver, the software librarian and the system updater (for updating the firmware) which would work with Windows 7, 8.1 and 10.  Now, they only specify 8.1 and 10, and even though the same versions I downloaded can still be found, in their list of older versions, they no longer say which ones are suitable for Windows 7.

There's a recent chart of compatibility for Windows 8.1 and 10, for synths which are presumably still in production, or were supported until relatively recently.

[i]Here are the PC and Mac compatibility charts for KORG products.
*Please note that we have discontinued our support for any products not listed in these charts.[/i]

https://www.korg.com/us/support/os/

There is no column for Windows 7, and a lot of the entries  for different versions of Windows 10 just say "under examination" (that includes the Minilogue  and Minilogue XD), or "End Of Support" - that includes the M50, microStation, PS60 and X60, which are now only supported in Windows 8.1 (which very few people use, AFAIK).

So, at the moment, it's probably still possible to use them in Win 7, provided you know which older versions to download, but Korg aren't giving any clues.  Beyond that, people will have to treat them like vintage synths, relying on sysex over DIN MIDI, where that's possible.

**Comment by christofmuc** [comment]
Documentation addressed in 1.10.0
