### ISSUE TITLE
On macOS I get an error about 

### ISSUE THREAD

**Issue by fadersolo** [christofmuc/KnobKraft-orm#273]
I just downloaded the latest release and when I load it up on macOS (Ventura 13.6) I get an error telling me I don’t have python installed:
<img width="910" alt="image" src="https://github.com/christofmuc/KnobKraft-orm/assets/37732096/53f80e5d-5c06-4c02-a74b-f7d916d12ac4">

But I do have it installed:

```
% which python3
/opt/homebrew/bin/python3
```

**Comment by christofmuc** [comment]
Hi! Yes, sorry, it seems brew has again switched python install path, and I don't have proper logic for finding it. 

The current list of search paths is:

1. "/Library/Frameworks/Python.framework/Versions/3.10",   // Python Mac installer (python.org/downloads)		
2. "/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.10",    // Homebrew Intel: python3
3. "/opt/homebrew/opt/python3/Frameworks/Python.framework/Versions/3.10", // Homebrew Apple Silicon: python3
4. "/opt/local/Library/Frameworks/Python.framework/Versions/3.10" 
5. and then the content of the variable ORM_PYTHON.

The easiest way to get is working is probably to download and install 3.10 from python.org via the Mac Installer, or to set the variable to point to the one you aready got. Let me know if that works for you!

**Comment by fadersolo** [comment]
I see, what’s interesting is that I do have 3.10 installed, but since I also have 3.11 it looks like homebrew cleans up the directory you’re looking in to only have 3.11:

```
% ls -l /opt/homebrew/opt/python3/Frameworks/Python.framework/Versions/
3.11
Current -> 3.11
```

I just confirmed this by re-installing 3.10 and it’s still not showing up in `/opt/homebrew/opt/python3/Frameworks/Python.framework/Versions/`.

What I do have on my system is `/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/`.

Sorry for asking, but how do I set the variable ORM_PYTHON?

**Comment by christofmuc** [comment]
https://stackoverflow.com/questions/25385934/setting-environment-variables-via-launchd-conf-no-longer-works-in-os-x-yosemite

It seems environment variables are tricky for apps if you do not want to set them every time again, you could try one of the solutions in that thread. I think it is easiest to use the Python.org download, that's what most people do.

02.10.2023 19:36:13 fadersolo ***@***.***>:

**Comment by fadersolo** [comment]
Ok, thanks for your help

**Comment by christofmuc** [comment]
Updated Python, for the next release this will be 3.12 which is the default installed by homebrew again. Maybe I should add the macOS pkg file to the DMG created.
