### ISSUE TITLE
Problems with Options / Create New Adaption dialogs

### ISSUE THREAD

**Issue by mslinn** [christofmuc/KnobKraft-orm#275]
Selecting **Options** / **Create New Adaption** displays a dialog that is hard to read on Windows due to the light gray background color:
 
<img src="https://github.com/christofmuc/KnobKraft-orm/assets/485818/51f74a4d-bea5-4f05-b15f-7d53dde34a38" width=400>

The dialog that follows has a "%s" instead of a variable value

<img src="https://github.com/christofmuc/KnobKraft-orm/assets/485818/b535e577-6b7c-48af-b01c-52f3f8ab89bb" width=400>

**Comment by christofmuc** [comment]
Oh thanks, that's two bugs in one!
