### ISSUE TITLE
Upgrade from Python 3.8 to 3.12

### ISSUE THREAD

**Issue by mslinn** [christofmuc/KnobKraft-orm#282]
I noticed that on Windows, `%LOCALAPPDATA%\Programs\KnobKraftOrm\python38.zip` contains Python 3.8. That is a 4-year-old release. Python 3.10 sped up Python quite a bit. Perhaps it might be worth upgrading to Python 3.12.

**Comment by christofmuc** [comment]
This is true! It is always a trade off - we have users who are still on Windows 7, and for those Python 3.8 is the latest Python version that works :-( 

What we could do is to duplicate the build pipeline and build both versions, one for modern computers and one for Windows 7.

**Comment by markusschloesser** [comment]
If Microsoft hasn't supported it for 10 years or so and python does not support it anymore, question is why do you have to support it? 😉
Nobody should be running it anywhere any longer (security).
Maybe sounds weird but sometimes progress demands cutting off old stuff. Especially as windows (10/11) still has excellent backwards compatibility.
Maybe declare the current release 2.08 the last one for win7 and then move on?

**Comment by christofmuc** [comment]
I was just trying to be nice, we had long discussion in #141 about this. But yes, I agree the latest build should probably be on an up to date Python. I don't expect any performance difference, but it will be better to be on an up to date version anyway!

**Comment by christofmuc** [comment]
Actually, we'll be running into all kinds of bad situations when creating a second build - we have auto updates, and uses will be nudged to update to a version that will no longer work on their machine. 

Maybe we should provide a way for the Windows version to use an externally supplied Python, just like the Mac version does. So if the supplied Python doesn't work you can switch back to one that you have installed elsewhere on the computer?

**Comment by mslinn** [comment]
Emphasize future needs, not current needs, when making decisions for the future. Your decision will become increasingly correct as time passes.

**Comment by Andy2No** [comment]
I'm fine with just sticking with the final Win7 compatible version.  Hopefully any adaptation I write will still be useful to someone else.

FWIW, I do now have a machine with Win 10 on it, but it annoys the hell out of me, so I rarely use it for much.  Security is my concern, not Microsoft's.

**Comment by christofmuc** [comment]
Released with 2.3.0. No Windows 7 anymore, if you need a private build, I can make you one!
