### ISSUE TITLE
The "Export patches" Dialog Is Hard To See

### ISSUE THREAD

**Issue by mslinn** [christofmuc/KnobKraft-orm#283]
The dialog is all black and grey. It is easily missed in the image below.

![knobby](https://github.com/christofmuc/KnobKraft-orm/assets/485818/54808797-edf7-4562-bbb3-782414518239)

**Comment by Andy2No** [comment]
Yes, a border would help there.   It's a problem with Dark themes in some Linux versions I've looked at too - if you have a few windows open, they all merge together into one blob, because they haven't done anything to show where the edges are.

**Comment by mslinn** [comment]
A colored background would also help. KnobKraft uses them in other dialogs, why not this one too?

**Comment by christofmuc** [comment]
Agree, this is really suboptimal. Namely, the import from synth dialog has a bright background, many others have this dark background which makes them disappear over the large grid. I'll have to go through all of them and harmonize this somehow. I wonder why the JUCE theme does treat them differently, normally this is all pretty standarized!

I'll treat this as a bug!

**Comment by christofmuc** [comment]
I changed the color for the export dialog. There are a few more dialogs, but as I touched it yesterday it was easy to do!
