### ISSUE TITLE
Need a Logo

### ISSUE THREAD

**Issue by mslinn** [christofmuc/KnobKraft-orm#288]
KnobKraft-orm needs a logo. Unfortunately, that is not within my skill set, or I would offer one.

Perhaps something that is evocative of electronic knobs and patch cables? After all, the term "MIDI patch" arises from patch cables used in analog synths. Of course, with a name like KnobKraft, the logo must have at least one knobby-esque aspect.

Here is an ARP-2600, an old analog synth that [I used to own](https://www.mslinn.com/av_studio/700-midi.html), showing patch cables in use:

![arp_2600_patches](https://github.com/christofmuc/KnobKraft-orm/assets/485818/95620a80-1346-4062-9981-6c79be47f552)

**Comment by christofmuc** [comment]
Beautiful synth! Yes, we only have a logo that is the icon of the app, done by some friendly soul a few years back. It plays with Orm vs Ohm, and uses the Omega as the center of the single knob:

![icon_orm](https://github.com/christofmuc/KnobKraft-orm/assets/5006524/73bf9b4f-f089-42b7-bbb2-aa4bf55c1528)
