### ISSUE TITLE
callback error

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#290]
opened KK 2.1.0 (not for the first time) and was greeted with:
<img width="407" alt="image" src="https://github.com/christofmuc/KnobKraft-orm/assets/59286549/4d5a73c9-8e83-4688-a054-951b7ba7e6c7">
Have never seen that before.

BTW: the paste names from clipboard function when importing from files is fucking awesome!!! 🥰 (just bought the Kid Nepro patches for the MKS80)

**Comment by christofmuc** [comment]
Ha! That does not look like a KK error, it mentions Lua and we don't use that. Any other software that might have produced that?

Glad you like the paste function - I forgot about it, but it had been in the release for a while, I'd have to research how long it is there already. New is the function to copy a bank into the clipboard (not an import, but a bank).

**Comment by christofmuc** [comment]
I have to checkout he Kid Nepro patches myself! Do you have a Rev4 or Rev5? I need to repair my MIDI interface before that, however. Too many things...

**Comment by markusschloesser** [comment]
> Ha! That does not look like a KK error, it mentions Lua and we don't use that. Any other software that might have produced that?
> 
> Glad you like the paste function - I forgot about it, but it had been in the release for a while, I'd have to research how long it is there already. New is the function to copy a bank into the clipboard (not an import, but a bank).

Ah shit, you're correct, had the ctrlr panel for the mks70 running in the background, apologies! 😊

**Comment by markusschloesser** [comment]
> I have to checkout he Kid Nepro patches myself! Do you have a Rev4 or Rev5? I need to repair my MIDI interface before that, however. Too many things...

Rev5, when I got one a couple of years ago, I listened to all the available demos online and then decided to go for the Rev5. Love it a lot 😊
You?

**Comment by christofmuc** [comment]
Rev5 as well. Don't get to use it as much and now my Motu Midiexpress is dead. I hope hope it's only the battery but I didn't find time to pull it out of the rack yet and give it a go

**Comment by markusschloesser** [comment]
If you choose to get another midi interface, I can only recommend the iConnectivity ones. I have 2 mio10 and they are fantastic

**Comment by christofmuc** [comment]
Get what you say. I got the Motu used for 150€ some years ago which was a good deal, and so far it has worked mostly. The drivers are crap and bluescreen happy in conjunction with the machine going to sleep and never waking up again. The filtering in the Motu is horrible to setup, but works. And important, like the MKS80 echoing all MIDI notes and so forth... I'll put the iConnectivity on the shopping list. i think they are the last ones making these devices anyway...

**Comment by markusschloesser** [comment]
mio's drivers are good and the most important thing is that they are multi-client capable.
Also rtpmidi is cool, I have laptop over wifi with rtpmidi and run kk on it and can put it besides my synths, use touch screen to send preset to synth over wifi, very handy!
mio10: 2 usb to PC ports, network port in the back, 10 din in/out, 1 usb client port (but takes a hub), only 4 rtp sessions
mioXL: only one to PC port, inbuilt USB hub, network port on front panel (🙄), lots more rtp sessions, more expensive, newer

**Comment by christofmuc** [comment]
@markusschloesser Noted. My next interface is certainly not a MOTU anymore. Still hope to revive my existing one, they are expensive as well. Hopefully will get around to it on this weekend.
