### ISSUE TITLE
Save Sysex Bank from the patches that are in the the Synth Bank window.

### ISSUE THREAD

**Issue by planist79** [christofmuc/KnobKraft-orm#296]
Hello,

i would like to request another function for the DW-8000, or in general:

Save Sysex Bank from the patches that are in the the Synth Bank window.
Ot is this already possible and i have not found out how?..

Thank you,

Peter

**Comment by christofmuc** [comment]
Hi Peter,

this is already possible, but only in a non-straightforward way. 

The logic right now is - banks are only lists (special lists), and lists can be saved to sysex with the Patches... Export into sysex file function. The trick is to get a bank to be displayed as a user list. For this, you can just drag and drop the synth bank (or a user bank) into the user list section, and you will get a copy of that bank as a normal user list. If you select that list, the Export into sysex file... menu will operate on the 64 patches of that list and you can create an appropriate file.

For the DW8000 bank format, select Sysex format individual program dumps, file format one file with all messages. This would only work with the new adaptation obviously, as the previous code had only edit buffer dump capability and not program dump capability.

I should offer a quicker menu entry to save a bank to disk - the only reason I didn't do it is that synths which have only a bank format like the Kawai K3 need to be treated differently, and I hadn't started to work on that. 

It's pretty easy, just needs to get done.

**Comment by christofmuc** [comment]
So much for the theory. I tested this, and it does export but all programs have the number 0, because the DW-8000 has no real program dump format. So the hack above works for synths that have numberFromDump() implemented, but not for edit buffer only synths. Even for those, the order of the export is not the same as the order of the patches in the list.

I will add a separate Export List/Bank menu entry, and maybe a button as well in the bank window so it is easier to find.

**Comment by christofmuc** [comment]
I added this in 2.2.2, please give it a try and let me know!

**Comment by planist79** [comment]
Great!!

It works well for the DW-8000 Synth Banks i compiled with KK. 
Both, the menu entry and the "Export Bank"-button in the Synth Bank window work well.

Tested options:
1. Syx Buffer Dumps / Syx Patch Dumps 
3. Single Syx / All in one Syx

Thank you!
