### ISSUE TITLE
MKS-50 (aJUNO) patch renaming 

### ISSUE THREAD

**Issue by planist79** [christofmuc/KnobKraft-orm#297]
For the MKS-50 / aJUNO the adaption does not yet allow renaming of patches.
I imported all my collected patches. Unfortunately they are all given arbitrary names and tags. 

Is it possible to implement the renaming?

**Comment by christofmuc** [comment]
I can look into this! Glad the MKS-50 code still works, I don't have one anymore and that was done a long time ago. 

What do you mean with arbitrary name and tags? Valid name or invalid names and tags? Then it would be a bug, for which I'd need some sample data.

**Comment by planist79** [comment]
ok, I'll upload sysex banks for the aJUNO tomorrow. or do you mean my patch database which now has lots of aJuno patches with wrong names?
I will send you some example screenshots also.

**Comment by planist79** [comment]
Hello Kris,

Thank you for the new version 2.2.0!!!!

Here is a Factory Patch Bank as syx and a readme witht the patch names.  

[read me.txt](https://github.com/christofmuc/KnobKraft-orm/files/14015780/read.me.txt)
[MYTHICAL2.zip](https://github.com/christofmuc/KnobKraft-orm/files/14015782/MYTHICAL2.zip)

The syx includes the names which do not get imported. KnobKraft v 2.2 just creates arbitrary but unique names for these patches. (Note: In the "Ctrl" Panel for the aJUNO the same syx bank gets imported with names, so the name information should be included somehow in the syx, here is the link to the panel: https://ctrlr.org/juno-alpha/)

![aJUNO- Syx import in KK](https://github.com/christofmuc/KnobKraft-orm/assets/107300612/400c9c7a-275f-470f-94c4-98b56ec6a597)

**Comment by christofmuc** [comment]
This should be fixed with release 2.2.1

**Comment by planist79** [comment]
@christofmuc: You worked your magic with v 2.2.1

I thought i have to import all my syx-patches again in order to have their correct names shown/saved. But KK is showing all the correct names of the MKS50/aJUNO patches !!

KnobKraft breathes new life into my the 2 synths i never wanted to sell since i bought them in 2001 (Korg DW-8000 and Roland aJUNO-2)!
One major improvement was the BCR2000 to control them directly, another is you great KnobKraft software to finally get the patches organized and now even elegantly transfered to/from the synths!

Thank you so much!!

**Comment by christofmuc** [comment]
Thank you, glad you like it! It was a lot of work, even when I intended it in the beginning just for myself :-)
