### ISSUE TITLE
Ctrl+Click or Shift+Click to select more than one patch at a time. 

### ISSUE THREAD

**Issue by planist79** [christofmuc/KnobKraft-orm#299]
Feature Request: It would be very handy to Ctrl+Click or Shift+Click to select various patches in the central patch screen, e. g. to move them to the Synth bank on one go. Right now it is only one patch at a time.

**Comment by christofmuc** [comment]
Absolutely. This needs to be done, I had it already here: #203. Thanks for the suggestion, raises the prio of this!
