### ISSUE TITLE
Reface DX not importing patches (stuck at 0%)

### ISSUE THREAD

**Issue by Tonbonthemon** [christofmuc/KnobKraft-orm#302]
After downloading the Reface driver and Knobcraft, when I tried importing patches from the synth to my computer, it would initiate the process but stay at 0%. Here is the log after opening the app with the DX connected _and_ trying to initiate a transfer from the DX using MIDI -> Import Patches from Synth, and then cancelling once it was stuck at 0:

> 17:37:57: info Launching KnobKraft Orm
> 17:37:57: info Detected Yamaha Reface DX on channel 1 of device reface DX-1

So nothing about the transfer is reflected here.

I am using ver. 2.2.1 on Windows 10. In the "setup" tab for the connection, I have Reface DX checked on, and "Sent to Device" is set to reface DX, "Receive from Device" is set to reface DX, and Midi Channel is set to 1.

When I hit "Auto-Detect Synths," I get this message and still the patch import does not work:

> 17:48:17: info Found Yamaha Reface DX on channel 1 replying on device reface DX-1 when sending to reface DX-1 on channel 1

**Comment by christofmuc** [comment]
Confirmed this is a problem with the 2.2.0 build. I have a fix that I will push and make a new version!

**Comment by Tonbonthemon** [comment]
> Confirmed this is a problem with the 2.2.0 build. I have a fix that I will push and make a new version!

Thank you!

**Comment by christofmuc** [comment]
This should work now with the 2.2.2 - I still haven't gotten my reface DX out of storage, so please give it a try and let me know!

**Comment by Tonbonthemon** [comment]
Hi Cristof, sorry for the late reply. Unfortunately even after updating, it
does not seem to be working; I am getting the same result as before.

**Comment by christofmuc** [comment]
Ok, I have to setup my reface and test again! That's a bit weird. Can you maybe attach the MIDI log here so I can have a look?

**Comment by christofmuc** [comment]
I kicked off the build for the 2.2.3 which worked now tested with my reface DX. Hope I did not cause another regression, this is pretty complex special case handling by now.

**Comment by RadekPilich** [comment]
Doesn't work for me either, freezes after around 20% here is the log:

`17:51:21.310: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.321: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.322: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.323: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.325: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.325: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.326: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.327: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]
17:51:21.327: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.339: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.340: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.342: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.343: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.343: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.345: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.345: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]
17:51:21.346: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.358: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.359: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.360: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.361: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.362: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.363: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.363: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]
17:51:21.364: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.376: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.377: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.379: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.380: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.380: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.381: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.382: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]
17:51:21.382: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.394: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.395: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.396: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.398: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.399: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.400: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.400: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]
17:51:21.401: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.420: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.422: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.423: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.425: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.425: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.426: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.426: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]
17:51:21.427: Out reface DX Sysex [f0 43 20 7f 1c 05 0e 0f 00 f7]
17:51:21.447: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0e 0f 00 5e f7]
17:51:21.448: In  reface DX Sysex [f0 43 00 7f 1c 00 2a 05 30 00 00 42 61 6e 6a 6f 20 20 20 20 20 00 00 40 00 00 42 02 01 52 00 05 7f 7f 7f 7f 40 40 40 40 00 40 40 00 40 40 00 00 00 69 f7]
17:51:21.449: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 00 00 01 7f 55 42 51 7f 39 00 00 55 00 00 03 01 00 01 01 35 7f 40 00 00 03 00 3c 00 00 00 1c f7]
17:51:21.451: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 01 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 40 f7]
17:51:21.451: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 02 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3f f7]
17:51:21.452: In  reface DX Sysex [f0 43 00 7f 1c 00 20 05 31 03 00 01 7f 7f 7f 64 7f 7f 7f 00 00 00 00 00 03 00 01 01 00 64 00 00 00 01 00 40 00 00 00 3e f7]
17:51:21.453: In  reface DX Sysex [f0 43 00 7f 1c 00 04 05 0f 0f 00 5d f7]`

**Comment by RadekPilich** [comment]
It was somehow being mangled with Minilogue XD.
Import works after disconnecting XD.
However it imports only the active patch and the result looks like this:

![Image](https://github.com/user-attachments/assets/19763c69-a3ee-4058-9c55-129db34e89e7)

**Comment by RadekPilich** [comment]
Apologies, it works correctly on it's own.
