### ISSUE TITLE
pagination is not dynamic

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#310]
When a filter is applied (in this case untagged), kk first showed 3 pages of patches. 
Tagging patches reduces the amount of untagged patches, but the amount of pages doesn't reflect this. So even when there are less than 3 pages needed to show the amount of patches, still 1,2,3 are shown.
Desired behavior imho should be to dynamically reflect amount of pages.
Tested with v 2.2.2

**Comment by christofmuc** [comment]
Ok, sounds like a simple bug!

**Comment by christofmuc** [comment]
Released with 2.3.0
