### ISSUE TITLE
Reface DX not showing up in Active Support for synth

### ISSUE THREAD

**Issue by 4zzzzz** [christofmuc/KnobKraft-orm#311]
Hi there, new to Knobkraft and trying to get set up. However the Reface DX isn't showing up in active support list but it can recognise when I've plugged it in? Screenshot attached 
<img width="1636" alt="Screenshot 2024-02-26 at 16 21 57" src="https://github.com/christofmuc/KnobKraft-orm/assets/161349553/ea1708aa-9be6-4ff2-be1b-edb593827089">
For reference I've downloaded the latest dmg file Darwin

**Comment by 4zzzzz** [comment]
Hi Chris, thanks for getting back so quickly. I have downloaded the previous version and have connected the synth. However, I'm not getting the option to upload Sysex files (see screenshot attached) thanks for your help! 
![Uploading Screenshot 2024-02-27 at 21.23.46.png…]()

**Comment by 4zzzzz** [comment]
also there is a message that says 'The Yamaha Reface DX implementation does not support editing the global settings of the synth, sorry!'

**Comment by Andy2No** [comment]
@4zzzzz from the messages in the log window at the bottom, you still need to install Python, somewhere it can see it.

**Comment by 4zzzzz** [comment]
Hi Chris, unfortunately there is no files for 3.1 version of python (screenshots attached) is there any other solutions I can try?
<img width="273" alt="Screenshot 2024-02-28 at 11 42 02" src="https://github.com/christofmuc/KnobKraft-orm/assets/161349553/6b180f16-5033-4f61-b0aa-4b01d3fb86b4">
<img width="859" alt="Screenshot 2024-02-28 at 11 41 39" src="https://github.com/christofmuc/KnobKraft-orm/assets/161349553/0200783a-4630-492e-bbd7-84830ac42869">

**Comment by christofmuc** [comment]
Oh ok. Let me try to answer:

1. The upload sysex file is a new feature of the 2.2.1 release, so it is not present in the 2.1.0. The 2.1.0 seems to be capable of downloading from the synth but not uploading, while the 2.2.1 can upload, but not download. Sorry for that stupid bug, I wlll fix it at the next opportunity, hopefully on the weekend.
2. The 2.1.0 does not need Python for the reface DX, just for many other synths. 
3. The 2.2.x needs Python also for the reface DX. A version that is available for Mac is here: https://www.python.org/downloads/release/python-31011/, the Python 3.10.11 is still available as installer.
4. The refaceDX code can not edit the global settings, this is only implemented for a few synths I have that have complex globals like the Rev2 or the Oberheim Matrix 1000. So it is not an error but just saying that it is not available.

**Comment by 4zzzzz** [comment]
ah that's a shame.. will you keep me updated when the bug is fixed?

**Comment by christofmuc** [comment]
Will do! Was distracted by paining the walls of my home office, but hope to get back to this soon!

**Comment by 4zzzzz** [comment]
hey just seeing if there were any updates on this?

**Comment by christofmuc** [comment]
@4zzzzz Thanks for checking back! I kicked off the build for the 2.2.3 now, which I tested successfully with my own reface DX tonight. Note that you still need to fix your Python installation, as the new reface DX code needs the Python to be installed.

**Comment by christofmuc** [comment]
Should be solved by 2.2.3 release.
