### ISSUE TITLE
midikraft-sequential-rev2 build fails

### ISSUE THREAD

**Issue by bzeiss** [christofmuc/KnobKraft-orm#317]
I'm trying to build knotkraft on Fedora 39, latest version on "main". I have successfully built KnobKraft on this system multiple times. I am getting this:

[ 66%] Building CXX object synths/sequential-rev2/CMakeFiles/midikraft-sequential-rev2.dir/Rev2.cpp.o
In Datei, eingebunden von /home/bzeiss/develop/KnobKraft-orm/synths/sequential-rev2/Rev2.cpp:11:
/home/bzeiss/develop/KnobKraft-orm/synths/sequential-rev2/Rev2Patch.h:33:50: Fehler: »virtual std::vector<std::__cxx11::basic_string<char>, std::allocator<std::__cxx11::basic_string<char> > > midikraft::Rev2Patch::layerTitles() const« als »override« markiert, überschreibt aber nicht
   33 |                 virtual std::vector<std::string> layerTitles() const override;
      |                                                  ^~~~~~~~~~~
make[2]: *** [synths/sequential-rev2/CMakeFiles/midikraft-sequential-rev2.dir/build.make:94: synths/sequential-rev2/CMakeFiles/midikraft-sequential-rev2.dir/Rev2.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1139: synths/sequential-rev2/CMakeFiles/midikraft-sequential-rev2.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2

**Comment by bzeiss** [comment]
If I remove the "override" from layerTitles in Rev2Patch.h, it builds.

**Comment by bzeiss** [comment]
There are mo build errors though:

In Datei, eingebunden von /home/bzeiss/develop/KnobKraft-orm/adaptations/CreateNewAdaptationDialog.cpp:9:
/home/bzeiss/develop/KnobKraft-orm/adaptations/GenericAdaptation.h:63:73: Fehler: expected class-name before »,« token
   63 |                 public midikraft::BankDownloadMethodIndicationCapability,
      |                                                                         ^
/home/bzeiss/develop/KnobKraft-orm/adaptations/GenericAdaptation.h:85:36: Fehler: »BankDownloadMethod« in Namensbereich »midikraft« bezeichnet keinen Typ
   85 |                 virtual midikraft::BankDownloadMethod bankDownloadMethod() const override;
      |                                    ^~~~~~~~~~~~~~~~~~
/home/bzeiss/develop/KnobKraft-orm/adaptations/GenericAdaptation.h:50:65: Warnung: Attribut »visibility« wird ignoriert [-Wattributes]
   50 | #define DEFAULT_VISIBILITY __attribute__((visibility("default")))
      |                                                                 ^
/home/bzeiss/develop/KnobKraft-orm/adaptations/GenericAdaptation.h:189:52: Anmerkung: bei Substitution des Makros »DEFAULT_VISIBILITY«
  189 |                 pybind11::module adaptation_module DEFAULT_VISIBILITY;
      |                                                    ^~~~~~~~~~~~~~~~~~
/home/bzeiss/develop/KnobKraft-orm/adaptations/GenericAdaptation.h:56:15: Warnung: »knobkraft::GenericAdaptation« mit bedeutenderer Sichtbarkeit als der Typ seines Feldes »knobkraft::GenericAdaptation::adaptation_module« deklariert [-Wattributes]
   56 |         class GenericAdaptation : public midikraft::Synth, public midikraft::SimpleDiscoverableDevice,
      |               ^~~~~~~~~~~~~~~~~
make[2]: *** [adaptations/CMakeFiles/knobkraft-generic-adaptation.dir/build.make:76: adaptations/CMakeFiles/knobkraft-generic-adaptation.dir/CreateNewAdaptationDialog.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1200: adaptations/CMakeFiles/knobkraft-generic-adaptation.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2

**Comment by christofmuc** [comment]
Looking at this right now, I got the same error on my machine when I forget to do a git submodule update - the errors are caused by an outdated midikraft git submodule.

When you pull a new version of Knobkraft, don't forget to git submodule update after that!
