### ISSUE TITLE
[adaptations\YamahaRefaceDX.py] banks/patches incorrect?

### ISSUE THREAD

**Issue by milnak** [christofmuc/KnobKraft-orm#321]
```python
def numberOfBanks():
    return 1

def numberOfPatchesPerBank():
    return 32
```

The Reface DX has 4 banks, each with 8 patches per bank.  Shouldn't these values reflect that ?

**Comment by christofmuc** [comment]
True, but as it is very quick in retrieving all 32 patches, I thought it would be easier to handle if we just make one bank with 32 than 4 banks with 8 each. Given that it is such a small number, it probably doesn't make a big difference. 

Give it a try and change these numbers to 4 and 8 respectively, the software should work for you! Let me know!

**Comment by christofmuc** [comment]
Question answered, I think 1x32 works better and faster than 4x8?
