### ISSUE TITLE
Cannot import ESQ-1 database

### ISSUE THREAD

**Issue by Red-Hector** [christofmuc/KnobKraft-orm#322]
When I try to open the ESQ-1 database, it gives the following error:

![image](https://github.com/christofmuc/KnobKraft-orm/assets/156534622/8aa927e8-76c8-401c-9fe5-5ef99fad8345)

I'm on Windows 10.

It is the database that is linked in the wiki.
https://app.box.com/s/ha4v4lbh2wkchfpz4lif8wlv51kxx5u4

**Comment by christofmuc** [comment]
Confirmed, there is a bug in the migration code that will try to add the comment column even after the migration step from schema 8 to schema 9 has completely recreated the table and alreadz added the comment column.

Can you try to open this one: [Ensoniq-programs-schema13.zip](https://github.com/christofmuc/KnobKraft-orm/files/15226938/Ensoniq-programs-schema13.zip)

**Comment by Red-Hector** [comment]
Yes that works, and imports properly. Thank you.


________________________________

**Comment by Mostelin** [comment]
Does this mean I don't have to make any changes to the ESQ-1 database?

**Comment by christofmuc** [comment]
No, the next release will contain a bug fix that can import the old one alright, no need to change the DB!

**Comment by christofmuc** [comment]
This is now released with 2.3.1
