### ISSUE TITLE
Suggestion:  Add links to the repo and/or Wiki, in the About dialog box.

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#326]
(As of v2.2.3) It would be useful to have a link from the About dialog to the some or all of the github repo main page, Wiki, and Adaptation Programming Guide.

Some people might download the Orm via a link in a forum, for example, and have no clear idea where it comes from or where to look for documentation.  Even though I've used it for some time, I still have to use a link from an email, or use a shortcut I keep with the downloads.  Links within the program itself would be better, and the About box seems like the best place to put them.

**Comment by christofmuc** [comment]
I added it, but it is not clickable because the message box does only display simple text and no hyperlinks. To have it clickable, we need to put it somewhere else or redo the about box to be a real DialogBox with a dedicated layout.

**Comment by christofmuc** [comment]
Released with 2.3.1
