### ISSUE TITLE
test_adaptations.py not in release package

### ISSUE THREAD

**Issue by milnak** [christofmuc/KnobKraft-orm#327]
it's in the github repo, but not in the release package.  For someone writing their own adaptation, is it assumed that they should clone the repo?

**Comment by christofmuc** [comment]
Ah, that's an oversight. I will add it! Cloning the repo is helpful to see all files, but it should strictly not be necessary, though running the tests requires a bit of pytest knowledge I guess.

Marking this as a bug! Thank you!

**Comment by christofmuc** [comment]
2,3,1 should contain all files now, at least with the Windows installer.
