### ISSUE TITLE
Can't rename patches in V2.2.3

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#342]
I've made some progress with making a Reface CS adaptation from the CP one, however, I can't get the Orm to let me rename the patches imported with it (from the edit buffer).  This seems similar to issue #29

When I type in a new name and press Enter, nothing happens, other than the name in the edit box changing back to what it was before I typed a new one.

The patch can't have a name stored in it, so I just want to be able to put a name in the database.  The adaptation generates "names" which are just a number, and so far all the same number (from a hash value), which is fine if I can change them manually.  I can't.

Am I supposed to be defining a rename function or not?  I can't see anything about that in the Adaptation Programming Guide, i.e. when there's no way to store it in the patch.  I thought I'd read that I shouldn't need to define one, but I can't now find anything to that effect.  If I do need to define one, what should it do, and where does it say so?

**Comment by Andy2No** [comment]
I also tried saving the edit buffer patches as sysex files, deleting them all, importing the sysex files and then renaming, as suggested in #29 - that didn't work either.

**Comment by Andy2No** [comment]
The adaptation has nameFromDump(message) implemented.  Is that being called after I try to change the name, putting it back again, overriding what I said?

The Adaptation Programming Guide seems to imply that it's possible to  have names specified this way, named in the database but not in the patch, but unless I'm missing something, it doesn't explain how to get that to work.  So, if it's possible, that needs more explanation.

**Comment by christofmuc** [comment]
Hm, let me think - I would expect you implement nameFromDump() only when there is a name stored in the patch. If you do not define it, the Orm will only store the name in the database, because there is no name from the patch. 

Implementing nameFromDump declares the GenericStoredPatchNameCapability for the synth, which also has changeNameStoredInPatch - or "renamePatch" in Python. I guess to be consistent, you'd need to implement both. You could just fake the name data into the patch and remove it before sending it to the synth, but seems unnecessary as there is already a database field for the name outside of the patch. 

What you probably want is to implement the friendlyProgramName() function which generates a nicer name given the program number.

**Comment by milnak** [comment]
> I've made some progress with making a Reface CS adaptation from the CP one, however, I can't get the Orm to let me rename the patches imported with it (from the edit buffer). This seems similar to issue #29

Fyi, I've sent out a [PR for a rewrite of the CP adaptation](https://github.com/christofmuc/KnobKraft-orm/pull/346) that I wrote.  You might want to use that, as I sort of hacked things up when I wrote the CP.

**Comment by Andy2No** [comment]
@milnak I saw that and thought "Oh no!  Does this mean I'm supposed to start all over again when I basically had it already working?" :)  I'll give that some thought.  

What functional changes does it make?  It all seems fine to me as it is, apart from the naming problem, which it looks like you probably still have - have you tried renaming patches?

The renaming issue seems fundamental to how Knobkraft Orm works.  I've had some initial success at solving that by just removing nameFromDump() - I can now rename patches (using the details panel on the right) but I haven't fully explored the consequences yet.  I'll try the friendlyProgramName() instead... soon.  Though of course, there is only one patch memory so it basically just has an edit buffer.  I'm not even clear if it remembers that when it's turned off or just reads the controls when it powers up - I forgot to check.

The CS has 35 (I think) bytes of data for the patch so if I make a name from that, I'm inclined to pick the most important parts (arbitrarily - the most important to me, I guess) and represent them as a character, even though the name would look like gibberish.  Using all 35 would be a bit much, and some information will be lost by putting them into a printable range of characters.  Alternatively, I suppose they could just be called "unnamed".  Since the name is stored separately from the patch, there doesn't seem to be any need to try to make them unique.  I would expect most people would want to name them after they imported them from the synth.

**Comment by christofmuc** [comment]
Closing this ticket in favor of #360 , which outlines a solution. Clearly, the documentation needs updating as well!
