### ISSUE TITLE
[Request] Add sending sysex on MIDI Log page

### ISSUE THREAD

**Issue by milnak** [christofmuc/KnobKraft-orm#344]
I'm currently using [MIDI-OX](http://www.midiox.com/app.htm) to send arbitrary SysEx and look at the returned data.  KnobKraft could probably add this relatively simply, e.g. a text box on the MIDI Log page that has something like:

`F0  __ __ __ __ __ __ __F7 [Send SysEx]`

**Comment by christofmuc** [comment]
Nice idea! Yes, that would be trivial if we just send it to all MIDI outputs. A bit more work if the MIDI output is to be selected?

**Comment by milnak** [comment]
I only use a single device at once, but ideally it would be specific to a midi output.

**Comment by christofmuc** [comment]
An initial version is released with 2.4.3 - it always sends to all outputs now, and you have to type the f0 and f7, but else it should already work. Please give it a try one the 2.4.3 build is available!
