### ISSUE TITLE
How are MIDI devices populated on windows?

### ISSUE THREAD

**Issue by milnak** [christofmuc/KnobKraft-orm#347]
While doing adaptation testing, I'm seeing seemingly a bunch of MIDI devices that I can't figure out what they are.

![image](https://github.com/user-attachments/assets/b3208940-d0a8-4153-b22a-cca5aa61a80b)

Device Manager shows a single device - "YC Series".

Any ideas?

**Comment by markusschloesser** [comment]
have a look at the Windows "Device manager" and there under "sound, video and game controllers". It lists all midi devices found by windows. How these are enumerated is a different topic (and more complicated ;-) )

**Comment by markusschloesser** [comment]
I am sorry, I didn't read properly (sleep deprived because of baby).
Have you checked what device manager shows when you enable "show hidden devices" (or similar)?

**Comment by milnak** [comment]
oh, didn't check hidden devices. I'll see if this reproes again for me. If it doesn't, it might be due to what I suggest above.  A potential repro for you would be to modify two adaptations so that `channelIfValidDeviceResponse ` both return 0 unconditionally, enable both of those and do an auto scan.

**Comment by markusschloesser** [comment]
Btw this is how windows identifies usb midi devices https://devblogs.microsoft.com/windows-music-dev/the-importance-of-including-a-unique-iserialnumber-in-your-usb-midi-devices/

**Comment by christofmuc** [comment]
No further action required on this one I think.
