### ISSUE TITLE
'No Python Installation Found' error despite having several versions available, Intel MacOS BigSur

### ISSUE THREAD

**Issue by DrMechanica** [christofmuc/KnobKraft-orm#367]
Starting knobcraft V2.4.0 (as recommended for mac in notes from later versions) delivers a warning about not finding a matching Python version, then the log shows it was looking for Python 3.10, which I understood to be changed to 3.12 according to #316. Regardless I have 3.10, 3.12, and 3.13 installed and available under '/usr/local/opt' via homebrew. I'm not sure what's happening here and any help would be great. Thank you!

**Comment by christofmuc** [comment]
I recently understood that homebrew does not install universal binaries, and Knobkraft is still Rosetta/Intel code. The installers from python.org will give you universal binaries. And you’re right, I think it should state 3.12.I will start building Apple Silicon soon, there are just a few dependencies which I need to update!Am 19.11.2024 um 19:26 schrieb DrMechanica ***@***.***>:﻿
Starting knobcraft delivers a warning about not finding a matching Python version, then the log shows it was looking for Python 3.10, which I understood to be changed to 3.12 according to #316. Regardless I have 3.10, 3.12, and 3.13 installed and available under '/usr/local/opt' via homebrew. I'm not sure what's happening here and any help would be great. Thank you!

**Comment by christofmuc** [comment]
This should have worked with the Universal binary installer from python.org, closing the ticket unless you say it doesn't work?
