### ISSUE TITLE
UX: Sorting patches in the grid view is unclear, should offer options

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#39]
"Seems like ALL is listing patches Alphabetically but as several sections starting over."

From https://www.gearslutz.com/board/showpost.php?p=15175240&postcount=21

I need to think about logical ways to sort the patches - by import, by name, by tag, ...? Where to put the UI for that?

**Comment by christofmuc** [comment]
Just found out that I cannot sort multi-banks import properly, as there is no column bank, just program. But for some synths, the program does not contain the bank number, and then the sorting goes completely intermittent. I also don't have a timestamp, but that would probably not be good enough to get the right sorting anyway. Have to think about the program place handling.

**Comment by Andy2No** [comment]
I think it would be worth allowing sort by bank/patch number, where those fields exist.

For example, I can import a bank from the DeepMind, or from a bank dump, and I'm then looking at just those patches in Orm.  Each one has a patch number (and a bank number) in it, so sorting by patch number would work.   That would make it easier to find the corresponding patch on the synth, which is useful when trying to reorganise them, or look for an empty slot to save one to.

**Comment by christofmuc** [comment]
@Andy2No Totally valid. The Deepmind.py did not implemented the numberFromDump() function yet, so the importer can not extract the encoded bank number, but just tries to keep the sorting it got when downloading. Not sure how well that works, however. 

I found to my dismay that the bank/program number handling is the one thing that I need to clean up in the code completely also to start working on the full bank management feaure #9 .

**Comment by christofmuc** [comment]
That was easier than thought - [UI] Add a combo box allowing to select one of 4 sort orders: By import (the original), by name, by program no, or by bank no.

**Comment by christofmuc** [comment]
Released with 2.3.1
