### ISSUE TITLE
Allow to delete single or multiple patches instead of always all that match the current filter

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#40]
This is part of ticket #26.

More details there. 

We need a way to multi-select patches in the grid, and perform an operation on exactly those. E.g. delete, or export.

**Comment by markusschloesser** [comment]
Either a dedicated "select" button, or preferably long hold one button plus tapping additional ones (first long press basically enters select mode) .
I also really like to way Google photos has implemented this for consecutive select mode for both finger and mouse

**Comment by christofmuc** [comment]
@markusschloesser This is now possible by just dragging a patch onto the new trash can. Future versions most probably will get a multi-selection, so we can extend that to delete multiple patches as well.

**Comment by markusschloesser** [comment]
Great, thanks!
Deletion asks for confirmation and then shows successful deletion in the log, but the deleted patch is still present in the patch selection window (and can even be send again). Only after going somewhere else and coming back, the deleted preset is not visible any longer. 
==> maybe do a reload after deletion?

**Comment by markusschloesser** [comment]
also: could the "del" (Entf") key be utilized for that additionally? A lot faster then dragging to trash 
(which btw even works when dragging with finger on touchscreen 😀👍)

**Comment by christofmuc** [comment]
@markusschloesser Let me see...
> also: 2. could the "del" (Entf") key be utilized for that additionally? A lot faster then dragging to trash (which btw even works when dragging with finger on touchscreen 😀👍) 

Great that the touchscreen works, wasn't sure. Del key would make sense if there is a confirmation, else it might be a bad surprise. We have no shortcut keys yet, just the macro setup for functions triggered by the playing keyboard. I created #129 for a discussion on this.

> 3. Another minor UX thing: IMHO most users would think that the existence of a trash can (which looks like a recycle bin) would mean that one can undelete/recover (I am aware that the pop up clearly states otherwise), due to the fact that the same bin in Windows/OSX offers that. I don't have a better symbol suggestion for now, just wanted to raise that. 

Yes, I am aware of that. Which is why I call it a trash can and not a recycle bin ;-) The original design is to use the hide function instead of real delete - this has the big advantage of a) undo and b) things you reimport will not suddenly appear as fresh and new, but rather will not be imported at all because the hidden database entry still exists.

> 4. the option to not show the confirmation dialog when deleting would be great 

Would be easy, question is just how to get rid of id? Maybe Yes Cancel / Never show it again?

> 5. maybe (but with a big warning): offer the option to automatically delete all duplicates?

Can't imagine how that works, which of the duplicates should be kept and which one not? For me, all my own patches initially are called "Basic program", so deleting all of them is probably a bad idea. Did you think about hiding them instead of deleting? That could even be done with the playing keyboard macro, and you can also setup a key/chord to skip to the next patch. Much faster than dragging a thousand items somewhere?

**Comment by christofmuc** [comment]
@markusschloesser Thanks for spotting this! I created #130 for that bug.

**Comment by Andy2No** [comment]
> Another minor UX thing: IMHO most users would think that the existence of a trash can (which looks like a recycle bin) would mean that one can undelete/recover ... I don't have a better symbol suggestion for now, just wanted to raise that.

How about the Grim Reaper's scythe?  A quick Google image search on that provides some promising results.

My first thought was the Reaper himself, but REAPER has another connotation, in this context, plus it might look a bit too gothic.  Just a scythe on it's own is easier to draw as an icon too.

**Comment by christofmuc** [comment]
Closing old thread. I can live with the trash can, it has no recycle symbol printed on it so what's in there is gone.
