### ISSUE TITLE
messed up new adaptation for the Andromeda and now knobcraft won't start

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#41]
Tried to do an Alesis Andromeda A6 adaptation, failed :-)
1. knobcraft now crashes directly after launching, event viewer shows:
"
Faulting application name: KnobKraftOrm.exe, version: 0.0.0.0, time stamp: 0x5fde4975
Faulting module name: ucrtbase.dll, version: 10.0.19041.546, time stamp: 0x43cbc11d
Exception code: 0xc0000409
Fault offset: 0x000000000007287e
Faulting process id: 0x2a08
Faulting application start time: 0x01d6d7be4f85311b
Faulting application path: C:\Users\Markus\AppData\Local\Programs\KnobKraftOrm\KnobKraftOrm.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: bb80b332-04ca-48bc-be90-f49a71019471
Faulting package full name: 
Faulting package-relative application ID: 
"

2. already failed before, first I didn't understand if "def createDeviceDetectMessage(channel):" is for the request or the answer, after I figured out that it was for the request and subsequently put it "return [0xF0 0x7E 0x7F 0x06 0x01 0xF7]" it still failed to load the adaptation with an error in that specific line.
The manual for the A6 states; "The A6 responds to the Universal Device Inquiry message < F0 7E 7F 06 01 F7 >"

3. How do I treat the manufacturer ID if it is more than one? Manual says "00 00 0E" is for Alesis.
In Midi-OX the A6 responds to  F0 7E 7F 06 01 F7  with  F0 7E 7F 06 02 00 00 0E 1D 00 00 00 30 31 34 30 F7

**Comment by christofmuc** [comment]
Easiest way to prevent the crash is to move the broken python file away from the adaptations directory. Knobkraft loads all of them, and when one has a critical error I seem to be unforgiving. 

Maybe let me see the current file, and I can see if I can spot the problem?

**Comment by christofmuc** [comment]
On #2, it is missing the commas. In Python, a list of numbers needs commas between the individual bytes.

**Comment by markusschloesser** [comment]
[Alesis Andromeda.zip](https://github.com/christofmuc/KnobKraft-orm/files/5725677/Alesis.Andromeda.zip)

**Comment by markusschloesser** [comment]
> On #2, it is missing the commas. In Python, a list of numbers needs commas between the individual bytes.

ah shit, that was quick (and dumb on my side 😂)

**Comment by christofmuc** [comment]
This is a quick fix: 

def name():
    return "Alesis Andromeda"  # MS TEST


def createDeviceDetectMessage(channel):
    # This is a sysex generic device detect message
    return [0xF0, 0x7E, 0x7F, 0x06, 0x01, 0xF7]
    
    # 0xF0 0x7E 0x7F 0x06 0x02 0x00 0x00 0x0E 0x1D 0x00 0x00 0x00 0x30 0x31 0x34 0x30 0xF7 MS A6 reply after inquiry from MIDIOX


def deviceDetectWaitMilliseconds():
    return 200


def needsChannelSpecificDetection():
    return False


def channelIfValidDeviceResponse(message):
    if (len(message) > 9
            and message[0] == 0xf0  # Sysex
            and message[1] == 0x7e  # Non-realtime
            and message[3] == 0x06  # Device request
            and message[4] == 0x02  # Device request reply
            and message[5:8] == [0x00, 0x00, 0x0E]  # Alesis
            and message[8] == 0x1D  # Andromeda
            and message[9] == 0x00
            and message[10] == 0x00  # Family member 0
            and message[11] == 0x00):
        # Extract the current MIDI channel from index 2 of the message
        return message[2]
    return -1

Note how I compare a sublist

**Comment by christofmuc** [comment]
P.S. editing Python can be quite a bitch because of the many formatting rules. My recommendation is always to use a good Python aware editor. I prefer PyCharm Community (https://www.jetbrains.com/pycharm/download/#section=windows). When I opened your file in it, the errors were already glowing dark red in my face ;-)

**Comment by markusschloesser** [comment]
thanks, that fixed the crash! (you (and I) immediately see that I don't that much about code. Will continue and take it from here.
Tried with Notepad++ but even have pycharm installed (for Ableton user remote scripts), will check it out. Again, thanks! :-)

**Comment by christofmuc** [comment]
Enjoy!

**Comment by markusschloesser** [comment]
"and message[5:8]" shouldn't that be [5:7]?
Trying to understand

**Comment by christofmuc** [comment]
Intuitively, yes. In Python, no.

Feature: https://stackoverflow.com/questions/509211/understanding-slice-notation

For some reason they decided to make the interval left closed, right open, i.e. the last index is *not* part of the list. A common source for mistakes, but when you dig it it can be quite natural. Or so I tell myself.
