### ISSUE TITLE
Increasing the View Scale level makes the patch names smaller (1360x768 screen)

### ISSUE THREAD

**Issue by Andy2No** [christofmuc/KnobKraft-orm#42]
If I set View to Scale 100%, I can just about cope with the font size used for the menus, because I mostly know what they say, but I need to squint, or use an on-screen magnifier, to make out the patch names properly.  If I set View to Scale 125%, the font for the menus gets bigger, which is nice, but not essential, but the patch names shrink to being almost totally unreadable.

I'm using a 1360x768 LCD screen, and also system fonts set to 125%, but possibly that setting isn't used by Orm.

Here's a couple of screen shots, with the log at the bottom reduced to the minimum size, by dragging the top downwards.  The first is View Scale 100%, the second is 125%.  Your eyes are probably better than mine, so you may be able to read patch names at 100% fairly well, but I'm struggling with it.

100%
![Orm 1_9_0 1360x768 100pc](https://user-images.githubusercontent.com/8021302/102817798-5005a700-43c8-11eb-96d7-47f8fd64cbfc.gif)

125%
![Orm 1_9_0 1360x768 125pc](https://user-images.githubusercontent.com/8021302/102817814-598f0f00-43c8-11eb-874f-98fb1da52db6.gif)

Would it be possible to reassign some of the unused space for showing the patch names larger?  E.g. the gaps around the buttons, and the borders inside them?

**Comment by christofmuc** [comment]
Yes, at some point I need to do an overhaul for the layout. The quick solution would be to show less patches in the grid, currently it is fixed to 8x8, but I could detect that there is not enough height and switch to 8x4, keeping the patch button size. 

I am also thinking of a general layout change moving the current patch to the right to gain more height - my original design was targeting my Android tablet in Portrait mode, but now that it is used on Desktop and I still didn't get around to make the Android version, we could use the width of the screen better.

**Comment by Andy2No** [comment]
I think there's scope for reducing the border size of the buttons showing a patch name, though I can see you need a minimum distance between them for touch screens.   

Height always seems to be the main issue for me - software tends to assume 1024 lines or more, now.  It would be good to be able to reduce the log to one line - and also to have that remembered when I close Orm and reopen it again (which probably belongs in the issue about remembering the window size).  

It would be nice if the region of the screen between the menu bar and the patches could be shorter too - a lot of it is blank space, at the moment.  For example, perhaps the tabs for Library, Settings, Macros etc, could move up to fill space that isn't used by synth selectors, if there's room - putting them all on the same line.

Perhaps just a manual grid size selection (that gets remembered) would work well enough though.   8x4 is a good match to the Reface DX, or Yamaha TX7/DX7, for example, because it's the size of a bank.

**Comment by markusschloesser** [comment]
something responsive would be cool, would also take care of the landscape problem. Probably harder to implement at first but easier in the long run.
The responsive parts could be 
- a dynamic amount of buttons with regards to height and width 
- where the menues are
Also there's currently two rows which merge, the with "Library..." and the synth buttons.
Another thought: make the pact selection section scrollable (instead of paginated)
I also mention the responsive part because I use 4 different screens on different PCs (and sizes). Some touch some non-touch

**Comment by christofmuc** [comment]
Maybe before I get around to do a full responsive layout and also make sure the margins etc match DPI and font sizes (a hard problem with JUCE and cross platform), I can ease the problem with the wide but low screen with doing responsive layout only for the current patch display. I wanted to this anyway since I have some more ideas what I want to dispay about the currently selected patch, e.g. the hex info / individual parameter info if available for the current synth.

Here is a screenshot from the branch I am working on, what do you think?

![grafik](https://user-images.githubusercontent.com/5006524/103684179-72ccb980-4f8b-11eb-8afb-0574054cb8cf.png)

**Comment by Andy2No** [comment]
It looks good, but it's hard to judge how it would look on my size screen.  If I scale that so it roughly fits for height, the fonts are really too small to read comfortably.

I'd prefer fonts at least this big... github is covering the attachment button with a "helpful" tip again.  Brb.

**Comment by Andy2No** [comment]
![preferred font size min](https://user-images.githubusercontent.com/8021302/103686865-562e8280-4f87-11eb-9fc2-6b4ac65ec261.gif)


Selecting the number of rows of patches shown, manually, from a menu, would be fine, if that helps.

**Comment by christofmuc** [comment]
I have to find out how to scale the whole fonts in JUCE, because I don't specify any font sizes, it does everything on its own (only the main ZOOM function is there).

This is how it looks when I switch my screen to 1360x768 and set system fonts to 125%. Looks good to me, but I am looking at a 26" monitor ;-)

![grafik](https://user-images.githubusercontent.com/5006524/103708234-7888c600-4fb0-11eb-9280-b28780e1724b.png)

**Comment by Andy2No** [comment]
On my 22" monitor, with my less than perfect eyes, I'm struggling to make much out without squinting or using an on-screen magnifying glass.

**Comment by markusschloesser** [comment]
is knobkraft compiled with 
`target_compile_definitions(${PROJECT_NAME} PUBLIC JUCE_WIN_PER_MONITOR_DPI_AWARE=1)` ? 
Because then I would assume that on Windows the OS itself takes care of the scaling. Admittedly per monitor dpi scaling is a very complex and messy topic and even large companies still fail to implement that properly.
I am a pretty good example why the per monitor thing is important: My main pc has 3 screens (32" @4k, 24" @FHD, 19" @1280x1024), whereas my laptop, which I use when sitting in front of the synths to be able to quickly select and send patches via touch, is 13" with 3200x1800. All those have different Windows OS scalings ranging from 100% to 225% (laptop).

**Comment by Andy2No** [comment]
Would it be possible to make the log, and the two log related buttons, hidable? 

If so, that would free up some more vertical space, which could make quite a difference.

For example, on the View menu there could be an item to Show log, with a tick if it's selected.

**Comment by christofmuc** [comment]
@Andy2No Yes, that'll be possible. Hiding it by default is not a good idea, as first time users might too easily miss errors, but being able to hide it (and persist that) is possible. Also, I had made a version where the too log buttons were just hovering in the upper right corner of the log view over the text, so they wouldn't need the whole row. That's probably the fastest to release.

**Comment by Andy2No** [comment]
Thanks.  That's great.  It would be nice if the zoom level could persist too, so it's the same when I open Orm again, but I suppose someone could set it so small they couldn't read the menu to put it back :)

**Comment by Andy2No** [comment]
... I just tried it,  75% is the smallest, and I've been setting it to 100% each time I start it up, so that's not a problem.

So, yes, it would be nice if it remembered that too.

**Comment by christofmuc** [comment]
@Andy2No Hi Andy, I made the version 1.13.0 to adress these issues, would be interested in feedback! It persists zoom level, and the position of the splitters. Log size can be reduced down to about two lines, and the fonts on the PatchButtons don't shrink anymore to ridiculous size. I added also a horizontal slider below the patch grid to set the number of patches displayed from 8x8 to 7x7... down to 4x4, also persisted.

**Comment by christofmuc** [comment]
@Andy2No Beta release 1.13.0 for Windows is at https://github.com/christofmuc/KnobKraft-orm/releases/tag/1.13.0

**Comment by Andy2No** [comment]
Thanks :)  The fonts in patch names are now more readable, at 100% or 125%, and stay readable when I resize the side bars, other than getting shorter.   They get smaller if I choose a zoom level of 150% or larger, but I wouldn't really need to.   They're still fairly readable at 150%, but at 175% they're tiny, though the menus and filter buttons have got bigger.

It's good that it retains the zoom setting and the sizes of the log and side bars.

I can't currently use the new slider, or the left/right long buttons to page through the results, or do that by clicking one of the page numbers below them (I can't remember if that was supposed to work).  If I tick one of the patch type filters, e.g. pads, that works, though I still only get to see the first page of results (in this case, of three pages).

Less importantly, if I shrink the right side bar too much, the text that says "No import information" gets overlayed on top of the "Hide" button:


![side bar a 125pc 1_13_0](https://user-images.githubusercontent.com/8021302/120971901-156cac80-c765-11eb-9df5-6b48c2d25ddd.gif)


![side bar b 125pc 1_13_0](https://user-images.githubusercontent.com/8021302/120971937-1e5d7e00-c765-11eb-8b54-0e962e16f594.gif)


Also, depending on how I resize the side bars, I'm seeing "..," appear on the end of patch names that don't need it, since it's still showing the full patch name before the "...".  Possibly it's because it's considering trailing spaces as part of the name, and deciding it doesn't have room for them?   That's not important either though, it just seems like it might be unintended behaviour.

See "Vectoria KA", in the middle, near the bottom, and "The Pig KA", near top right.  As I made the right side bar a little bigger, they both had "..." added, but still show their full patch names.


![watch the KAs a 125pc 1_13_0](https://user-images.githubusercontent.com/8021302/120973673-25858b80-c767-11eb-971a-2fdfa9c33559.gif)


![watch the KAs b 125pc 1_13_0](https://user-images.githubusercontent.com/8021302/120973703-2b7b6c80-c767-11eb-9a7f-58d856274c14.gif)

**Comment by christofmuc** [comment]
> I can't currently use the new slider, or the left/right long buttons to page through the results, or do that by clicking one of the page numbers below them (I can't remember if that was supposed to work). If I tick one of the patch type filters, e.g. pads, that works, though I still only get to see the first page of results (in this case, of three pages).

@Andy2No Oh, you mean the mouse click is not registered? That could be, with invisible overlaps of areas. Which buttons don't accept clicks? The left/right and the page buttons plus the slider?

> Less importantly, if I shrink the right side bar too much, the text that says "No import information" gets overlayed on top of the "Hide" button:

Thanks, that can be fixed!
 
> Also, depending on how I resize the side bars, I'm seeing "..," appear on the end of patch names that don't need it, since it's still showing the full patch name before the "...". Possibly it's because it's considering trailing spaces as part of the name, and deciding it doesn't have room for them? That's not important either though, it just seems like it might be unintended behaviour.

Well observed, I think your suspicion with the trailing spaces might be correct. I will look at it and see if I can do a simple fix!

**Comment by Andy2No** [comment]
Yes, left/right, page buttons, slider, and also clicking the patch buttons doesn't seem to do anything, though I don't currently have the synth connnected.

Clicking any of the patch type buttons, or Fav/Hide on the right slider makes it exit immediately, though I can click the empty box above Fav/Hide, and it briefly changes colour, so that one seems okay.

I've also noticed the hover text for the database / import selection on the left persists, partly dependent on how fast I move the mouse, like this:


![persistent hover text 13_1_0](https://user-images.githubusercontent.com/8021302/121025234-dbb79800-c79c-11eb-8515-2ec69bce8ecb.gif)

**Comment by Andy2No** [comment]
Also, pressing the Save button, after altering a colour in Categories->Edit auto-categories, makes Orm exit immediately, but on starting it up again, it did actually work - the new colour has been set, before it crashed.

**Comment by christofmuc** [comment]
@Andy2No Thank you! I made an update version 1.13.1 which should address all issues except the sticky tool tip, which I couldn't reproduce: https://github.com/christofmuc/KnobKraft-orm/releases/tag/1.13.1

**Comment by Andy2No** [comment]
That's much better.  Thanks :)

The tool tip problem seems to have gone too.  I haven't managed to get it to do it, with this version.

**Comment by Andy2No** [comment]
I spoke too soon.  Yes, I can get the tool tip problem in 1.13.1 too.  It's not a major issue though.  I can also get rid of them by switching to another window and back again.

The steps to produce it seem to be:

- Start Orm.
- Resize the left side bar.
- Click on "By import" to expand the list.
- Wait for the tool tip to appear, without moving the mouse, then move it downwards along the list, causing a trail of them to appear, like before:


![1_13_1 tool tip persistence still there](https://user-images.githubusercontent.com/8021302/121231309-2cf08600-c888-11eb-8981-18b6a3280032.gif)

**Comment by christofmuc** [comment]
@Andy2No Hm, I still can't reproduce them, maybe it is again dependend on the resolution. I will turn them off for 1.13.2, however, I don't really like the look of them. I will rather look into possibilities to shorten the text displayed - the current text is straight from the database, but I could probably recalculate that to a more compact form. Thanks!

**Comment by Andy2No** [comment]
No problem.  I agree, there's no real need for tooltips.

Being able to keep the side bars as narrow as possible, but still fully useable would be good.  It would be nice if a few more of the category buttons were still visible, when I shrink the right one down, but I realise my 768 lines is an extreme case.   Some people might want to use it on older laptops, netbooks, and big tablets though, especially if they use it to play live.
