### ISSUE TITLE
Crash when "Only untagged" is checked and a category filter is selected

### ISSUE THREAD

**Issue by aFrankLion** [christofmuc/KnobKraft-orm#55]
**Issue**: If I have "Only Untagged" checked and select a category tag to filter my patches, the program immediately closes.

I realize that this combination of actions should not be performed intentionally, as it will always result in no patches being found. I am in the process of manually tagging many patches, and I occasionally click the colored patch category filter buttons instead of the grayscale tag application buttons while doing this.

I am using the program with a DSI Prophet Rev2.

**Comment by christofmuc** [comment]
Confirmed and fixed. My implementation now gives precedence to the "only untagged" filter, as long as this is set, the additional filters for specific categories have no impact (and won't crash the software)

**Comment by christofmuc** [comment]
Fixed in Hotfix release 1.10.3
