### ISSUE TITLE
Check for updates available, offer to update or at least take us to download page

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#56]
1. show version info in "about" screen (I know it's in the title, but imho it doesn't belong there)
2. have a button in "about" which checks for newer version
3. notify user at launch, if newer version detected with option to see changelog and download newer version
4. maybe auto-update?

**Comment by christofmuc** [comment]
Thank you! The version in the title helps when people post screenshots of bugs ;-)

I agree an update check would be useful, and opening a URL to this github site is also pretty easy. Downloading and running the installer is a bit more involved, especially cross-platform. I'll put this on the list!

**Comment by christofmuc** [comment]
Release 1.11.0: Added WinSparkle to the Windows version. This will be used for auto updates for future versions. 

Closing this for now.

For Mac, we could do the same thing, if requested.

**Comment by markusschloesser** [comment]
1. first run didn't ask for auto update consent. Second run then asked. 
2. Doing a manual "check for updates" seems to run but pop-up window closed so fast, I cannot see the result. Maybe a message with "Your version is up to date" with release number of installed and online version would help?
3. Also do we need a versioning for adaptations? Or maybe a hint, that an included adaptation is more current than the custom one?

**Comment by christofmuc** [comment]
> 
> 
>     1. first run didn't ask for auto update consent. Second run then asked.

Ok, that's as specified. The idea is to not distract on first experiene of software with this (WinSparkle is built like this).

>     2. Doing a manual "check for updates" seems to run but pop-up window closed so fast, I cannot see the result. Maybe a message with "Your version is up to date" with release number of installed and online version would help?

Bummer, used the wrong function. This one will immediately install when it finds one without asking for permission. Hopefully found the right one now - just don't know if the update from 1.11.0 to 1.11.1 will work. Might be that the application doesn't quit properly. I'll try it out (things like these are a bit hard to test upfront). 
 
>     3. Also do we need a versioning for adaptations? Or maybe a hint, that an included adaptation is more current than the custom one?

I like your thinking. Hm. There is no "more current", there is only different, as you might have improved the adaptation yourself, hence the "override" warning that you're not using the stock adaptation. I could suppress the warning if the local adaptation code is identical to the built-in code (would happen if you just break out and want to look at it). 

Mad idea: To do proper versioning we'd introduce git versioning of the adaptations on your local disk, so you could even push back/contribute. The installer could install a local git repo so changes to the adaptations can be tracked, and differences be displayed. But then, the user needs a grasp of three-way merges, and that's probably too much assumed. I'll keep this in mind should the number of adaptations and users working on them should explode.

**Comment by markusschloesser** [comment]
I got an update notification! :-) 👍
But there's a problem with formatting
![image](https://user-images.githubusercontent.com/59286549/105230346-7d7b7700-5b65-11eb-984d-00ab05d1cf2e.png)

**Comment by christofmuc** [comment]
That should be fixed now, pages are hosted on a URL where the content-type is specified as HTML

**Comment by markusschloesser** [comment]
Auto update hasn't been working for the last months (Windows)

**Comment by christofmuc** [comment]
@markusschloesser @andy2no Ah yes, this is just because I haven't automated the automated update on my end, and currently it is still extra work for me on release. I will try it again with the 1.14.0, it should still work. Then I need to implement the automation of the release on my end, effectively probably having me to migrate all the build code from Azure to github, but well...

**Comment by christofmuc** [comment]
@markusschloesser @Andy2No I went through the update process for the 1.14.0, and that worked on my machine. So the mechanism works, it is just some extra work during the release. I need to automate that in order not to lazy out.

**Comment by markusschloesser** [comment]
confirmed that the update worked, but:
1. after successfully updating automatically kk wasn't reopened automatically 
2. I though that the icon on desktop was removed, but in fact it's now just somewhere else (which means it probably WAS removed and then added again)
Both very minor things though

**Comment by christofmuc** [comment]
@markusschloesser Ok, the update and restart worked for me, no idea why it wouldn't. The moving of the icon is probably something I can't control as it is part of the InnoSetup tool.

As these are minor, I keep this closed and rather focus on automating the process so I cannot forget to do it!

**Comment by markusschloesser** [comment]
that's why I didn't reopen! :-)
