### ISSUE TITLE
Make a maxforlive (m4l) for KnobKraft

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#57]
As vsts are somewhat restricted in Ableton (and also possibly in other DAWs because of the way that most of them handle multi-client midi), I would love to see a m4l version(s) of knobkraft.
Could be a "per Synth" version, with this one could have a proper total recall in Live for external hardware.
Is that doable?

**Comment by christofmuc** [comment]
Good question, I know near nothing about M4L and not a lot about Ableton, as I'm more of a live player and jammer.

Looking at Cycling 74's webpage, they claim "Create custom applications by connecting objects together instead of writing lines of code" - that would prevent any reusage of existing functionality, and would turn me off. Is there really no file format/programming code that can describe a M4L device?

**Comment by markusschloesser** [comment]
i'm very much a noobie when it comes to max and m4l, only managed to modify a couple of devices without really understanding what I'm doing. But: I think, one can do a lot in M4l including including external stuff within a device. Also Max uses Juce for some things.
A couple of urls:
https://www.ableton.com/en/blog/programming-in-max-for-live/ (old but a good entry point) also https://help.ableton.com/hc/en-us/articles/360003276080-Max-for-Live-tutorials-and-learning-resources 
https://riemannkollektion.com/blogs/techno-producer-knowledge-hub/max-for-live-the-techno-producers-guide 
https://cycling74.com/sdk/max-sdk-8.0.3/html/index.html  MAX API 
https://www.muffwiggler.com/forum/viewtopic.php?t=228802

**Comment by christofmuc** [comment]
Thank you! That's much more than I found. Looks a bit like a rabbithole, though, with going back to a C API. 
 
I think I will first investigate the VST capabilities in terms of sysex to see where the limitations will be, before I embark on yet another platform. VSTs can be build nicely with JUCE, actually I think that was the main reason JUCE was created.

**Comment by christofmuc** [comment]
This is not a priority, let's first look at the VST version.

**Comment by markusschloesser** [comment]
I already guessed and it was only because of the non existent sysex support in ableton, which can be circumvented when using M4l.
If there's an easy way to to do vst and M4l, I would still appreciate it a lot. Would be open to incentivising that as well 😉

**Comment by christofmuc** [comment]
@markusschloesser I don't even have a M4L license, I think this is only part of the full blown Ableton?

**Comment by christofmuc** [comment]
Ok, this is pretty clear about it: https://help.ableton.com/hc/en-us/articles/360003148640-SysEx-support-in-Live-10

"Do I need Max for Live to use SysEx in Live 10?

Yes. Live 10 supports the flow of SysEx messages through suitable Max for Live devices only."

They have an offer currently, Live 10 Standard for 279€ plus 119€ for the Max for Live, or Live Suite for 479€.

I wonder how big the market is for M4L... only few Ableton users will have it, and there are many other DAWs... (https://www.marketexpertz.com/sample-enquiry-form/21621)

**Comment by markusschloesser** [comment]
> @markusschloesser I don't even have a M4L license, I think this is only part of the full blown Ableton?

Max/MSP is a language/dev environment on its own. Max is not small, used a lot at universities, quite a big community around it. Check out cycling74.com or the Lines forum https://llllllll.co/ .
M4L is an implementation of Max WITHIN Live. 
Lots of stuff out there for Max and (supposedly) easy to make an m4l device out of a max patch.

**Comment by markusschloesser** [comment]
So yeah, the vst IPC approach is a lot bigger

**Comment by christofmuc** [comment]
bigger?

**Comment by markusschloesser** [comment]
bigger market :-)

**Comment by christofmuc** [comment]
Haha. Ok. But good to know that there is a Max standalone product, I thought maybe Ableton hat bought Max but they only license it as M4L. Will keep that in mind.
