### ISSUE TITLE
knobkraft - electra one crash

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#60]
[74c74694-408a-4246-ae27-f9c56f6ebcdd.zip](https://github.com/christofmuc/KnobKraft-orm/files/5762886/74c74694-408a-4246-ae27-f9c56f6ebcdd.zip)
first "get from edit buffer" worked fine
second (more complex) crashed orm.

**Comment by christofmuc** [comment]
Hm, can't coax more info from the crash dmp than "unhandled C++ exception". 

I think the stackdump looks like this:
https://sentry.io/organizations/knobkraft/issues/1948338135/?project=5450515&query=is%3Aunresolved&statsPeriod=14d

But sadly the sentry upload did not work, and matching the dmp file to a pdb file is always tricky, that's what we have sentry for, normally.

Was this version 1.10.2 or 1.10.3?

Can you try again with the newly released 1.10.5? I have archived the debug files also outside of Sentry, so I should be able to use the crash dmp directly.

https://github.com/christofmuc/KnobKraft-orm/releases/tag/1.10.5

**Comment by markusschloesser** [comment]
just happened again with 1.10.5.
enabled electra, closed setup, clicked on Electra in top right, knobkraft closes.
Did you get the crash log this time?

**Comment by markusschloesser** [comment]
re- opened, clicked Electra, log shows:
22:45:12: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:45:12: Error calling nameFromDump: JSONDecodeError: Expecting ':' delimiter: line 1 column 6437 (char 6436)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:45:12: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:45:12: Error calling nameFromDump: JSONDecodeError: Expecting ':' delimiter: line 1 column 6437 (char 6436)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:45:12: Error calling nameFromDump: JSONDecodeError: Expecting ':' delimiter: line 1 column 10022 (char 10021)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:45:12: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:45:12: Error calling nameFromDump: JSONDecodeError: Expecting ':' delimiter: line 1 column 10022 (char 10021)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

**Comment by christofmuc** [comment]
Sadly no automatic crash dump. The error indicates that the data from the Electra is not valid JSON, maybe a bug on their side ;-)
You shoud be able to export the offending preset (or all of them) using the export button, and attach it here. Then I should be able to replicate the problem.

Or if those are public presets - I have access to the Electra Preset Store and could download it as well.

**Comment by markusschloesser** [comment]
So I imported a couple of patches from my Electra, they all seem to work, BUT not the MKS80 one I made. When I have that one selected at the Electra
1. I get 3 patches, 1 mks80, and 2 "invalid" ones
2. log file shows
3. 22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Skipping patch ROLAND MKS-80 v3 because it is a duplicate of ROLAND MKS-80 v3
22:49:09: Retrieved 3 new or changed patches from the synth, uploaded to database
22:49:09: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting value: line 1 column 44863 (char 44862)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting value: line 1 column 44863 (char 44862)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 9867 (char 9866)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting value: line 1 column 44863 (char 44862)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 9867 (char 9866)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting value: line 1 column 44863 (char 44862)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Adaptation: Error calling name: SystemError: <built-in method seek of _io.StringIO object at 0x000001A739056160> returned a result with an error set
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 9867 (char 9866)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Uncaught exception in renamePatch of Patch of GenericAdaptation
22:49:09: Error calling nameFromDump: JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 9867 (char 9866)

At:
  json\decoder.py(355): raw_decode
  json\decoder.py(337): decode
  json\__init__.py(357): loads
  <string>(65): nameFromDump

22:49:09: Adaptation: Error calling name: SystemError: PyEval_EvalFrameEx returned a result with an error set

The mks80 has special json in the preset, to make the "Tune Request" and "Patch Change" work before they implemented that in the web editor

**Comment by markusschloesser** [comment]
> Sadly no automatic crash dump. The error indicates that the data from the Electra is not valid JSON, maybe a bug on their side ;-)
> You shoud be able to export the offending preset (or all of them) using the export button, and attach it here. Then I should be able to replicate the problem.
> 
> Or if those are public presets - I have access to the Electra Preset Store and could download it as well.

yep, it's "my" mks80 v3 preset

**Comment by markusschloesser** [comment]
on the other hand, I now have successfully retrieved all presets from the Electra and can also send successfully 😊👍👍👍 (with the exception of the mks80 preset)

**Comment by christofmuc** [comment]
Can you get the MKS80 preset to me? You can export it from the Orm via the export button into a ZIP file. I tried the file from the Electra One App page and that works, but it seems different given the error message above.

**Comment by markusschloesser** [comment]
[knobcraftexport mks80 electra crashing patch.zip](https://github.com/christofmuc/KnobKraft-orm/files/5767998/knobcraftexport.mks80.electra.crashing.patch.zip)
attached

**Comment by christofmuc** [comment]
Very strange, that preset works for me and does not have a parse error. Anyway, I changed the code so the system is more tolerant should an extra comma or something turn the preset into invalid JSON. You will not be able to rename an invalid JSON preset, but everything else should work. 

Due for next release.

**Comment by christofmuc** [comment]
Better error handling for JSON parse errors added.

**Comment by markusschloesser** [comment]
ok, does not crash anymore 👍👍, but results in "Adaptation: Can only rename valid JSON, the preset may be corrupted" and the preset itself shows up as 
![image](https://user-images.githubusercontent.com/59286549/103836350-2071c280-5089-11eb-9dc6-97f2a404e378.png).
Also exported from knobkraft attached 
[knobcraftexport import elektra bank patch.zip](https://github.com/christofmuc/KnobKraft-orm/files/5778864/knobcraftexport.import.elektra.bank.patch.zip)

**Comment by christofmuc** [comment]
Lol, at least that looks corrupted! I can fix the name extraction in this case, but the real question is why would that preset work at all?

Somewhere in the middle of the file, there is a quotation mark missing, and that makes it invalid JSON. I wonder how the Elektra Code survives this:

![grafik](https://user-images.githubusercontent.com/5006524/103880783-e2e95580-50d9-11eb-9704-fc3a53ce095f.png)

**Comment by martinpavlas** [comment]
Hi, sorry for being slow in responding. I am currently in the bed with covid :)

I tried to replicate the issue but I think I am missing some bit. This is what I have done:

I took the file "knobcraftexport mks80 electra crashing patch.zip" and ran a JSON validator on it. It looks ok and Electra loads that preset fine.

Then I tried file "knobcraftexport import elektra bank patch.zip". JSON validation fails here indeed. There are a few bytes missing on the `"contr:1,` line it should be `"controlSetId":1`. As the double quote is missing, it renders the file invalid. When I tried to load this file to Electra I get an error message.

I will get knobcraft installed on my computer and will play around with it a bit.

**Comment by markusschloesser** [comment]
> Hi, sorry for being slow in responding. I am currently in the bed with covid :)
> 
> I tried to replicate the issue but I think I am missing some bit. This is what I have done:
> 
> I took the file "knobcraftexport mks80 electra crashing patch.zip" and ran a JSON validator on it. It looks ok and Electra loads that preset fine.
> 
> Then I tried file "knobcraftexport import elektra bank patch.zip". JSON validation fails here indeed. There are a few bytes missing on the `"contr:1,` line it should be `"controlSetId":1`. As the double quote is missing, it renders the file invalid. When I tried to load this file to Electra I get an error message.
> 
> I will get knobcraft installed on my computer and will play around with it a bit.

Holy shit! Get well soon! I hope it's not too bad?
re electra: did you see that when initially importing into knobkraft it import 3 patches (from edit buffer), the mks80 and two "invalid", maybe because of the missing quotation?
fyi: that's the (my) mks80v3 preset from the electra one page, where I only fixed patch selection and implemented tune request by hand in the json, so i might have fucked up something :)

**Comment by christofmuc** [comment]
@markusschloesser  Strangely, I downloaded you mks80v3 preset from the website, and that did not contain the bug from the preset in your Elektra. Maybe a different version?
