### ISSUE TITLE
Support for Quasimidi Cyber-6

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#61]
One of the devices wanted is the Quasimidi Cyber-6.

As this has a rather simple sysex structure, it lends itself to learning. Therefore here is an example on how I would implement this device reading two pages in the manual.
[QuasimidiCyber6.py.txt](https://github.com/christofmuc/KnobKraft-orm/files/5764509/QuasimidiCyber6.py.txt)

**Comment by christofmuc** [comment]
@markusschloesser Maybe have a look at the version I attached here and give it a try. I think the documentation is especially unclear about the size to be given on a dump request...

**Comment by markusschloesser** [comment]
the documentation is shit 😂
same problem as with the A6, doesn't get detected, manually fixing ports still doesn't work with getting programs

**Comment by christofmuc** [comment]
Do you have any other Librarian that works for the Cyber-6? What I do if the documentation is that bad I reverse engineer by looking at the communication other programs do. Or can you initiate a dump from the device into Midi Ox, so we can at least see an example MIDI file?

**Comment by christofmuc** [comment]
Closing this, as I think there is not enough information available on the Cyber-6

**Comment by markusschloesser** [comment]
Yeah, doesn't make sense to try to support it. Too rare, not enough documentation.
