### ISSUE TITLE
Prophet 12: Uncaught exception in renamePatch of Patch of GenericAdaptation

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#63]
I got a couple of those (20?) while launching 1.10.5 for the first time on my laptop

**Comment by christofmuc** [comment]
Ouch, does it say which synth?

**Comment by markusschloesser** [comment]
only had the Prophet 12 connected and selected at that time

**Comment by christofmuc** [comment]
Maybe if you can post me the full log on startup (if it still occurs), that would give me an idea.

**Comment by christofmuc** [comment]
Ok, confirmed, I could reproduce it. Weird C++/python binding problem, should be fixed with next release.
