### ISSUE TITLE
disabling all adaptations crashes knobkraft

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#64]
when I untick the last adaptation in settings, knobkraft crashes
[da48bea1-e4b5-42be-b813-6dd2e2730e87.zip](https://github.com/christofmuc/KnobKraft-orm/files/5773125/da48bea1-e4b5-42be-b813-6dd2e2730e87.zip)

**Comment by christofmuc** [comment]
@markusschloesser Thank you! That's an easy fix (was a regression from introducing the new Adaptation tab)!

**Comment by christofmuc** [comment]
Fixe by 1.10.6
