### ISSUE TITLE
Limit the amount of backups 

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#66]
my knobkraft folder has grown in size significantly, since the P12 db is 12mb and there are now 36 backups. Total size of the folder is now 362MB.
How about a max size for backups per db, or alternatively a max amount of backups per db file in settings? And auto-delete older ones?

**Comment by christofmuc** [comment]
@markusschloesser  It exists, you just haven't reached the hard coded limit of 500 MB yet :-)

The size limit could go into some preference dialog I just didn't have time to implement. Not sure how important that is right now.

**Comment by markusschloesser** [comment]
ah, there IS a size limit! 👍😁
What happens when reached? Deletion/overwriting based on age?
Maybe something for the FAQ? (which I would suggest having)

**Comment by christofmuc** [comment]
We could try to build the FAQ here in the github discussion forum?

I started this: #68
