### ISSUE TITLE
Librarian should accept bank dumps, patch dumps, edit buffer dumps from any device any time

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#69]
Many synths allow you to initiate dump directly from the device. There is no reason why the Orm should not be able to accept unrequested dumps and just store them in the database. 

Question would be how the UI should react to a dump received. Just a log message? A quck popup box?

Normally, it is not a good idea to keep doing other things while sysex dumps are running on the MIDI network, e.g. playing notes during a dump is not always without problems...

**Comment by markusschloesser** [comment]
Midi-OX does this with a dedicated "Receive manual dump" button, which is imho a good option and doesn't block things

**Comment by christofmuc** [comment]
@markusschloesser True, that's probably also easiest implemented :-)

**Comment by christofmuc** [comment]
Released with 1.11.0 - button "Receive manual dump"
