### ISSUE TITLE
Need synth-specific help text to be displayed, some of them need really arcane settings

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#70]
We could have a text box displaying synth-specific help text. Question would be where to put it. In the setup menu, there is not much space and I can't display the setup message for all synths selected. Best would be the Adaptation tab, but who looks there? It should probably be renamed to "Synth settings" or something where people are going to look

**Comment by markusschloesser** [comment]
would you do make that meta data for adaptations as part of those, or as separate entities?
pro for part of: everything contained in one file
pro for separate: everybody can write FAQs or info about synths

**Comment by christofmuc** [comment]
@markusschloesser Good point, we might need both... I have shied away from putting any web/online functions into the software so far, but maybe we could add a URL to a github Q&A about a specifc synth... Just opening a browser with more help text might be not too heavy weight. 

First I'd add something to the file.

**Comment by markusschloesser** [comment]
the URL approach is appealing. You could use the Wiki for that.
I don't mind when a sw pulls stuff from the internet when (in this case) enabling a module/adaptation, but that might involve things like webview etc. There are others who do mind, but hey it's your program! ;-)

**Comment by christofmuc** [comment]
Ok, I built both - you can provide a text with the adaptation that is displayed in the Adaptation view, and there is also a link into the Wiki with the adaptation synth's name as a page title. That's a bit experimental, I also added you as a collaborator so you for sure have Wiki editing rights, though I tried to make the Wiki public already.

Also, I added a Reload and a Reveal in Explorer Button for the Adaptation, with an automatic "break out" function in case you want to work on one of the bundled adaptations. Should make it more comfortable. 

I need to wrap up the next release, but the multi-data code is giving me a hard time, will probably need the weekend to finish that.

**Comment by markusschloesser** [comment]
I could write something for the Andromeda, what do you think makes more sense
a) in the adaptation? (then you need to check in what you sent me via forum)
b) in the wiki?
It will be interesting/challenging to keep implementations of kk and adaptations in sync with the description

**Comment by christofmuc** [comment]
@markusschloesser I think add it to the Wiki first. The information in the adaptation could be really short. here is a screenshot of the upcoming version - the link into the Wiki is calculated from the synth name, and clicking it will take you here into the github Wiki. If no page exists for that synth, you will be immediately able to create it:

![grafik](https://user-images.githubusercontent.com/5006524/104786065-4899a980-578c-11eb-8539-9ff24f0579ee.png)

**Comment by markusschloesser** [comment]
looks great!
what's "Data File load capability"? Because I have successfully imported hundreds of sysex files

**Comment by christofmuc** [comment]
@markusschloesser Ah, Data File Load is the name of the C++ class that is used for the multi-data type synths. That is a bit historic, with the idea that each database entry is a "DataFile" of a certain type. What it really is is more a "StreamDumpCapability", because you can use it to create database entries from multiple MIDI messages (like Yamaha, Roland), or to work with MIDI messages representing different data types (Tones, Voices, Performances...).

Naming is hard.

**Comment by christofmuc** [comment]
Release with 1.11.0
