### ISSUE TITLE
A bit more metadata for a patch would be nice

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#71]
"MS: that would be cool, also the new side panel you proposed, could/should show meta data. Meta data from import: date, which bank (or from which file/folder when sysex from computer), org prog number and name. But also user meta data: tags, comments, "used in song", etc?"

With the new side panel, we can display:

Patch name as edit box, so you can immediately change it there without opening a dialog box
Also for layered patches, show both layer names in edit boxes

Synth this patch is for
If encoded in the patch, bank and program number it came from.
Import information (also with nested information from bulk imports!). If file, probably with browse button (Reveal)
Fav/Hidden
Tags (Categories)
Comment field.
Star rating 1-5?

Contained in which program lists, once program lists are implemented
Contained in which synth banks, once bank management is implemented (special case of program lists)

Hexdump
Parameter list with values (when synth supports Parameter Info)
Delta to last patch the selected (for quick diffing)

Waveform when preview was recorded
Spectrogram when preview was recorded

**Comment by markusschloesser** [comment]
great! 
re star rating: imho redundant with fav/hidden
size of patch could be helpful (K5000 patches have different sizes, which decides how many are available in the k5000s)

**Comment by christofmuc** [comment]
From #77: Search should also search new meta data.

**Comment by christofmuc** [comment]
The 2.1.0 brings the searchable comment field, the list of known bank positions, and the hex dump. There is more ideas about metadata but by now the metadata side panel is an established feature and we can track the individual ideas in separate issues.

**Comment by RadekPilich** [comment]
Related to my comments in https://github.com/christofmuc/KnobKraft-orm/issues/379, I would like to see at least one additional field for author / source (soundpack). 

Yes, I could use comment for that, but I'd rather leave comment as ad-hoc freetext. Author / source seems to me as relevant / important / meaningful property of each patch and is easy to understand for majority of users. 

Some might prefer comment 1, comment 2 and comment 3 and define their own approach how to handle metadata, but that would be less intuitive and more difficult to manage, especially if sharing patches with other users etc.
