### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#77]
I suggest:
1. Have the search field always visible, I think it will be used a lot. 
2. On the other hand, I think that the "filter for specific import" is of lesser importance
2. Have search also go thru the proposed meta data
3. have an "X" button at the end of the search field to quickly erase all typed in text
4. I always get confused what a) sets a category and b) filters a category. A clearer visual distinction between "editing" stuff (labeling, setting category) and "playing/sending" programs would be helpful plus naming the sections of the UI.

**Comment by christofmuc** [comment]
Good points! Except I use the filter by import a lot, because I have imported some commercial soundbanks, and then go to "Synthwave Luke Neptune" or something when I want a specific sound. 

The editing/filtering happens to me a lot as well, I think the sidebar design will reduce that, as well I want to get the tagging into a two click solution like here in the Labels menu at github - you first have to click a menu, and then can add a category (or multiple).

**Comment by markusschloesser** [comment]
maybe you could split the current field in half? And then use that space for both?
Also
6: Is there a special reason why the current search is context sensitive? Needn't be imho ;-)

**Comment by christofmuc** [comment]
You mean case sensitive? Didn't even notice that. That can be turned off.
And yes, the layout of the search is troubling me a bit, at some point I need to really re-layout the whole area.

**Comment by markusschloesser** [comment]
yep, meant case sensitive. Turning off would be great! 

me too :-) I'll try to think of something

**Comment by christofmuc** [comment]
That is weird, for me, it is case-insensitive. I couldn't remember it being case sensitive.

Proof:
![grafik](https://user-images.githubusercontent.com/5006524/104789467-6586aa80-5795-11eb-9b8e-71a50a291f2b.png)

**Comment by markusschloesser** [comment]
I believe you, but I for me it's definitely case sensitive. (win10 20h2)

**Comment by christofmuc** [comment]
@markusschloesser That sounds like a language setting or a locale. What language is your OS/your locale setting? English?

**Comment by markusschloesser** [comment]
US English

**Comment by markusschloesser** [comment]
case sensitivity is fixed!

**Comment by markusschloesser** [comment]
I'll try to do a UI suggestions thing:
1. This is how it currently looks like on my laptop (3200x1800 resolution on 13" screen)
![image](https://user-images.githubusercontent.com/59286549/107272664-53bfbc80-6a4e-11eb-85cb-7268b97af38d.png)
2. there a multiple menus at play here, 6 on top, 1 at the bottom. All these lead to not much left in terms of height. So my proposal is to have the "library" view as default and put all other buttons (Adaptation, Macros, Setup etc) in their respective OS menu categories  
![image](https://user-images.githubusercontent.com/59286549/107273177-0132d000-6a4f-11eb-89f0-bfebf2384a25.png). 

- Adaptation into the setup menu for the specific synth, or into "Help",
- Macros should be part of "Setup"
- Setup should go into "File", 
- Midi Log into "Help"
3. The other log (not the midi log), should also go into "Help" and be named differently, how about "Connection Log". 2 and 3 should you give plenty more height/space.
4. Width: there are 3 different widths: 
   a) categorization 
   b) Filter category
   c) Patches/Presets
How about having them all the same width?
5. The filter category buttons are sharp edged and not rounded, like all other buttons. They are also a different height. 
6. Naming of buttons: I would suggest headlines for the UI things ("Filter by category", "Categorize Preset", "Presets/Patches"
7. When changing height by pulling the line above the log up, ONLY the preset button heights change. (If you put the log somewhere else that line can be disposed off).
8. Make the amount of presets shown vertically and horizontally user configurable. 
9. Is the "Auto-detect Synths" function under the "Midi" menu identical to "Auto-Configure" in "Setup"? If yes, the should be named identically or even better, get rid of one :-)
10. (active) Synth selection: Make them bigger/give them more height. 
![image](https://user-images.githubusercontent.com/59286549/107275749-72c04d80-6a52-11eb-9d65-62dfeb74595b.png)
I think there is some space left underneath them. Also "active" and "selected" state could be done just by using colors. So bright green for "active and selected ", olive green for "active but not selected", dark red for "not active". With that you would gain the space for the current green line.
11. I like hover for help tips, but of course that doesn't work with touch interfaces

**Comment by christofmuc** [comment]
@markusschloesser  Good stuff! I know I am shying away from a proper relayouting session, so know I am motivated to start tackling it! I personally don't like the OS menu very much, as it is not touch friendly, but agree that we have one menu bar too many. The menu bar at the bottom us actually more of a toolbar, maybe we can put it vertically to the right side?

**Comment by christofmuc** [comment]
1.13.0 tries to address the following items:  

> I suggest:
> 
>     1. Have the search field always visible, I think it will be used a lot.
Done, bigger font, always visible.
 
>     2. On the other hand, I think that the "filter for specific import" is of lesser importance
Moved into left sidebar.

>     3. Have search also go thru the proposed meta data
No meta data yet, recorded over there.
 
>     4. have an "X" button at the end of the search field to quickly erase all typed in text
Done.
 
>     5. I always get confused what a) sets a category and b) filters a category. A clearer visual distinction between "editing" stuff (labeling, setting category) and "playing/sending" programs would be helpful plus naming the sections of the UI.
This should be better now, but I need to useability test the 1.13.0 myself to see how it turned out.

**Comment by christofmuc** [comment]
And of these, 1.13.0 addresses:

> I'll try to do a UI suggestions thing:
> 
>     2. there a multiple menus at play here, 6 on top, 1 at the bottom. All these lead to not much left in terms of height. So my proposal is to have the "library" view as default and put all other buttons (Adaptation, Macros, Setup etc) in their respective OS menu categories
I still use the tabs (the library .. menu a lot, also for other (upcoming) features. But I tried to make the new later a bit less generous on using the y-axis. 
 
>     2. Width: there are 3 different widths:
>        a) categorization
>        b) Filter category
>        c) Patches/Presets
>        How about having them all the same width?
I tried to clean this up a bit more, please let me know how you like the new version, 
 
>     3. The filter category buttons are sharp edged and not rounded, like all other buttons. They are also a different height.
This should be fixed, thanks for pointing it out!

>     4. Naming of buttons: I would suggest headlines for the UI things ("Filter by category", "Categorize Preset", "Presets/Patches"
Have to try this, currently can't really picture how to squeeze this in!
 
>     5. When changing height by pulling the line above the log up, ONLY the preset button heights change. (If you put the log somewhere else that line can be disposed off).
The splitter now stores its position, and you can push it down so only 2 lines or so of log are visible. This is a simple solution that lets you at least see some disastrous warning there ;-)

>     6. Make the amount of presets shown vertically and horizontally user configurable.
Done, for now only in 8x8. 7x7. 6x6. Let's see how this works!
 
>     7. Is the "Auto-detect Synths" function under the "Midi" menu identical to "Auto-Configure" in "Setup"? If yes, the should be named identically or even better, get rid of one :-)
True, will take this on the list.
 
>     8. (active) Synth selection: Make them bigger/give them more height.
>        I think there is some space left underneath them. Also "active" and "selected" state could be done just by using colors. So bright green for "active and selected ", olive green for "active but not selected", dark red for "not active". With that you would gain the space for the current green line.
I have another use for the upper line: I want to show which patch is currently loaded into which synth, so I'd need the second row to show the patch name in each synth. That is really useful e.g. if you're jamming and forgot which patch is currently active in the OB-6 for example (which has no patch name display, but just these 7-segment displays).
 
>     9. I like hover for help tips, but of course that doesn't work with touch interfaces
I found hovers in the JUCE framework - I turned them on for the import list (the names are way too long there, I need to reformat them, but for now the import list has a tooltip that shows the full text). Not sure if I like it.

**Comment by christofmuc** [comment]
@markusschloesser Beta release 1.13.0 for Windows is at https://github.com/christofmuc/KnobKraft-orm/releases/tag/1.13.0

**Comment by markusschloesser** [comment]
wow, great!
want to first fix my db mess before updating, but very much looking forward to all the great improvements! 👍

**Comment by markusschloesser** [comment]
I just realized that I never commented on this, apologies! It looks sooo much better now and is also a lot easier to use!!! 😊

I'll add a 12th suggestion:
12. Can you make the category assignment buttons bigger or resizable? I mainly use the touchscreen of the laptop which works great for selecting patches but is rather fiddly when assigning categories and/or favoriting/hiding patches.

**Comment by Andy2No** [comment]
I like the new patch numbers - I was still on 1.13.2, not realising there was an update since then, due to #56 

However, perhaps due to my lowish resolution monitor (1360x768) and unusual system font size scaling (I'm now using 120% custom scaling), I'm getting the numbers overlayed on the bottom left corner of the first letter of each patch name - that's when set to the most comfortable view scale, for me, of 125%

Perhaps the patch number could be moved to top right, instead of bottom left?  All patches have a first letter, but not all have a last one, plus the full patch name doesn't always fit anyway, so it's less of an issue if the last letter is partially obscured.  Also, first letters tend to be capitals. whereas the last letter often isn't, so it's less likely that it needs the top right corner:

![Patch numbers overlaying names, at 125pc view](https://user-images.githubusercontent.com/8021302/147127152-0f18dd37-cf28-47d9-94e4-0f2daca057d8.gif)

**Comment by markusschloesser** [comment]
I think we two cover the most extreme differences when it comes to screen real estate. The laptop I am using mainly for kk has a 13,5" (touch screen) display with a resolution of 3840 x 2400 (4k but with 16:10), Windows scaling set to 250% (recommended  by Windows would've been 300%)

**Comment by markusschloesser** [comment]
> I like the new patch numbers - I was still on 1.13.2, not realising there was an update since then, due to checking for updates not working #56

I though that these came from the MKS-80 but they are for all synths now? Will need to check, but yes, great idea!
Are those unique per synth? Adaptation? DB?

**Comment by Andy2No** [comment]
> I though that these came from the MKS-80 but they are for all synths now? Will need to check, but yes, great idea! Are those unique per synth? Adaptation? DB?

They are there for all the synths I've got working adaptations for - I don't really have a Minilogue XD one - that's just a place marker.

The Yamaha Reface DX patches I've checked all say "Bank0-0", interestingly.  I saved them as single patches, a while ago, so they're presumably edit buffer dumps, without a patch or bank number.

The DeepMind 12 ones are numbered 0 to 127, then start again - those are dumps of banks from the synth, IIRC.  The DSI 
Mopho factory set is numbered 0 to 383. so I guess they don't really have a separate bank number.

![Reface DX (edit dunps q) - all say Bank0-0](https://user-images.githubusercontent.com/8021302/147212853-628e287d-f728-40e7-908b-b396b90f1692.gif)

![Mopho factory to 383](https://user-images.githubusercontent.com/8021302/147212882-299e0eb2-3487-4bc7-808c-f144aad38c74.gif)

**Comment by christofmuc** [comment]
@markusschloesser @Andy2No Thank you for the suggestions! I created two new items #127 and #128.

Regarding the patch numbers displayed - given that the Orm so far was not really about bank management I didn't care so much for the original patch number. It currently has a MIDI program location (bank + program number) when the patch data itself contains it, i.e. the Adaptation can implement a function "numberFromDump" to extract it from the MIDI message.

This is why edit buffer dumps when stored always show 0, and if the MIDI message contains only a program number (0-127) and not the bank, it will also always end up in bank 0. 

I was trying to keep more information during the ingest operation, because then I would know e.g. "ah, this was read at position 17 when getting all patches from the Yamaha reface DX (which has no program place stored in the patch data)", but I think this doesn't work everywhere yet (#104 ).

Also, people want a configurable display because for example the OB-6 has program names stored, but for the sake of retro look has only a 7-segment 3 digit program display, so most people will not know the name of a patch, only the original program number. So I want to make a switch to actually select what should be displayed on the button.

**Comment by Andy2No** [comment]
> @markusschloesser @Andy2No Thank you for the suggestions! I created two new items #127 and #128.
> 
> Regarding the patch numbers displayed - given that the Orm so far was not really about bank management I didn't care so much for the original patch number. It currently has a MIDI program location (bank + program number) when the patch data itself contains it, i.e. the Adaptation can implement a function "numberFromDump" to extract it from the MIDI message.

Just to tie these pages together, I've just got my Korg Minilogue XD adaptation working, more or less, and I have implemented numberFromDump(), but I haven't managed to get it to show the patch number properly - it's currently showing as 0-127, then repeating four times.  Patches are actually numbered 1-500, but treating it as four banks of 128 doesn't seem to cause any major problems.

I've made a discussion page for that adaptation:

https://github.com/christofmuc/KnobKraft-orm/discussions/133

The adaptation source is attached there.

It seems that numberFromDump() isn't having any effect - I got the same results before I added it.  I  may have just done something wrong, of course :)

```
def numberFromDump(message):
    progLSB = message[7]
    progMSB = message[8]
    return progLSB + progMSB * numberOfPatchesPerBank()
```

**Comment by christofmuc** [comment]
I'll close this longish and by now outdated ticket. There are a few open tickets for some of the issues that came up here, and I'd rather create new ones with more specific items. I went through the text again today and don't feel there is much we haven't discussed and captured elsewhere. When there are still problems with the Monologue XD, we should open a new ticket.
