### ISSUE TITLE
smallish design errors - html code in menus

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#81]
see screenshots
![image](https://user-images.githubusercontent.com/59286549/105397435-56827b00-5c21-11eb-96e5-a124d77c18b2.png)

![image](https://user-images.githubusercontent.com/59286549/105397448-5bdfc580-5c21-11eb-87ad-15bc3ab5f29f.png)

there seems to be some html code where it's not supposed to be

**Comment by christofmuc** [comment]
I can imagine what brought it there, but not why ;-) Will fix.

**Comment by christofmuc** [comment]
will be part of 1.12.0 release

**Comment by christofmuc** [comment]
Released with 1.12.0
