### ISSUE TITLE
crash after edit buffer import A6

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#86]
just had a crash after a successful edit buffer import from the Andromeda. I know it was successful because a subsequent import saif "already in db".
Did you get the crash log automatically? Do you know what happened? I couldn't reproduce the crash

**Comment by christofmuc** [comment]
@markusschloesser Strangley, again no crash dump. By now I feel this Sentry thing is not rely reliable, and I should also look at other solutions... unless your firewall is blocking this, but I thought at some point it had worked!

**Comment by markusschloesser** [comment]
it did work in the past, don't remember which computer though.
Laptop has been idle for 3 hrs and kk has a constant cpu usage of 25-30%, could be related?
[sentry.zip](https://github.com/christofmuc/KnobKraft-orm/files/5947416/sentry.zip)
edit: kk actually hang (not crashed), sentry zip attached

**Comment by christofmuc** [comment]
Thank you! There is one crash dump from today, 21:37. This looks like it crashed when reloading an Adaptation.

**Comment by markusschloesser** [comment]
I found a possible reason for the hanging. The Andromeda keeps sending shitloads of nrpn data currently and after a certain amount kk gives up. Log attached. The trouble maker is the a6, however kk shouldn't hang either? ;-)
[nrpn p12 drama kk.zip](https://github.com/christofmuc/KnobKraft-orm/files/5962263/nrpn.p12.drama.kk.zip)

**Comment by markusschloesser** [comment]
this was fixed in the release, closing
