### ISSUE TITLE
Feature request: copy /show patch sysex 

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#87]
My use case is ableton, somebody wrote a M4l device (https://maxforlive.com/library/device/6998/cf-sysex-recorder) to "play back" sysex when opening a song. I'm gonna ask the creator to not only show recorded sysex, but also paste sysex into the M4l device.
For that it would be helpful, if kk could "show" the sysex of a patch. Alternatively copy to clipboard.

**Comment by christofmuc** [comment]
@markusschloesser That should be easy. Would we know which clipboard format? We could do text in hex string (nice to also check for problems) or pure binary bytes.

Sorry for now getting more done, past three weeks I was stuck on a completely different project ;)

**Comment by markusschloesser** [comment]
no need for apologies! :-)
the m4l device sends exactly out, what is pasted there, so probably binary. Or do some synths expect hex?

**Comment by christofmuc** [comment]
Can you give an example of text/content that you successfully pasted into M4L, and where you got it from (e.g. from which software did you copy it)?

The reason I am asking is that the clipboard has the concept of "data types", so M4L might allow more than one data type, and could maybe even convert text pasted into sysex already.

You can also try it out with a regular text editor like notepad, e.g. you could copy a text string like f0 7e 7f 06 01 f7 into the clipboard with notepad and see if you can paste it, and if it gets sent.

**Comment by christofmuc** [comment]
Ok, the author actually specified the format he needs, I can try that... it is a pretty specific function though ;-O

**Comment by christofmuc** [comment]
Hi Markus, I made a menu item that creates a string in the clipboard for the current patch.

Can you try to paste this string into the CF sysex recorder and see if it is accepted? This is the Kijimi patch "000" as I found it in my database, it looks like valid sysex to me:

    "sysex" : [240, 2, 19, 0, 127, 11, 34, 0, 37, 62, 60, 58, 60, 60, 93, 60, 0, 61, 61, 0, 126, 59, 94, 0, 0, 29, 73, 106, 27, 45, 114, 114, 40, 126, 66, 42, 112, 60, 62, 0, 104, 67, 60, 33, 9, 35, 31, 0, 15, 100, 65, 0, 126, 0, 3, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 4, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 8, 4, 0, 0, 8, 10, 1, 0, 0, 0, 1, 0, 100, 10, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 0, 1, 1, 1, 1, 1, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 247]

If that works, I can make it part of the next release!

**Comment by christofmuc** [comment]
Released with version 1.12.2, which sadly won't auto update from 1.12.1, needs to be manually installed.
