### ISSUE TITLE
New feature: Bank management

### ISSUE THREAD

**Issue by christofmuc** [christofmuc/KnobKraft-orm#9]
The Orm is currently meant to be used as a computer-based patch librarian, for easy backup, quick sifting through patch banks and easy management of own patches stored in synths. 

It is not (yet) a bank manager. 

For that, we'd need a UI that allows the user to sort patches (drag and drop), and build new lists of patches from the overall library. Then those could be sent to the synth as a patch bank. 

Technically easy (the MIDI communication and patch uploads etc. are there), but the UI needs some thinking as it should be self-explanatory and efficient at the same time, and ideally also work on future tablet versions.

If somebody has a recommendation of a program that did a very good solution, I'd be happy to have a look.

**Comment by christofmuc** [comment]
Oh, this came up here: [https://forum.sequential.com/index.php/topic,4327.0.html](url)

**Comment by christofmuc** [comment]
Thinking about this, I will rather go with list management - you might want to create list of patches for different purposes (song ideas, jam sessions, ...). The bank would then be a special kind of list, possibly created from a list in the first place (turn list into bank)...

This would also solve the problem of creating a partial bank or updating only a few places in an existing bank.

**Comment by christofmuc** [comment]
Also idea from GS: "There's needs to be a way to tag a sound as Reject and then see those and put a better patch there. For instance I have Banks A-H on the Virus C but I have a Sounddiver Library of over 2k patches. I want to have my Virus loaded with a best of, so somehow I need to sort out the crap first. Ideally I'd like to see the banks and another Library view of All Sounds."

https://www.gearslutz.com/board/music-computers/1334549-sounddiver-2021-a.html

**Comment by christofmuc** [comment]
This should also allow for requesting single patches from the synth,

**Comment by Andy2No** [comment]
It would be nice to be able to sort patches in a bank in the original order, as on the synth, when there's just a single bank of patches showing in Orm.  I realise that's a special case though, so maybe not easy to do.

**Comment by christofmuc** [comment]
Came from Sequential forum:

> Would be good if it were possible to drag and drop patches within the window so that they could be easily written back to the synth in a new location.

https://forum.sequential.com/index.php/topic,4769.msg54511.html#msg54511

**Comment by christofmuc** [comment]
Also from the same post:

> Being able to write back to the synth directly in the app would be great.

**Comment by christofmuc** [comment]
Released version 2.0.0 today as a beta, which contains my interpretation of bank management. Happy to get feedback (preferably in new tickets/issues).
