### ISSUE TITLE
failure to open database

### ISSUE THREAD

**Issue by markusschloesser** [christofmuc/KnobKraft-orm#90]
![image](https://user-images.githubusercontent.com/59286549/113925778-b41f7000-97eb-11eb-9d6d-635daa9c2bd8.png)
cannot do anything right now

**Comment by Andy2No** [comment]
Yes, same problem for me too (Windows 7).  After I press OK on that message, it crashes, with the standard "Close or Debug" dialog box.

Possibly we can get around it by deleting the database, or uninstalling Orm then installing it again - I just installed it over the top of the previous one, as usual.

Maybe there's something else I should try first, for debugging reasons?

**Comment by christofmuc** [comment]
Oh dear. You could try to backup the settings file from %APPDATA%\KnobKraftOrm\KnobKraftOrm.settings and start without that file. That should at least give you the opportunity to create a new database. 

I wonder what is wrong in the migration code, I can look at it later today. You should be able to load the before migration back with the 1.11.x version :-(

**Comment by christofmuc** [comment]
Found the problem, a stupid double create, so no data was harmed. Will build a version that should open the database without error and re-release.

**Comment by christofmuc** [comment]
Should be fixed with 1.12.1

**Comment by Andy2No** [comment]
Yep.  1.12.1 opens fine for me.  That's all I've tried, so far.
