### ISSUE TITLE
Import files from CPU - Prophet 10 

### ISSUE THREAD

**Issue by trusampler** [christofmuc/KnobKraft-orm#99]
Hi,
    I have my Prophet 10 working great with the latest update,  other then import files from cpu. Seems to not be working, is there anyone else using the latest update that can import to the prophet? thanks

**Comment by christofmuc** [comment]
@trusampler Good to hear from you! Can you detail what you tried and what does not work? Maybe add a screenshot here - the import from the Synth only works when the Synth has been detected by the software, try to run the menu "MIDI" auto-detect synths function and see if you get a green bar below the synth name at the top - that indicates the synth is fully detected and can transfer MIDI in both directions.

**Comment by trusampler** [comment]
Hi, Thanks for the reply,vi just got to work and will be away from my cpu
for a few. Once I return, I will send you a screenshot. Thanks so much for
your quick reply. Love your software.

**Comment by trusampler** [comment]
Hello,           I re ran the auto detect synths, and yes the green bar is there. I have attached a screenshot. I do notice I can change patches with no issues, yet each time I try to import, it will not.Thanks for the help in advance, and for making a great tool.      Sent from Mail for Windows 10 From: ChristofSent: Friday, July 9, 2021 6:04 AMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 ***@***.*** Good to hear from you! Can you detail what you tried and what does not work? Maybe add a screenshot here - the import from the Synth only works when the Synth has been detected by the software, try to run the menu "MIDI" auto-detect synths function and see if you get a green bar below the synth name at the top - that indicates the synth is fully detected and can transfer MIDI in both directions.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by trusampler** [comment]
![screenshot 1](https://user-images.githubusercontent.com/87179285/125290266-1fe30e80-e2ee-11eb-8a22-e94362dfc78a.png)
Heres a copy of the screenshot, it indeed shows green ,but the import files from cpu, doesn't seem to work. thnx

**Comment by christofmuc** [comment]
@trusampler Looks good indeed - can you attach also the MIDI Log? It should show the messages the computer is trying to send to the synth.

**Comment by trusampler** [comment]
Hi, I saved this midi log,is this the file you need? thnx Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 10:02 AMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 ***@***.*** Looks good indeed - can you attach also the MIDI Log? It should show the messages the computer is trying to send to the synth.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christofmuc** [comment]
@trusampler Hm, I don't think the mail attachment went through, you might need to upload the file on github directly :-/

**Comment by trusampler** [comment]
[midi log.log](https://github.com/christofmuc/KnobKraft-orm/files/6802739/midi.log.log)

I saved a midi log here my friend.

**Comment by trusampler** [comment]
Ok, uploaded thnx Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 11:47 AMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 ***@***.*** Hm, I don't think the mail attachment went through, you might need to upload the file on github directly :-/—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christofmuc** [comment]
@trusampler Ah, that is the log from the log window - can you also share the log from the "MIDI log" window? That shows the individual commands sent and received from the MIDI interface.

**Comment by trusampler** [comment]
Hi, where would I be able to find this ? Thnx

**Comment by christofmuc** [comment]
There is a tab next to Setup... that reads MIDI log.

**Comment by trusampler** [comment]
[midi log - correct.log](https://github.com/christofmuc/KnobKraft-orm/files/6803633/midi.log.-.correct.log)

Here's the correct file, thanks

**Comment by christofmuc** [comment]
Great! Can you send me the log from after trying to download a bank from the Prophet 10?

**Comment by trusampler** [comment]
[midi log - trying to import from cpu.log](https://github.com/christofmuc/KnobKraft-orm/files/6804010/midi.log.-.trying.to.import.from.cpu.log)

**Comment by trusampler** [comment]
Hi,   Uploaded now, thanks Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 3:26 PMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 (#99) Great! Can you send me the log from after trying to download a bank from the Prophet 10?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christofmuc** [comment]
Hm, this is strange, this is the same commands we use for doing an auto-detect/quick detect. Did you try to run "import patches from synth" (lower left corner) and select a synth? A different command should be sent to the synth then in the MIDI log.

**Comment by trusampler** [comment]
Hi,  1.   I just selected Prophet 5/10 tab 2. then import sysex from cpu.  I then tried to import from sysex, then clicked tab.. same thing no response.   Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 3:51 PMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 (#99) Hm, this is strange, this is the same commands we use for doing an auto-detect/quick detect. Did you try to run "import patches from synth" (lower left corner) and select a synth? A different command should be sent to the synth then in the MIDI log.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christofmuc** [comment]
Yes, but how does the MIDI log look like? Does it show the command f0 01 ... that I showed above?

**Comment by trusampler** [comment]
[midi log - new.log](https://github.com/christofmuc/KnobKraft-orm/files/6804315/midi.log.-.new.log)
Here's what I get after trying to import from cpu

**Comment by trusampler** [comment]
02:26:44.392: Out Prophet 5/10 Sysex [f0 7e 01 06 01 f7]02:26:44.393: In  Prophet 5/10 Sysex [f0 7e 7f 06 02 01 32 01 00 00 01 05 02 f7]02:27:32.550: In  Prophet 5/10 Note on G#4 Velocity 1 Channel 1 [90 50 01]02:27:32.616: In  Prophet 5/10 Note on F#4 Velocity 102 Channel 1 [90 4e 66]02:27:32.622: In  Prophet 5/10 Note off G#4 Velocity 0 Channel 1 [80 50 00]02:27:32.718: In  Prophet 5/10 Note off F#4 Velocity 0 Channel 1 [80 4e 00]02:27:32.753: In  Prophet 5/10 Note on F#4 Velocity 41 Channel 1 [90 4e 29]02:27:32.838: In  Prophet 5/10 Note off F#4 Velocity 0 Channel 1 [80 4e 00]02:27:32.844: In  Prophet 5/10 Note on D#4 Velocity 102 Channel 1 [90 4b 66]02:27:32.879: In  Prophet 5/10 Note on C#4 Velocity 81 Channel 1 [90 49 51]02:27:32.910: In  Prophet 5/10 Note off D#4 Velocity 0 Channel 1 [80 4b 00]02:27:32.925: In  Prophet 5/10 Note off C#4 Velocity 0 Channel 1 [80 49 00]02:27:32.931: In  Prophet 5/10 Note on A#3 Velocity 107 Channel 1 [90 46 6b]02:27:32.980: In  Prophet 5/10 Note off A#3 Velocity 0 Channel 1 [80 46 00] Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 4:54 PMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 (#99) Yes, but how does the MIDI log look like? Does it show the command f0 01 ... that I showed above?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christofmuc** [comment]
Ok, this is very weird. Do you click "Import patches from synth", and then select bank 1, and press "Import"?

**Comment by trusampler** [comment]
Hi,     Yes I do, I have all the patches imported from synth fine, yet when I try to import sysex files from cpu, it does nothing at all. I was under the impression a few versions ago, I was able to do this command, but it’s been awhile, and not sure if it was working in here, or midi ox. Does it work on your end?  Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 5:34 PMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 (#99) Ok, this is very weird. Do you click "Import patches from synth", and then select bank 1, and press "Import"?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by trusampler** [comment]
Come to think of it, I've tried to import sysex from cpu, none of the synths I own are able to import correctly.

**Comment by trusampler** [comment]
Yet the program changes, work on all synths just fine.

**Comment by christofmuc** [comment]
Phew. When I click import bank from synth for the Prophet 5, even if I don't have one, it shows this command in the MIDI log being sent to the synth: [f0 01 32 05 00 00 f7]. The synth will reply with a patch. In your case, this command is never sent even though the synths are detected all fine.

It could be good to test only a single synth being connected at one time, and close all other MIDI software, and re-run the auto-detection for the single synth. This way we can rule out that the software somehow expects an answer on the wrong device (even if the green bar indicates it has done a proper two-way communication with the synth). 

Other than that, maybe can you do a Video capture of the software, with a click on the MIDI log button at the end? You could do that by using the PSR command in Windows (ALT-R, type psr), this will launch the "Problem Step Recorder" built into Windows. You can then start recording and click through the software, and it will create a nice report for me with lots of screenshots that you can upload here.

**Comment by trusampler** [comment]
Ok sounds great, thanks  Sent from Mail for Windows 10 From: ChristofSent: Monday, July 12, 2021 6:20 PMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 (#99) Phew. When I click import bank from synth for the Prophet 5, even if I don't have one, it shows this command in the MIDI log being sent to the synth: [f0 01 32 05 00 00 f7]. The synth will reply with a patch. In your case, this command is never sent even though the synths are detected all fine.It could be good to test only a single synth being connected at one time, and close all other MIDI software, and re-run the auto-detection for the single synth. This way we can rule out that the software somehow expects an answer on the wrong device (even if the green bar indicates it has done a proper two-way communication with the synth).Other than that, maybe can you do a Video capture of the software, with a click on the MIDI log button at the end? You could do that by using the PSR command in Windows (ALT-R, type psr), this will launch the "Problem Step Recorder" built into Windows. You can then start recording and click through the software, and it will create a nice report for me with lots of screenshots that you can upload here.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by christofmuc** [comment]
@trusampler Hi! Did you get any other success after our conversation? It seems strange that no MIDI messages sent are logged when you do the download operation.

**Comment by trusampler** [comment]
Hello,           Not as of yet, I’ve been working long hrs, but hope to return back  to test soon. thnx Sent from Mail for Windows 10 From: ChristofSent: Thursday, July 22, 2021 4:08 PMTo: christofmuc/KnobKraft-ormCc: trusampler; MentionSubject: Re: [christofmuc/KnobKraft-orm] Import files from CPU - Prophet 10 ***@***.*** Hi! Did you get any other success after our conversation? It seems strange that no MIDI messages sent are logged when you do the download operation.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
